### ISSUE TITLE
cannot import from google drive

### ISSUE THREAD

**Issue by LANXIANGMING** [jarrodek/ChromeRestClient#1001]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 57.0.2987.133
Platform: Mac OS X (10_11_6)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
