### ISSUE TITLE
Project list doesn't update when adding a new entry

### ISSUE THREAD

**Issue by PatrM** [jarrodek/ChromeRestClient#1003]
## Steps to reproduce
1. expand existing project
2. click on existing service
3. create new service and add it to said project
4. new service gets saved to project

## Expected outcome
to 4: new service gets saved and added to the existing list of projects' services 

## Actual outcome
to 4: last used service's name gets replaced with the new service, nothing is being added in the view
* the actual new list appears after collapsing and expanding the project manually, so something might be wrong with the refreshing after adding new services

## Versions
App: 9.14.64.305-stable
Chrome: 58.0.3029.110
Platform: Windows (10)

**Comment by jarrodek** [comment]
This is fixed already and will be released soon.
