### ISSUE TITLE
Toolbar moved up

### ISSUE THREAD

**Issue by metaer** [jarrodek/ChromeRestClient#1004]
Toolbar moved up
screenshot: http://joxi.ru/p2784P5uojGM7A?d=1

## Expected outcome
Toolbar in the bottom

## Actual outcome
Toolbar moved up

## Versions
App: 9.14.64.305-stable
Chrome: 58.0.3029.110
Platform: Mac OS X (10_12_4)
monitor 1280x800
application window in full screen

## Steps to reproduce
1. Set http method POST and more then 5 fields in data form
2. set raw headers (as in screenshot)
3. save project (both checkboxes are checked, including google drive)
4. send request several times

**Comment by jarrodek** [comment]
This is already fixed and will be available with new release.
