### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by antivir88** [jarrodek/ChromeRestClient#1006]
ARC insert cookies into request without adding (from tab)

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 57.0.2987.133
Platform: Linux (-)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
That is right and this is expected behaviour. ARC behaves as any other HTTP client meaning it will remember cookies receiver from the server and insert them into subsequent requests.

I'll close this as WAI.
