### ISSUE TITLE
Move the application to Electron

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#1012]
When #1011 is ready then move the shell to the electron application.

The electron will be released for:
- Windows
- Mac OS
- Linux (research needed about supported platforms)

Because at this point elements are externalized to the ARC organization it should be matter of moving high level components into new architecture and replacing Chrome specific API with Node APIs.

Threads:
- low level components can contain logic not available for Electron. Change in this components will be required
- `socket-fetch` library must be adopted to Node environment. I may not be possible. Then a new similar implementation for Node's Socket will be required. Either way the implementation must comply with  #1010

**Comment by gear54rus** [comment]
@jarrodek are you sure that this is the best course of action?

Just as we got a standard API for multiple browsers from which the ARC could benefit, the extension gets transferred to 'native' platform, is there clear benefit to this? Did this decision stem from the difficulty of sending unrestricted HTTP requests?

There are benefits to being an extension such as retrieving data about current page (to pull some tokens or URLs from the environment the user is already in) and communicating with the browser in general.

**Comment by jarrodek** [comment]
Hi,

Generally you are right. But the app already is having difficulties of getting data from the Chrome session. Chrome apps are separated from this session and you need additional extension to be installed.

I am considering creating an extension with limited functionality. The limitations are mostly related to transport object. I'm also considering this as a DevTools panel but it might be not that convenient to use.

The primary use case will be electron app. This allows me to create other applications that support each other and can exchange data. With extensions that wouldn't be possible.

**Comment by jarrodek** [comment]
Electron app is now created. But because the code is not yet signed I'm not going to publish installation URL as for now. I'll publish this information very soon here, on the blog and in the application.
