### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by alikini** [jarrodek/ChromeRestClient#1015]
Not able to set Authorization header for request ... 

Scenario: trying to send PUT request , that requires header to be sent : 
Authorization : "token_string" . 
Sending, getting error: 401: Authorization required . 

Thank you

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
Is the token valid?
You can check if the header is sent with the request in the response status details:

![image](https://user-images.githubusercontent.com/3320020/27650189-06144f5c-5c2c-11e7-8797-692320d2ed1c.png)

Otherwise I can't reproduce the problem.

**Comment by alikini** [comment]
Thank you response !
In my case, I have to send Authorization token. not a basic authentication.

I am able to send same request with header  and same value from another
rest client, but not from yours.

It should send simple : Authorization: token_value .  in header.

just tried again with restlet_client and it worked fine with same values as
was sent in your client .





Alexander Berezovsky
Mobile: +972 544753104

**Comment by jarrodek** [comment]
Alexander,

It doesn't matter if this is basic, oauth or custom authorization scheme. My question was if can you see the authorization header with your value in the source message (this is what actually has been sent to the server). Compare it with your token. If the correct value is there then there's not a problem of the application but server.

Thanks.
