### ISSUE TITLE
Unable to initiate requests in offline mode.

### ISSUE THREAD

**Issue by TobiasLounsbury** [jarrodek/ChromeRestClient#1016]
**Problem:** When chrome is in "offline" mode ARC does not allow any requests. 
**Use case:** Anytime a request does not actually require network access such as when debugging a local resource on a flight.
**Possible Solutions:**
1. Create a setting that overrides this behavior and allows requests
1. Create a setting that changes the blocking behavior to a warning behavior

**Comment by jarrodek** [comment]
This is fixed and will be available with new release.
