### ISSUE TITLE
Advanced REST Client versions with Chrome

### ISSUE THREAD

**Issue by engineeratomic** [jarrodek/ChromeRestClient#1017]
Not an issue except that I cant find what I am looking for. Can someone advise what version of Chrome are supported with the currently available Advanced REST Client.  I have Chrome v43 across 30k users. Upgrade is not a simple task. I need to check whether the client is supported or will work with this version of Chrome

Very many thanks

**Comment by jarrodek** [comment]
This is described in app's manifest here: https://github.com/jarrodek/ChromeRestClient/blob/develop/app/manifest.json#L8

Currently minimum version of chrome for ARC is 49 and it can only go up.
