### ISSUE TITLE
经常发生崩溃以及发送超时后会内存爆涨

### ISSUE THREAD

**Issue by psyuhen** [jarrodek/ChromeRestClient#1018]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 59.0.3071.104
Platform: Windows (10)

## Steps to reproduce
1.  打开HTTP request
2. 发送请求，请求超时后，不动，然后重新发送刚才的请求
3. 一直等待后，请求超时，过不久就内存爆涨。

**Comment by jarrodek** [comment]
Hi,

Will you be able to translate it to english?
