### ISSUE TITLE
Cannot post file

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#1019]
When do post data + file to API, my API could not get the post data and uploaded file.
I'm using PHP for API.

## Expected outcome
Get post data and uploaded file.

## Actual outcome
No post data and uploaded file ($_POST = [], $_FILES = [])

## Versions
App: 9.14.64.305-stable
Chrome: 58.0.3029.110
Platform: Linux (-) (Linux mint 17.1 Cinnamon 64bit version 2.4.8)

## Steps to reproduce
1. Create a POST request
2. Set Content-Type: application/x-www-form-urlencoded
3. Set Data form
4. Attach File
5. Send

**Comment by dunght160387** [comment]
I have tried to remove and reinstall ARC, but it still does not work.

Also, I have tried to use workaround by ARC Cookie Exchange, I got uploaded file but the attachment info is not correct (missing some parameters), and post data ($_POST) still empty.

**Comment by priyankaparab** [comment]
I am also facing the same issue.

**Comment by jarrodek** [comment]
This is duplicate of #945
The issue is related to bug in Chrome that disallow reading data from FormData object. In current version of Chrome this should be fixed.

**Comment by dunght160387** [comment]
Thank you @jarrodek ! Waiting for Chrome got fixed.
