### ISSUE TITLE
Header Key character casing is changed when request is made.

### ISSUE THREAD

**Issue by JonesTravis** [jarrodek/ChromeRestClient#1020]
Making a request changes the Character casing of the header keys. This is problematic when the endpoint is case sensitive in regards to header keys. 

To reproduce, use a header like "ABCD-Product-Accept: test-value" and make a request. In the details block where the request and response headers are displayed the request header will have been sent with the character casing "Abcd-Product-Accept: test-value".

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491for detailed discussion and explanation. I'm closing this as a duplicate and WAI. 

Thanks.
