### ISSUE TITLE
Variables are not saved in an Environment with parenthesis in the name

### ISSUE THREAD

**Issue by dkalcheu** [jarrodek/ChromeRestClient#1021]
## Steps to reproduce
1. Open an existing _Operation_ in a _Project_.
2. Go to **Variables** tab.
3. Click on **Add new environment** button.
4. Use a name with parenthesis, e.g. _**Test (Something)**_.
5. Click on **Save Environment** button.
6. Click on **ADD VARIABLE** button.
7. Add a new variable, e.g. _**test=variable**_.
8. Save the request under the existing project.
9. Select another _Environment_.
10. Switch back to _**Test (Something)**_.

## Expected outcome
The _**Test (Something)**_ environment should have _**test=variable**_ variable.

## Actual outcome
The _**Test (Something)**_ environment does not have any variables.

## Versions
App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I can confirm the bug in current version of the application.
The component responsible for this behavior has been fixed, however. New release is scheduled in coming  weeks.

**Comment by dkalcheu** [comment]
Great, thank you!

**Comment by jarrodek** [comment]
This is already fixed. New release coming soon.
