### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by himynameisoleg** [jarrodek/ChromeRestClient#1023]
Spelling mistake in "Saved Tab" under  "You don't have saved requests

## Expected outcome
OPEN FROM GOOGLE DRIVE

## Actual outcome
OPEB FROM GOOGLE DRIVE

## Versions
App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)

## Steps to reproduce
1. Navigate to Saved Tab on the right navigation of app
2. ensure you have no requests presnt
![bug](https://user-images.githubusercontent.com/5840837/28376641-40b0765a-6c70-11e7-85a9-abf011d69106.png)

3.

**Comment by jarrodek** [comment]
Thank you for issue report. I've already fixed that but I'm waiting with new release until I finish new request editor panel.
