### ISSUE TITLE
Typo in the Saved > button "OPEB FROM GOOGLE DRIVE"

### ISSUE THREAD

**Issue by cauveryguda** [jarrodek/ChromeRestClient#1024]
In Saved tab, when we don't have any saved requests. There is a typo on the button "OPEB FROM GOOGLE DRIVE"
![screen shot 2017-07-21 at 10 36 37 am](https://user-images.githubusercontent.com/12631004/28475316-8500c7b0-6e00-11e7-92e0-fa4479efca72.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. 
I've already fixed this in develop. I'm still working on few other issues before the release and then I'll update the main app.
