### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by teneous** [jarrodek/ChromeRestClient#1025]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)

## Steps to reproduce
1. application crash and have to restart it again
2. 
3.

**Comment by jarrodek** [comment]
What can I say....?

**Comment by jarrodek** [comment]
I mean seriously. Can you give me more details?
