### ISSUE TITLE
Feature: disable SSL validation option

### ISSUE THREAD

**Issue by technophil98** [jarrodek/ChromeRestClient#1026]
The client would benefit from a "disable SSL validation" which would allows to test not-yet-secured https REST routes.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report. This is duplicate of #432.

I really would like to do that, but.

Please refer to the cr-bug (https://bugs.chromium.org/p/chromium/issues/detail?id=603104) for reasons why it is not going to be fixed in the app.

I'm closing it as wont fix.
