### ISSUE TITLE
Bottom bar overlaps editable screen

### ISSUE THREAD

**Issue by sha2nkk** [jarrodek/ChromeRestClient#1027]
![bug](https://user-images.githubusercontent.com/6416158/28606383-6b2c486c-71f4-11e7-85b5-49392927f2e0.png)

## Expected outcome
bottom bar should be left hand.

## Actual outcome
Its blocking the button and editable view on right

## Versions

App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)

## Steps to reproduce
1. Maximize window(Screen res 1366x768)
2. Write JSON body long enough to be scrollable 
3. Scroll down

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I'll fix this very soon.

**Comment by HaoAtMLB** [comment]
Bump... also having this issue.

**Comment by jarrodek** [comment]
This is already fixed. Soon will be released.
