### ISSUE TITLE
On Ctrl + S the saved requests get reordered 

### ISSUE THREAD

**Issue by nafeydev** [jarrodek/ChromeRestClient#1028]
I have been seeing erratic behaviour with Ctrl+S on linux and mac (haven't tested on windows). Almost any time i try to do that the saved operations in operations list gets reordered. Here are some screenshots that exhibit that behaviour:
http://imgur.com/3UXKFYL
http://imgur.com/a/59WKL

On top of that sometimes Ctrl + S will overwrite existing saved operations. This usually happens only after I have created a new operation or renamed an existing one, but as I am not able to relaibly reporduce it I dont have the exact steps.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
In the screenshot, I'm assuming that saved was "test" request?

**Comment by nafey** [comment]
Yes that is correct

**Comment by nafey** [comment]
Is this going to be fixed in future?

**Comment by jarrodek** [comment]
This is already fixed but still not released. There are few minor bugs to be fixed before the release.
