### ISSUE TITLE
Feature Request: A way to group requests within a project

### ISSUE THREAD

**Issue by StephenCasella** [jarrodek/ChromeRestClient#1029]
I'm using ARC extensively for a large API I'm writing. I have my API autogenerating an ARC project file that I can import so I can easily play with all of the requests it supports. Unfortunately, when there are potentially hundreds of requests in the same project, it gets cumbersome to navigate between requests without enforcing a naming convention (and even then requests are not consistently displayed in alphabetical order across multiple application loads). The ability to create something like a folder within a project in ARC would be most useful. One level of depth would be sufficient.

**Comment by jarrodek** [comment]
Hi,

Thank you for the feature request. It seems reasonable. I'll push it into the roadmap since later I'm planning to do some changes in projects.

**Comment by jarrodek** [comment]
This is already supported on project details screen and new version will have reorder option in the quick list in the navigation panel.
