### ISSUE TITLE
Project JSON exported from ARC will not import on a new machine or the even original machine.

### ISSUE THREAD

**Issue by salientgreen** [jarrodek/ChromeRestClient#1034]
Cannot import project json file saved from arc to another machine

## Expected outcome
The json should import with 28 pre made requests

## Actual outcome
During the import process all 28 requests are shown on the import preview screen, but after the import the project shows no requests.

## Versions
App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)

## Steps to reproduce
 [PCR API Testing - Services - Oracle - POST - Copy.zip](https://github.com/jarrodek/ChromeRestClient/files/1209497/PCR.API.Testing.-.Services.-.Oracle.-.POST.-.Copy.zip)
1. Download the attached file
2. Import the attached file, notice the requests shown on the import screen
3. After importing, the project shows zero requests

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
I can reproduce the issue with this data but I can't find a problem. I've tracked execution of the import procedure and it is importing everything according to the algorithm. But in the end the databases is not even created.
I need to investigate this case further.

**Comment by jarrodek** [comment]
I just noticed that the imported data are saved in "saved" list without information about the project:
![image](https://user-images.githubusercontent.com/3320020/29371604-a0b9c558-825d-11e7-859c-471c0f3c4669.png)
So the problem would be with associating project data with saved requests.

**Comment by jarrodek** [comment]
This is fixed in ARC v10
