### ISSUE TITLE
Could you please put a environment toggle ? it would make us much more productive

### ISSUE THREAD

**Issue by paterlinimatias** [jarrodek/ChromeRestClient#1036]
Currently, there is an environment reference, you could change that into a toggle.

![screen shot 2017-08-09 at 11 41 21 am](https://user-images.githubusercontent.com/60751/29127552-d287d37e-7cf7-11e7-8f7d-41fb43aa4a3c.png)

**Comment by jarrodek** [comment]
That make a lot of sense. Thanks for pointing this out!

**Comment by jarrodek** [comment]
It's already in the code base. Soon it will be released.

**Comment by paterlinimatias** [comment]
That is awesome!

**Comment by jarrodek** [comment]
The release has been published with this issue resolved.
