### ISSUE TITLE
Variables and Header sets are not imported

### ISSUE THREAD

**Issue by RikWaspcroft** [jarrodek/ChromeRestClient#1037]
**Recreation steps:**

Scenario:
Export from ARC including "Saved requests and projects", "Header sets", "Variables and environments",
Then delete the projects, variables and header sets.
Import the exported file

Issue:
Variables and Header sets do not get imported.

**Comment by jarrodek** [comment]
Thank you for reporting this. This obviously shouldn't happen.

**Comment by jarrodek** [comment]
This is now fixed in the code. Soon it will be released.
