### ISSUE TITLE
Using variable for root path adds http:// prefix on enter

### ISSUE THREAD

**Issue by RikWaspcroft** [jarrodek/ChromeRestClient#1038]
**Recreation steps**

Scenario:
Setup a variable **domain** with a value of http://somevaliddomain.com
Add ${domain} to host input path (when shows Host and Path in one concatenated line)
Hit enter on line. http:// is prefixed to the ${domain} causing the request to fail

We have SSL certificates setup on UAT and PROD, we don't typically set these up on our local boxes

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I'm aware of this behavior. It will be fixed.

**Comment by jarrodek** [comment]
This is already fixed. Will be available in next release.
