### ISSUE TITLE
Not able to search from history using previously searched word

### ISSUE THREAD

**Issue by Karthikamenon01** [jarrodek/ChromeRestClient#1040]
Say,I searched in history used a word and i came back to history page after some time,i can see the previously searched term is retained on the search area,but on clicking enter,the search is not working.
Need to delete the word and enter again to make it work.
Not sure,whether to retain the previously search term is a use case,if so need to search how much ever times we try

## Expected outcome
the search should work without entering the whole word again

## Actual outcome
Not filtering the history the second time

## Versions
App: 9.14.64.305-stable
Chrome: 60.0.3112.90
Platform: Windows (8.1)

## Steps to reproduce
1. Go to History,search for a valid word
2. Navigate away from the page and go back again to History
3. Click on Search icon ,we can see the previous search term is retained
4.Now,just click on Enter to see whether the results are filtered
5.Delete the whole word and re enter again to verify whether  search works.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. I'll check this out soon and if can confirm I'll fix it.

**Comment by jarrodek** [comment]
This will be fixed in next release. It's already in the code base.
