### ISSUE TITLE
 这么测试图片上传，$_FILES为空

### ISSUE THREAD

**Issue by lixueyuanac** [jarrodek/ChromeRestClient#1043]
## 怎么获取files请求，通过multipart/form-data上传图片，获取不到图片路径
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 58.0.3029.110
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,
Is it possible for you to translate this to english, please?
