### ISSUE TITLE
Environment Variables not saved after closing and re-opening app

### ISSUE THREAD

**Issue by StewPoll** [jarrodek/ChromeRestClient#1045]
After working with a project and saving certain requests, and setting up a number of environment variables, when I close and re-open the app, all the environment variables have been cleared

## Expected outcome
Environment variables should be kept and "Saved" with their associated environments

## Actual outcome
Environment variables are deleted and the environments have no variables set upon start up

## Versions
App: 9.14.64.305-stable
Chrome: 60.0.3112.113
Platform: Mac OS X (10_12_5)

## Steps to reproduce
1. Create a new custom environment
2. Set environment variables
3. Close app
4. Re-open app
5. Load custom environment 
6. Variables are cleared

**Comment by AndrewStickler** [comment]
I get the same problem with the same version - this seems to be a regression, so would appreciate a fix soon please.
Thanks,
Andrew

**Comment by jarrodek** [comment]
The code responsible for managing environments and variables has been redesigned and this should not happen again. Soon I'll be releasing an update of the app.
