### ISSUE TITLE
Do you know my personal information if I use this app to send data?

### ISSUE THREAD

**Issue by korkis** [jarrodek/ChromeRestClient#1047]
Thanks for good app
but I still wonder whether you collect my data or not

**Comment by jarrodek** [comment]
Hi.
It is described in setting secretion and in onboarding screen.

The application do not store any personal information. It doesn't send any data that would make possible to identify a user personally. If Google Analytics is enabled the app generates random string and keeps it locally to identify the session but it cannot be used to get information about the user behind the application.

I'm very strict about data protection and I do not allow any personal and even non-personal data to be send outside the app. 
In settings you have link to privacy policy of the app. Please read it and let me know if you have more questions.
