### ISSUE TITLE
Multi-line headers are unsupported

### ISSUE THREAD

**Issue by smarts** [jarrodek/ChromeRestClient#1053]
From [section 4.2, Message Headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html)
> Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT

ARC doesn't currently handle this case. i've identified at least one place that is problematic. in `headers-parser-behavior.js` there is this code:
`const headers = headersString.split(/\n/gim);`

which could be replaced with:
`const headers = headersString.split(/\n(?=[^ \t]+)/gim);`

FWIW, Postman doesn't support this case either, so fixing this bug would give ARC a leg up on Postman.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. I've patched the bug already. It will be in the next release.
