### ISSUE TITLE
Clickable Link Headers

### ISSUE THREAD

**Issue by dschulten** [jarrodek/ChromeRestClient#1054]
Currently, link headers appear as follows:

![image](https://user-images.githubusercontent.com/107194/30970786-59c7deca-a466-11e7-889b-9f881a3ff023.png)

As you can see, the clickable URL is `http://localhost:8080/pimexport/products?page=2>;rel=`, which is wrong, the URL must end after page=2.

Expected: parse Link header according to [RFC-5988](https://tools.ietf.org/html/rfc5988#section-5) and make links clickable.

**Comment by jarrodek** [comment]
Hi, thank you for the issue report. I'll fix it with next release.
