### ISSUE TITLE
How to Install self signed certificate in Chrome. 

### ISSUE THREAD

**Issue by bhisevaibhav** [jarrodek/ChromeRestClient#1057]
The app can't work if the self-signed certificate is not installed in Chrome

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report. This is duplicate of #432.

Please refer to the cr-bug (https://bugs.chromium.org/p/chromium/issues/detail?id=603104) for reasons why it is not going to be fixed in the app.

I'm closing it as wont fix.
