### ISSUE TITLE
Auto format JSON when pasting

### ISSUE THREAD

**Issue by marfedd** [jarrodek/ChromeRestClient#1059]
Since this is used a lot when working with RESTful backends, it would be nice that when I pase some JSON on the "Raw payload" field it would auto format if. 
I frecuently paste JSON that I extract from the browser and is unformatted. It's very difficult to edit it that way so I have to go to a website to first format it and then paste it and then edit it.

Regards.

**Comment by jarrodek** [comment]
Hi,

Thanks you for feature request. It is great idea. I will do it.

**Comment by gbatanov** [comment]
![image](https://user-images.githubusercontent.com/2103439/31617092-1a76e484-b297-11e7-819f-65c278edb2c5.png)

**Comment by jarrodek** [comment]
@gbatanov What do you mean?

**Comment by jarrodek** [comment]
@gbatanov 
Marked by you header is a request header - not response. Response must have been `application/json` or otherwise JSON parser wouldn't be invoked.
Please provide more details in separate thread since it's not related to this issue.
