### ISSUE TITLE
ARC does not allow GET requests with a body

### ISSUE THREAD

**Issue by HayDegha0917** [jarrodek/ChromeRestClient#1060]
GET requests can be submitted with a body. Salient example: Elasticsearch does searches using GET with a body.

## Expected outcome
ARC allows me to enter a request body

## Actual outcome
Body tab is automatically hidden when method is set to GET

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
This issue has been discussed here many times. This is a duplicate.

For recap: HTTP spec does not allow message body in GET request. Web clients (XHR, Fetch) does not allow to add body for get request (Fetch even throws an error while XHR just ignores it). Therefore ARC won't allow do this.
