### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by rbarguelles** [jarrodek/ChromeRestClient#1061]
How do you do the file uploads on post?

**Comment by jarrodek** [comment]
Select HTTP method that allows to carry a payload and switch to the "body" tab.

![image](https://user-images.githubusercontent.com/3320020/31626317-1e706f94-b25e-11e7-9b58-e34bd6c020af.png)

**Comment by rbarguelles** [comment]
Thanks! Found it. Just an observation, it is not intuitive. I still needed to dig around to make it appear, compared to the previous version where the file upload was very accessible.
