### ISSUE TITLE
UTF-8 problem with new 10 version

### ISSUE THREAD

**Issue by FilimonovAP81** [jarrodek/ChromeRestClient#1062]
Hello

yesterday all worked fine. Today a have received such data in response: "Ð¢ÑÐ¼ÐµÐ½ÑÐºÐ°Ñ Ð¾Ð±Ð" 

I think in new version we have a problem with russian char coding

BR,
Anton.

**Comment by jarrodek** [comment]
Than you for the issue report.
I'm marking this as a duplicate of #1065 since i've started conversation there.`
