### ISSUE TITLE
Loading never ends after sending a request

### ISSUE THREAD

**Issue by oridanus** [jarrodek/ChromeRestClient#1068]
after pressing "Send" the loading bar doesn't finish, although the request has been sent successfully.

## Expected outcome
Have an "OK" as before

## Actual outcome
keeps loading

## Versions
App: 10.0.3
Platform: 5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by jarrodek** [comment]
Hi,

Is that happening when you are using XHR extension?

**Comment by ldpm** [comment]
I am having this experience while using the XHR extension, though I am not the original poster. Verified that the endpoint is working by using Firefox's RESTClient extension.

**Comment by oridanus** [comment]
@jarrodek, yes when using XHR extension

**Comment by jarrodek** [comment]
The update is already available for that. I'm sorry, that was my mistake in coding this module. I've fixed this already and the fix is available in 10.0.4
