### ISSUE TITLE
Copy content to clipboard does not work

### ISSUE THREAD

**Issue by galbini** [jarrodek/ChromeRestClient#1070]
Hi,

After execute a get, when i try to copy content to clipboard the content is no paste !

## Expected outcome
The content must be pasted (in a file for example).

## Actual outcome
The content can not be paste.

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. Get a ressource
2. Used the icon to copy the content to clipboard
3. used Ctrl+v to paste

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I'll fix it in a moment.
For some reason it works everything else but not in Chrome app environment...

**Comment by jarrodek** [comment]
Fixed and released.

**Comment by galbini** [comment]
Thanks that work !
Great Job.
