### ISSUE TITLE
Improvement: please increase font size to Body input (Editor view = text input)

### ISSUE THREAD

**Issue by QQeba** [jarrodek/ChromeRestClient#1072]
Please increase font size to Body input (Editor view = text input)

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. Open ARC
2. Switch to 'Body' tab
3. Change Editor view to 'Test input'
4. Type anything to the input
*Observed:* Input font is too small, uncomfortable to read - [See the screenshot](https://www.screencast.com/t/qTFBnguu)
*Expected:* (?) The font is bigger

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. Sorry about that. This is obvious bug with styling. I'm on it.
