### ISSUE TITLE
request: fill variable content from environment value

### ISSUE THREAD

**Issue by lfischer** [jarrodek/ChromeRestClient#1073]
**Overview**
Extend the magic variable functions by a way to read a defined environment value.

E.g. provide an additional "Miscellaneous" function which uses the given key parameter to read a value from the system environment and uses the content to fill the magic variable:

`environment(key)`

**Use case**
Some possible variable values are changed after a time period (e.g. a token is renewed every hour). This requires a manual update of the magic variable content.
If the value is provided by a script writing into the system environment, it would be great if the current value could be used inside ARCs magic variables.

**Comment by jarrodek** [comment]
This is definitely a good idea. Thanks for suggesting.
It is not possible to do with Chrome apps though. I do not have access to user system. That includes system environments. 
Next version that is installable on your system is able to do it. I must implement it though.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
