### ISSUE TITLE
Utf-8 output doesn't work

### ISSUE THREAD

**Issue by wapmorgan** [jarrodek/ChromeRestClient#1074]
Instead of text I get strings like these:
```json
"title": "ÐÐ°Ð¿Ð¾Ð»Ð½ÐµÐ½Ð½Ð¾ÑÑÑ Ð¿ÑÐ¾ÑÐ¸Ð»Ñ",
"title": "ÐÐ¾ÑÐµÑÐµÐ½Ð¾ Ð¼ÐµÑÐ¾Ð¿ÑÐ¸ÑÑÐ¸Ð¹",
```

## Expected outcome
Strings in UTF-8.

## Actual outcome
Now it comes in iso8859-1.

## Versions
App: 10.0.3
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

## Steps to reproduce
It's confidencial information, so I can't give it.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Can you please at least gibe me response headers? `Transfer-Encoding, `content-encoding`, `content-type` if it's there?

**Comment by wapmorgan** [comment]
Full response headers:
```
date: Mon, 16 Oct 2017 15:15:22 GMT
server: Apache/2.4.10 (Debian)
x-powered-by: PHP/5.6.31
content-length: 226
content-type: application/json; charset=UTF-8
```

**Comment by jarrodek** [comment]
Have you tried running the same request (if it's GET) in the browser? 
It looks good actually. I mean `title` property is presented right way and according to response headers the response is not encoded. The app uses build in text decoder to decode utf-8 strings so this is what server actually returned.

**Comment by jarrodek** [comment]
I see that more people have the same problem. Let me check what I can do.

**Comment by jarrodek** [comment]
The problem was with Fetch polyfill library which is a new thing I am using in the app.
It was trying to transform ArrayBuffer into string without taking encoding into the account. I'll send an update in an hour or so.

Sorry for that.

**Comment by wapmorgan** [comment]
Thanks for fast resolution!
