### ISSUE TITLE
Cant load body for saved object. Only headers are loaded

### ISSUE THREAD

**Issue by kLkA** [jarrodek/ChromeRestClient#1077]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.3
Platform: 5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. After update i've tried to load saved request and body didnt appear

**Comment by jarrodek** [comment]
Hi,

I can't reproduce the problem.
Is that body edited in "raw" editor? Sometimes there's an issue with code mirror where you have to click on the editor for the content to show up. Is that the case?

**Comment by kLkA** [comment]
Hi, Sorry! It turns that data is in textarea but didnt show up until i clicked on it first time. Now its ok :)

**Comment by jarrodek** [comment]
That's actually a problem with the app. It should handle this issue properly. 
I just fixed it. Release it's on its way.
