### ISSUE TITLE
A few projects got lost after upgraded to 10.0.3

### ISSUE THREAD

**Issue by jiajieduan** [jarrodek/ChromeRestClient#1078]
I noticed that a few of my projects under projects tab were lost after ARC upgraded to 10.0.3.
However, I can still find those single requests under saved tab. And it is pain to go through all the saved single request to find what i want..
Is there a maximum number of projects that can be displayed under Projects tab? (and looks like it is 25? because i have only 25 projects left and lost all the rest projects.. I'm just randomly guessing why would my projects get lost..)..

**Comment by jarrodek** [comment]
There was no changes in the data store. Only the UI.
Possible reason is that the list of projects do not request for more project when you scroll to the end of it. I'll check this later today.

**Comment by jarrodek** [comment]
I got it. Pagination was disabled in projects navigation. It is now enabled.
Please, give me an hour to publish the release with bug fix.

**Comment by jiajieduan** [comment]
Awesome. Thanks!

**Comment by jarrodek** [comment]
I've published the app seconds ago. It takes up to 60 minutes to update.
