### ISSUE TITLE
Copy&Paste overwrites all the body of a request

### ISSUE THREAD

**Issue by GianlucaVagnoni** [jarrodek/ChromeRestClient#1082]
If I copy a text and paste it in hte body of a request, the system overwrite the entire body.

## Expected outcome
The pasted text should be copied in the body avoiding the overwrite the whole body, just make it work like all the other software around the world :)

## Actual outcome
When I past the copied text it replaces the entire body of the request

## Versions
App: 10.0.5
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. Write a generic request in the body, ex:
{
    "input1": "value1",
    "input2": "value2",
    "input3": "value3",
    "input4": "value4"
}
![image](https://user-images.githubusercontent.com/32868201/31659535-d09eaad8-b334-11e7-83a3-5b90145ab9d6.png)

2. Copy a text (Ctrl+C) from another open program (e.g. a text document)
3. Paste it in the body of the request, in a random line, as you wish.
4. The entire body is replaced
![image](https://user-images.githubusercontent.com/32868201/31659585-f56d40fe-b334-11e7-8f37-65e55180f278.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
It was a fix for #1059 but I haven't considered selection at a time.
I'll fix it today.
