### ISSUE TITLE
Paste is not work properly in "Body" field

### ISSUE THREAD

**Issue by maxifly** [jarrodek/ChromeRestClient#1083]
When i want change body and do copy/paste in body field, after paste in field plase only text thet i am copy. Another text cleared.

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.5
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by LucyParry** [comment]
I'm having this issue too so just wanted to add some more information. We use the tool all the time at work (thank you) so it caught us off guard!
<hr>
Unexpected 'Paste' behaviour when editing the request body of a 'POST', 'PUT' etc. 
Using the Editor view: Text input with Body content type: application/json

## Expected outcome
When editing the body content by pasting text, I would expect the text to be inserted wherever the cursor is placed in the text editor box.

## Actual outcome
When editing the body content by pasting text (for example changing a JSON value), the entire body content is replaced by the pasted value.

# Versions
App: Version 10.0.5
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
Running on: Windows 10 Pro 64-bit Version 1703

# Steps to reproduce
1. Start a new request or open a saved one
2. Set method to "PUT" or "POST"
3. Set body content type to application/json
4. Set editor view to 'text input'
5. Add some data to the body of the request
6. Edit this data by pasting in a value somewhere in the middle of the body text 
![arc1](https://user-images.githubusercontent.com/12956949/31724921-f2544002-b41a-11e7-9701-bc4d1e93b8e9.png)

7. The whole of the body text is replaced by the pasted value
![arc2](https://user-images.githubusercontent.com/12956949/31724922-f26b33de-b41a-11e7-8ce6-3be831be0a53.png)
