### ISSUE TITLE
multipart/form-data requests don't work with other form parameters

### ISSUE THREAD

**Issue by liubin9** [jarrodek/ChromeRestClient#1086]
How to post other form parameters in content type of multipart/form-data ? 
such as  payload in before.

Version: 10.0.5

**Comment by mrvincenzo** [comment]
@liubin9 Did you find a workaround? I am struggling with the same issue.

**Comment by jarrodek** [comment]
@mrvincenzo What do you mean a workaround? What you are missing?

**Comment by mrvincenzo** [comment]
@jarrodek I am missing the option to copy paste a body request as a whole. As for today I need to add all parts separately which is very annoying in my case. Before the change, I was able to copy & past a complete form-data body into the reset client.

**Comment by jarrodek** [comment]
@mrvincenzo I wasn't aware of such use case. Can you crate a new issue for that? It's different from this issue.
Although I'll try to update it asap.

**Comment by mrvincenzo** [comment]
@jarrodek I've created a new issue https://github.com/jarrodek/ChromeRestClient/issues/1100
