### ISSUE TITLE
Can't turn on "Use XHR extension"

### ISSUE THREAD

**Issue by shell8104** [jarrodek/ChromeRestClient#1087]
When I tried to turn on the XHR mode, I can't do it. It was confusing for me, because I saw it on the button, that I clicked it.

## Expected outcome
When I click on the switch button, it should turn on/off.
When I click on the label of the switch it should turn on/off.

## Actual outcome
When I click on the switch button, it doesn't turn on/off.
When I click on the label of the switch it turns on/off.

## Versions
App: 10.0.5
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1.  Click on the "Use XHR extension" switch
2.  It doesn't turn on.
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. It is fixed now and will work later today.
