### ISSUE TITLE
After upgrade, having issues sending requests to secure site

### ISSUE THREAD

**Issue by jeffwwelch** [jarrodek/ChromeRestClient#1088]
Hello,

After the app upgrade, I can no longer send requests to our internal SharePoint environment.  Before the upgrade, if I attempted to access I would get challenged for username/password.  Now that no longer happens and I get 403 errors.

## Expected outcome
I expect a popup for username/password/domain

## Actual outcome
no popup, just returns 403 error.

## Versions
App: 10.0.5
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. enter a url to a secured resource
2. click send
3. get 403 Access Denied Error

**Comment by jarrodek** [comment]
Hi,

Can you please provide more information?
What is the authentication type?
Is the endpoint exposed so I can test it?

**Comment by jeffwwelch** [comment]
Hi, please close this issue.  Turns out it was a configuration on my side.

**Comment by jarrodek** [comment]
Thanks for letting me know!
