### ISSUE TITLE
Feature Request: Export data per project

### ISSUE THREAD

**Issue by ebikargar** [jarrodek/ChromeRestClient#1092]
Hi folks, 
I was wondering to ask if you could consider the feature for exporting data for every specific project.
ATM you are able to export all the data , you are not able to specify data from an specific project.

**Comment by jarrodek** [comment]
Hi,

Thank you for the feature request.
This is already in the app:

![image](https://user-images.githubusercontent.com/3320020/31786332-fc836998-b4bc-11e7-9132-c3ce2aa6779f.png)

**Comment by ebikargar** [comment]
Thanks for mentioning this feature jarrodek, 
I was wondering to ask you if you got any chance to check what's happening when you export and import list of invocations from a project ?? In my case , when I'm exporting list of calls from a project and try to import them in the other ChromeRestClient, project will be create with empty list of calls,instead list of imported calls will be appear not in the imported project but in Saved calls. what's wrong with it?

**Comment by jarrodek** [comment]
It looks like a bug within import module. I'll fix it this weekend.
Really sorry for that.

**Comment by jarrodek** [comment]
Fixed per https://github.com/jarrodek/ChromeRestClient/commit/e638c383b3394b5f83e4e4828233ec2ed4e04b82
