### ISSUE TITLE
Messy code with Chinese charater

### ISSUE THREAD

**Issue by KelvinYellow** [jarrodek/ChromeRestClient#1093]
The ARC plugin automatic updated itself days ago. After that,the response turns out having messy code in Chinese charater, when the other tools(like SoapUI) returns correct.

## Expected outcome
{
   "statusCode": 200,
   "total": 1,
   "page": 1,
   "state": 1,
   "records": 1,
   "rows": [   {
      "DEPT_ID": "007541934",
      "BREVITY_CODE": "E0200053",
      "ITEM_TYPE": "xzxk",
      "REMARK": "表单发布",
      "DEPT_NAME": "深圳市宝安区经济促进局",
      "STATUS": "1",
      "SUIT_ONLINE": "1",
      "FOLDER_NAME": "外商投资企业设立及企业变更和终止审批",
      "FORM_DATA_SOURCE_ID": "19e1f7e2292b40aea4ac7e527365596c",
      "VERSION": "9",
      "CATALOG": "01888,902,903,root_qy_ztfl_qt,root_qy_ztfl_slbg",
      "LICENSINGCODE": "1",
      "WORKFLOW_ID": "1604700d-679f-11e7-8259-286ed488c806",
      "CODE": "00002301359070699316440306",
      "NAME": "外商投资企业延长经营期限",
      "CHANGE_TYPE": "2",
      "DEPT_ORG_NAME": "深圳市宝安区经济促进局",
      "FORM_DATA_ID": "19e1f7e2292b40aea4ac7e527365596c",
      "DEPT_ID_ORG": "007541934",
      "ITEM_LEVEL": "1",
      "REGION_ID": "440306",
      "MANAGEMODE": "B",
      "FOLDER_ID": "be7085b49fcb44bd9a7a0ef065761c11",
      "FORM_DATASOURCE_ID": "QZQD_XZXK_20170807115403448400",
      "APPLY_SERVICE": "http://wzfw.szjmxxw.gov.cn",
      "REGION_NAME": "宝安区",
      "IS_RELATION_FORM": "1",
      "PUBLISH_TIME": "2017-09-30 16:35:58",
      "BUSINESS_STATUS": "PUBLISHED",
      "BUSI_ID": "4d320126f3ac4319ae51f2068ec92f4e"
   }]
}

## Actual outcome
{
"statusCode": 200,
"total": 1,
"page": 1,
"state": 1,
"records": 1,
"rows": [
  {
"DEPT_ID": "007541934",
"BREVITY_CODE": "E0200053",
"ITEM_TYPE": "xzxk",
"REMARK": "è¡¨ååå¸",
"DEPT_NAME": "æ·±å³å¸å®å®åºç»æµä¿è¿å±",
"STATUS": "1",
"SUIT_ONLINE": "1",
"FOLDER_NAME": "å¤åæèµä¼ä¸è®¾ç«åä¼ä¸åæ´åç»æ­¢å®¡æ¹",
"FORM_DATA_SOURCE_ID": "19e1f7e2292b40aea4ac7e527365596c",
"VERSION": "9",
"CATALOG": "01888,902,903,root_qy_ztfl_qt,root_qy_ztfl_slbg",
"LICENSINGCODE": "1",
"WORKFLOW_ID": "1604700d-679f-11e7-8259-286ed488c806",
"CODE": "00002301359070699316440306",
"NAME": "å¤åæèµä¼ä¸å»¶é¿ç»è¥æé",
"CHANGE_TYPE": "2",
"DEPT_ORG_NAME": "æ·±å³å¸å®å®åºç»æµä¿è¿å±",
"FORM_DATA_ID": "19e1f7e2292b40aea4ac7e527365596c",
"DEPT_ID_ORG": "007541934",
"ITEM_LEVEL": "1",
"REGION_ID": "440306",
"MANAGEMODE": "B",
"FOLDER_ID": "be7085b49fcb44bd9a7a0ef065761c11",
"FORM_DATASOURCE_ID": "QZQD_XZXK_20170807115403448400",
"APPLY_SERVICE": "http://wzfw.szjmxxw.gov.cn",
"REGION_NAME": "å®å®åº",
"IS_RELATION_FORM": "1",
"PUBLISH_TIME": "2017-09-30 16:35:58",
"BUSINESS_STATUS": "PUBLISHED",
"BUSI_ID": "4d320126f3ac4319ae51f2068ec92f4e"
}
],
}

## Versions
App: 10.0.3
Platform: 5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

It is fixed already in version 10.0.4 (or 5). Please, update the app and this will work again.

**Comment by KelvinYellow** [comment]
Thank you!
It is working fine now!
