### ISSUE TITLE
Typo in the Socket screen: "Prevoius connections"

### ISSUE THREAD

**Issue by mhelvens** [jarrodek/ChromeRestClient#1094]
![screen shot 2017-10-22 at 10 08 32](https://user-images.githubusercontent.com/4012816/31860392-0d357d66-b711-11e7-841e-80537f0e629d.png)

**Comment by LucyParry** [comment]
FYI project maintainers: I submitted a couple of PRs for this and another typo - Hope that's OK!
https://github.com/advanced-rest-client/websocket-history/pull/1
https://github.com/advanced-rest-client/headers-form-editor/pull/1

**Comment by jarrodek** [comment]
@LucyParry Thank you for the PRs. I've merged changes and I'll update the app today / tomorrow.
