### ISSUE TITLE
Cannot use a variable for Host?

### ISSUE THREAD

**Issue by mhelvens** [jarrodek/ChromeRestClient#1095]
<img width="442" alt="screen shot 2017-10-22 at 11 27 40" src="https://user-images.githubusercontent.com/4012816/31861008-43b64df6-b71c-11e7-9793-7c29dad0e5b8.png">
<img width="442" alt="screen shot 2017-10-22 at 11 27 54" src="https://user-images.githubusercontent.com/4012816/31861009-4541f2ce-b71c-11e7-8498-bf0f0f8bc422.png">

**Comment by jarrodek** [comment]
This is my setup:

![image](https://user-images.githubusercontent.com/3320020/31918545-0b669a86-b812-11e7-851d-19072c2593d6.png)

Apparently it's working. Are you able to debug this behavior?

**Comment by mhelvens** [comment]
Sorry for the long delay in responding. My team switched to a different tool, but it was a bit rude of me to leave you hanging. I was not able to debug the behaviour then. But it was consistent.

If you cannot reproduce it, feel free to close this issue.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
