### ISSUE TITLE
Use XHR disappeared after recent update

### ISSUE THREAD

**Issue by dbavery** [jarrodek/ChromeRestClient#1097]
I use the "Use XHR" option quiet extensivly since our product ships with a self-signed certificate by default. Upon upgrade of my extension to 10.0.07-STABLE that option has disappered.

## Expected outcome
I expected that since I have the ARC Cookie Exchange plugin installed that I would still have the Use XHR option

## Actual outcome
That toggle is no longer shown.

## Versions
App: 10.0.7
Platform: 5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. Install the client and the ARC Cookie Exchange plugin and go to use the Use XHR option -- it is missing

I uninstalled and reinstalled both plugins with no luck.

**Comment by jarrodek** [comment]
This option is now under context menu next to the URL editor:

![image](https://user-images.githubusercontent.com/3320020/31918308-dd33b442-b810-11e7-8771-48d7eaaaaa8a.png)

**Comment by dbavery** [comment]
@jarrodek Thank you! I was hoping it was something that simple. I must have missed that in the release notes for the new version.
