### ISSUE TITLE
Paste digits into json editor overwrites its content

### ISSUE THREAD

**Issue by i-ka** [jarrodek/ChromeRestClient#1103]
When editing json request body, if try to paste digits into text input, it overwrites text input's content.
If string contains any letters or special symbol it works fine.

## Expected outcome
Paste digits into text input at cursor position, save existing text

## Actual outcome
Pasting overwrites all content of text input

## Versions
App: 10.0.8
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
Copy digits (from any place)
![image](https://user-images.githubusercontent.com/13613488/32367488-1bfc2376-c0a4-11e7-9b6a-eba149bc0c2a.png)
2. And paste it at any position
![image](https://user-images.githubusercontent.com/13613488/32367653-abcbadb4-c0a4-11e7-8776-9b140ef65f72.png)

**Comment by jarrodek** [comment]
Thank you for the issue report.
I have fixed this issue a moment ago. Soon I will release an update.
