### ISSUE TITLE
Can't draw window on response result

### ISSUE THREAD

**Issue by qiaolevip** [jarrodek/ChromeRestClient#1104]
This is response result:
mtopjsonp1({"api":"wdetail","v":"6.0",

## Expected outcome
What should happen?
It show response result or can draw window show more content.

## Actual outcome
What happened?
Can't see result.

![screenshot from 2017-11-13 17-50-26](https://user-images.githubusercontent.com/996755/32719565-d3dd8936-c89b-11e7-8eac-f274a36d5b08.png)

## Versions
App: 10.0.10
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

## Steps to reproduce
1. Text url : some api  : response jsonp callback
2.  See result area
3. Can't see it

**Comment by jarrodek** [comment]
Hi,
Thank you for the issuer report. It will be fixed with next hotfix release.

It would be faster to install new ARC from here: https://install.advancedrestclient.com/
Bug fixes are delivered in this project with highest priority.

**Comment by qiaolevip** [comment]
Thx, I'll install the latest version of ARC.
