### ISSUE TITLE
"+" symbol getting omitted on post request

### ISSUE THREAD

**Issue by rashidmv** [jarrodek/ChromeRestClient#1106]
Your description here

## Expected outcome
What should happen?
what ever given post parameter should go as such
## Actual outcome
What happened?
"+" getting fileteed out
## Versions
App: 10.0.10
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

## Steps to reproduce
1. in urlencoded post parameter give "+" symbol
2. 
3.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
Can you be more specific?
I can understand that you are sending URL encoded form data (?)

And what's actual problem? `+` sign being replaces in the message body or not being replaced? I'm not sure.

I am closing it as invalid. If you can provide steps to reproduce feel free to re-open.
