### ISSUE TITLE
Projects list does not refresh after creating a new project

### ISSUE THREAD

**Issue by jackblackjack** [jarrodek/ChromeRestClient#1107]
If I works into project A and wish to create a new request template into project B I do steps ## Steps to reproduce:

## Expected outcome
What should happen?
Project B is available for select into section Projects.

## Actual outcome
What happened?
Project B is not available for select into section Projects.

## Versions
App: 10.0.10
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

## Steps to reproduce
1. Once click to HTTP Request section.
2. Build a required http request.
3. Click to send
4. Call a SAVE dialog and set a title project B, and title for request.
5. Click to Save as NEW
6. Click to section Projects

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. I've fixed it in the source code. Soon it will be released.
