### ISSUE TITLE
Click to insert into Url field  is not working

### ISSUE THREAD

**Issue by pramesh0545** [jarrodek/ChromeRestClient#1108]
Your description here
From the response view i can not able to update the request URL by click any href link in the response.
## Expected outcome
What should happen?
If i click on any href url it should update the request url.
## Actual outcome
What happened?
don't know previously it is working fine. might be updated version had issue.
## Versions
App: 10.0.8
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. make any rest call it should return the response which contains some href links.
2. click on any href link of response view
3. verify whether request url is updating or not?

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. It will be fixed with next release.
