### ISSUE TITLE
Always show "Unable to save current request. unknown" while saving "multipart/form-data"

### ISSUE THREAD

**Issue by skyerh** [jarrodek/ChromeRestClient#1109]
The ARC always  show  "Unable to save current request. unknown" while saving "multipart/form-data" with TEXT  PART exist.
![2017-11-24 10 06 09](https://user-images.githubusercontent.com/2095652/33192913-c77e19d2-d0ff-11e7-9367-bb33bd4b719f.png)
![2017-11-24 10 06 38](https://user-images.githubusercontent.com/2095652/33192915-c7a82808-d0ff-11e7-87fa-b29689153862.png)
![2017-11-24 10 06 44](https://user-images.githubusercontent.com/2095652/33192916-c7ce9a1a-d0ff-11e7-81cc-156c47686e61.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I can reproduce it. I will try to fix it today.

**Comment by jarrodek** [comment]
The code has been merged but it will take some time to release the fixed version. Sorry for the delay.
