### ISSUE TITLE
always pop up: Failed to construct 'URL': invalid URL

### ISSUE THREAD

**Issue by bailp** [jarrodek/ChromeRestClient#1110]
Your description here

ACR worked well before. But it does not work anymore today. Sending any request will report a popup dialog at bottom showing  “ Failed to construct 'URL': invalid URL ”

Also when collapse and open the detailed url editor, different url displayed. 

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.11
Platform: 5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

## Steps to reproduce
![image](https://user-images.githubusercontent.com/10415109/33205844-535bd474-d143-11e7-8c2c-4fc3a62ec6f3.png)
![image](https://user-images.githubusercontent.com/10415109/33205855-5b447aba-d143-11e7-82e3-9325def85ad3.png)
![image](https://user-images.githubusercontent.com/10415109/33205870-66eba9ce-d143-11e7-9f99-813363aaee51.png)

**Comment by jarrodek** [comment]
I am unable to reproduce this behavior. 
Chrome browser that is that old (10 versions old, over a year from release date) might not be supported because of missing APIs.
Can't you update Chrome?

**Comment by bailp** [comment]
After updating Chrome to the latest version(63.0.3239.84),  any installed extension gone away >_<...
and   I can't find it anymore from chrome webstore . Is ARC chrome extension not available for the latest Chrome version ?
now I installed the standalone app, but it don't work so conveniently as old extension

**Comment by bailp** [comment]
Great, it works. Thanks @jarrodek
