### ISSUE TITLE
Why can't I find the Raw payload section for a POST request while sending notification to a single device using Registration token?

### ISSUE THREAD

**Issue by triparna53** [jarrodek/ChromeRestClient#1111]
Your description here

## Expected outcome
Successfully sent notification

## Actual outcome
401 The request was missing an Authentication Key (FCM Token) since I can't add payload.

## Versions
App: 10.0.11
Platform: 5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by jarrodek** [comment]
It's all there:

<img width="1110" alt="screen shot 2017-12-06 at 10 49 08" src="https://user-images.githubusercontent.com/3320020/33679434-9a1a2788-da73-11e7-8c92-71abf3d0bbba.png">
