### ISSUE TITLE
the response header no visible 

### ISSUE THREAD

**Issue by joasimar** [jarrodek/ChromeRestClient#1113]
Your description here

## Expected outcome
What should happen?
i cannot see response 
## Actual outcome
What happened?
i cannot see response 
## Versions
App: 10.0.12
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

## Steps to reproduce
1. method post any url 
2. 
3.

**Comment by jarrodek** [comment]
Can't reproduce. Please reopen when providing more details.

**Comment by jarrodek** [comment]
Also, pleas, install new native ARC as it has a lot better user experience and receives updates first https://install.advancedrestclient.com/
