### ISSUE TITLE
Clear stored data doesn't clear the current URL in HTTP request

### ISSUE THREAD

**Issue by Weishaupt** [jarrodek/ChromeRestClient#1115]
When a Rest Call is executed and all data is cleared afterwards, the URL of the last call is still in the HTTP request field.

## Expected outcome
Entry field is cleared.

## Actual outcome
Entry field contains last called URI.

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

## Steps to reproduce
1. Execute a HTTP request
2. Select Preferences / Clear stored data
3. Remove

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
