### ISSUE TITLE
How can I delete a service from "Projects"?

### ISSUE THREAD

**Issue by czar82** [jarrodek/ChromeRestClient#1118]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
You can do this in project detail panel. Click on the "right arrow" next to the project name to open the panel.

Also, I suggest to move to desktop application: https://install.advancedrestclient.com/
