### ISSUE TITLE
bug when save with type multipart/form-data

### ISSUE THREAD

**Issue by drincast** [jarrodek/ChromeRestClient#1119]
When a request is create withthe type multipart-form-data, it does not allow to save the query

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## Steps to reproduce
1. create de request type multipart/form-data
2. click to save the query
3.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.

**Comment by drincast** [comment]
ok, thank for the information

**Comment by jarrodek** [comment]
I've double checked the desktop client. I hound an issue with the FormData. I've fixed it today. I'll update the app soon.
