### ISSUE TITLE
Left Menu disappeared

### ISSUE THREAD

**Issue by Diwann** [jarrodek/ChromeRestClient#1120]
I lost the left menu

![2018-01-29 16 32 14](https://user-images.githubusercontent.com/784023/35518480-fda66672-0511-11e8-933c-53e9058cb2c1.png)

## Expected outcome
What should happen?
I should be able to open the left menu

## Actual outcome
What happened?
To make more space for my query, I once discarded the left menu to hide it from the main window

## Versions
App: 10.0.12
Platform: 5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

## Steps to reproduce
1. move the elevator of the menu to the left 
2. You can't select it anymore to move it back to the right

**Comment by jarrodek** [comment]
HI,

Thank you for issue report.
It looks like menu is just hidden. Can you please click on the "menu" icon on top left?

**Comment by Diwann** [comment]
Hi, thanks for the answer.
Unfortunately, the menu icon doesn't help much 😅 
see: https://youtu.be/AI-UH0n2Jsw

**Comment by jarrodek** [comment]
This issue will be resolved by setting min width of the left panel. However, Chrome package is deprecated and all chrome apps are scheduled to be removed from chrome.
Please install desktop client that is actively maintained: https://install.advancedrestclient.com/

**Comment by Diwann** [comment]
ok, thanks

**Comment by jarrodek** [comment]
It might not be clear. Google scheduled to remove support for Chrome apps.

**Comment by Diwann** [comment]
No, it's clear.
I 've installed the desktop client.
Thanks for that

Le mar. 6 févr. 2018 à 23:07, Paweł Psztyć <notifications@github.com> a
écrit :
