### ISSUE TITLE
Not possible to restore left panel width when dragged to 0

### ISSUE THREAD

**Issue by Jyhess** [jarrodek/ChromeRestClient#1121]
It's not possible to recover left panel when it it minimized.

## Expected outcome
When I resize left panel to have 0 pixels width, I can resize it to have it visible.

## Actual outcome
When I resize left panel to have 0 pixels width, I cannot drag it to expand its width, and I don't find any button or option to restore its original size.

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## Steps to reproduce
1. Drag left panel to have 0 width
2. Try to restore its original width

**Comment by jarrodek** [comment]
This issue will be resolved by setting min width of the left panel. However, Chrome package is deprecated and all chrome apps are scheduled to be removed from chrome. 
Please install desktop client that is actively maintained: https://install.advancedrestclient.com/

**Comment by dhoelzl** [comment]
Is there any way to restore the panel? E.g. clearing some stored data etc.?

**Comment by jarrodek** [comment]
If I am not mistaken executing this code in apps console window should fix the problem:

```
chrome.storage.local.set({drawerWidth: 360});
```

To be able to execute any code you need to go to `chrome://extensions`, enable Developer mode, click on the background page or any index.html page to open the console.

**Comment by jarrodek** [comment]
This code sets local variable in chrome storage for the app called `drawerWidth` with value `360` which is a number of pixels to render the drawer.

**Comment by dhoelzl** [comment]
Thank you, that fixed the problem! 👍
