### ISSUE TITLE
Failed to construct 'URL':Invalid URL

### ISSUE THREAD

**Issue by lanlan1128** [jarrodek/ChromeRestClient#1123]
whatever the request I make ,It shows "Failed to construct 'URL':Invalid URL"。

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Please, use newer version of ARC from https://install.advancedrestclient.com/
It should have any issue related to this error message (except of it being actually invalid URL) fixed.
