### ISSUE TITLE
Javascript error after app closed

### ISSUE THREAD

**Issue by chakaSA** [jarrodek/ChromeRestClient#1124]
Your description here
![image](https://user-images.githubusercontent.com/6409896/36135597-e37a4708-1094-11e8-8fbb-e948570a5318.png)

Saw an newer version was available and installed it yesterday on my laptop.
I left the app open and only closed it this morning.

Did not take note of how long after closing the app, but since then getting the above Javascript error a few times.

## Expected outcome
What should happen?
No error message

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: Win 19
Chrome 64.0.3282.140 (Official Build) (64-bit)

## Steps to reproduce
1. Installed
2. App Left open & laptop hibernate
3. Close app
Dont know if these steps are worth anything?

**Comment by jarrodek** [comment]
Hi,
this report is for ARC desktop app and should be reported here: https://github.com/advanced-rest-client/arc-electron/
However, it is already fixed. I have released an update a minute ago. See https://github.com/advanced-rest-client/arc-electron/issues/50
