### ISSUE TITLE
Lost the history pane

### ISSUE THREAD

**Issue by adrianboston** [jarrodek/ChromeRestClient#1125]
Your description here

History panel cannot be expanded from zero width if slide shut. Perhaps needs to restore panel with new window or restore default size.

## Expected outcome
What should happen?

Left panel should expand with mouse

## Actual outcome
What happened?

Nothing. No expansion

## Versions
App: 10.0.12
Platform: 5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## Steps to reproduce
1. Close history panel using mouse or perhaps a ctrl command. It happened unexpectedly
2. Try to grab edge of left window using mouse
3. Nope!!

**Comment by adrianboston** [comment]
Slider is visible when clicking the triple-dash icon on top left of main window but panel cannot be opened

**Comment by jarrodek** [comment]
Please, see https://github.com/jarrodek/ChromeRestClient/issues/1121 for more info.
Closing as duplicate.
