### ISSUE TITLE
Environment variables are not reflected when run

### ISSUE THREAD

**Issue by MMitchellPR** [jarrodek/ChromeRestClient#1126]
**Changes in environment variables are not reflected until restart.**

## Expected outcome
Should use new values from environment, not old ones. 

## Actual outcome
Used old environment values. 

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

## Steps to reproduce
1. Setup 
URI=${host}:${port}
host=localhost
port=80
Request to ${URI}
2. Runs as expected. 
3. Then change host or port. Run again, but get original values, not the new ones. 
4. Restart ARC
5. Runs with new values.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
