### ISSUE TITLE
Won't stop saving and transferring cookies

### ISSUE THREAD

**Issue by robsrs** [jarrodek/ChromeRestClient#1127]
For a minute I thought it might be nice to be able to mimic browser cookies and disable that annoying popup that covers the results, so I did it.  Ever since then I haven't been able to disable the feature.  I've tried disabling and uninstalling the browser extension, I've turn off the feature in settings->stored data->collect cookies, and it still collects and sends cookies that I don't want it to and I have to clear history every time.

## Expected outcome
It should turn off.

## Actual outcome
It doesn't turn off.

## Versions
App: 10.0.12
Platform: 5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/
There's a lot more options to control cookies.

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
