### ISSUE TITLE
Unable to set 'Host' header

### ISSUE THREAD

**Issue by wyn930504** [jarrodek/ChromeRestClient#1128]
Unable to set 'Host' header

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

**Comment by jarrodek** [comment]
Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
