### ISSUE TITLE
Drawer is unusable after dragging too far to the side

### ISSUE THREAD

**Issue by rossyoung56** [jarrodek/ChromeRestClient#1130]
I've been having an issue with the REST client after I accidentally resized the drawer so far that it's now nearly invisible. 

I now can't see the drawer even when it's open, and I can't grab it to drag it and make it visible again. I can still click the hamburger icon to open the drawer, and I can click something on the drawer to close it, but I can't see or do anything else. 

I haven't found a way to reset the drawer or even the whole layout, either. Each new window that I create has the same problem, as well.

## Expected outcome
Drawer is always draggable, has a minimum size, or can at least be reset.

## Actual outcome
If drawer is resized too small it is unrecoverable. It cannot be viewed, resized, or reset.

# Version
Advanced REST Client 10.0.12
Google Chrome 63.0.3239.132 (Official Build) (32-bit)

# Image
The drawer is the white line on the left side. I can't grab onto it to drag it whether in windowed or fullscreen mode.
![arc_drawer](https://user-images.githubusercontent.com/3180837/37048723-a5fdd18c-2166-11e8-970c-2d42c7a0dafd.PNG)

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue.
