### ISSUE TITLE
What file are saved projects saved to?

### ISSUE THREAD

**Issue by PaulSager** [jarrodek/ChromeRestClient#1131]
I wiped my hard drive, and now I need to restore all of my old ARC projects from my backup. I am thinking there should be a file, or set of files, somewhere under my old Users\<me>\folder, but I don't know where.

When I click Import:Open From File: it takes me to C:\Users\Paul\AppData\Local\Programs\advanced-rest-client, which doesn't exist on my backup. So I do not know what version of ARC I previously was using. I believe that it was the standalone app, but am not positive.

So if someone can tell me, when I save a new project/request, where that gets saved, then I am hoping to find that same location in my backup.

**Comment by jarrodek** [comment]
You are reporting the issue for Chrome application (deprecated app).
If the data were related to Chrome app then it won't be possible to restore it. It was saved in Chrome internal datastore and if you haven't exported the data to a file or to Google Drive then it's lost.

ARC desktop client keeps some data in the location you described. However it's only user settings and lates request data. Rest of the data are still kept in application internal datastore. So if you haven't exported the data to a file / Google Drive there's nothing I can do.
