### ISSUE TITLE
Misspelled Word on Display Screen

### ISSUE THREAD

**Issue by speedking456** [jarrodek/ChromeRestClient#1157]
![image](https://user-images.githubusercontent.com/20252229/50743033-8d66cf00-11c7-11e9-8044-ef93066156f5.png)
Display has only 1 P

## Expected outcome
It says display

## Actual outcome
It says dispplay

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

## Steps to reproduce
1. Send a post request with no return data.

**Comment by jarrodek** [comment]
Thank you for issue report.
It has been patched in corresponding components and will be shipped with next release.
