### ISSUE TITLE
https://install.advancedrestclient.com/ is using an expired certificate

### ISSUE THREAD

**Issue by bstrathearn** [jarrodek/ChromeRestClient#1161]
Your description here

## Expected outcome
Visit https://install.advancedrestclient.com/ to install ARC

## Actual outcome
Chrome tells me the connection is not secure because: 

> This server could not prove that it is install.advancedrestclient.com; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Friday, March 29, 2019. Does that look right? If not, you should correct your system's clock and then refresh this page.

## Versions
App: 10.0.12
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

## Steps to reproduce
1. Click the `Install new ARC with new features` link

**Comment by jarrodek** [comment]
Hi,
Thank you for the report. It is fixed now.
Sorry for that.
