### ISSUE TITLE
sandwich navigation button is not opening the left panel. Only displays half merged vertical bar

### ISSUE THREAD

**Issue by AnushaSunkada** [jarrodek/ChromeRestClient#1163]
sandwich navigation button is not opening the left panel. Only displays half merged vertical bar.

## Expected outcome
Click on sandwich navigation button should open the left panel displaying history and saved requests.

## Actual outcome
Click on sandwich navigation button is not opening the left panel.

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

![Capture](https://user-images.githubusercontent.com/22977936/55875325-782c8280-5bb2-11e9-992a-c0db61cece00.PNG)

**Comment by jarrodek** [comment]
Hi,
This is known issue which right now I cannot fix.. 
Suggested walkaround is to use ARC desktop client: https://github.com/advanced-rest-client/arc-electron/releases (Note, you have to move your data manually by using import/export).

Or see my comment here to fix it yourself https://github.com/jarrodek/ChromeRestClient/issues/1121#issuecomment-481513441

**Comment by AnushaSunkada** [comment]
thank you.
