### ISSUE TITLE
Post Redirection problem

### ISSUE THREAD

**Issue by ozgeu** [jarrodek/ChromeRestClient#1164]
I post data to a jsp and redirect it another jsp.
It does not work
![image](https://user-images.githubusercontent.com/19166943/55972435-2526fe00-5c8c-11e9-8e95-e1c8b688c22e.png)

but when I try same post in postman.
It works.

![image](https://user-images.githubusercontent.com/19166943/55972510-4ee02500-5c8c-11e9-8d6b-6672645d5771.png)

**Comment by jarrodek** [comment]
Hi,
I cannot currently update this version of the application. Suggested walkaround is to use ARC desktop client: https://github.com/advanced-rest-client/arc-electron/releases
Note, you need to move your data manually using import / export feature.
