### ISSUE TITLE
Same API in different tomcat server is not working

### ISSUE THREAD

**Issue by mamathak412** [jarrodek/ChromeRestClient#1169]
Tested API in tomcat server1 working as expected. Same API tested in tomcat sever2. 
Getting Error.
## Expected outcome
API should work both in tomcat server1 and tomcat server2

## Actual outcome
In tomcat server2, getting error - The requested URL can't be reached

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

## Steps to reproduce
1. Same api run in two different tomcat servers.
2. Run in ARC in both servers

**Comment by mamathak412** [comment]
![server1](https://user-images.githubusercontent.com/26055307/59899484-84368b00-9412-11e9-8dea-192c12d1859b.png)
![server2](https://user-images.githubusercontent.com/26055307/59899485-84368b00-9412-11e9-92ef-26e67ef25f01.png)

**Comment by jarrodek** [comment]
The HTTP message sent from the app is guaranteed to be the same. Variables may change like cookies or other headers but the generated message is always the same. If the app works for one API and it does not for the other one then the API is down, url is different or some other issue. I see that the other request returns 0 status. This status means that conneciton to the resver cannot be setablished. This then means that the API is down.
In any case there's noting to do for me.
