### ISSUE TITLE
json params in the body of the POST request doesnot remain saved.

### ISSUE THREAD

**Issue by tsjahangiri** [jarrodek/ChromeRestClient#1173]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. The chrome application is no longer supported as Chrome decided to drop support for Chrome applications in near future. This is not an issue in ARC desktop client. 
Please, [follow this instructions](https://docs.advancedrestclient.com/moving-from-chrome-application-to-desktop-client) to upgrade to the desktop client.
