### ISSUE TITLE
About Sending a request button

### ISSUE THREAD

**Issue by mgmandaliya** [jarrodek/ChromeRestClient#1176]
It's very difficult to click the send button when I am the bottom of the page when huge data you should give a shortcut for sending a request or submit button like the postman. so give shortcut dor send button. thanks :)

**Comment by jarrodek** [comment]
Hi,
This app (because of Chrome removing support for Chrome apps) is no longer maintained. Please, use the desktop client that has a lot of improvements. You can find it here: https://install.advancedrestclient.com/install

**Comment by mgmandaliya** [comment]
thanks :)
