### ISSUE TITLE
Improvement : Format the json response message

### ISSUE THREAD

**Issue by pulse-mind** [jarrodek/ChromeRestClient#1178]
Thank you for your job
It could be nice to click on a button to format the json in the response message

## Expected outcome
When the response message is json it could be nice to be able to format it (like in a IDE)

## Actual outcome
The json is displayed as a blick of text

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

## Steps to reproduce
1. send a request to a web-service that return a json

**Comment by jarrodek** [comment]
Hi,

When you see JSON message like this it means that the server did not return the correct content type that would indicate that the response is a JSON response. Other reason is that the repone has invalid JSON that cannot be parsed and therefore ARC uses the "raw" viewer to render the response.
