### ISSUE TITLE
On start app never stops loading, memory and CPU consumption go through the roof 

### ISSUE THREAD

**Issue by BjoernZen** [jarrodek/ChromeRestClient#1181]
Your description here
Just started the Chrome app. When ist comes up "History" and "Saved" tabs on the side bar never stop loading. Also CPU consumption is very high. Memory consumption won't stop rising (see snapshot, it's at 15GB). After a while it crashes.
![grafik](https://user-images.githubusercontent.com/51834116/108533629-79b05100-72d9-11eb-8b4e-a2138e0681c4.png)

It worked normally yesterday when I installed it for the first time. Just used it for quite simple rest requests.
## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
The Chrome application is no longer developed as the Chrome team removes support for it. Please, use the desktop client which is a replacement for this application from https://install.advancedrestclient.com/install
