### ISSUE TITLE
JSON tab does not handle numbers above 15 digits long

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#234]
Originally reported on Google Code with ID 238
```
What steps will reproduce the problem?
1. Get respose from server in JSON. At least one value should has 16 or more digits.
2. RAW tab show correct response. JSON tab rounds digits to 15 numbers (see jobId below).

What is the expected output? 
"jobId":710000000017630930
RAW:
{"id":"-1017217058851284123","jsonrpc":"2.0","result":{"delay":20,"errorMessage":null,"jobNumber":637233,"jobDate":"2014-03-03
13:10:25","price":null,"jobId":710000000017630930,"errorCode":null}}

What do you see instead?
jobId: 710000000017631000
JSON:
{
id: "-1017217058851284123"
jsonrpc: "2.0"
result: {
delay: 20
errorMessage: null
jobNumber: 637233
jobDate: "2014-03-03 13:10:25"
price: null
jobId: 710000000017631000
errorCode: null
}-
}

On what operating system, browser and browser version?
Windows 7 64 bit, chrome 33.0.1750.117 m


```

Reported by `sinyagovsky` on 2014-03-03 09:19:13

**Comment by Imagix** [comment]
+1 on this.  I'm getting "[15743151143831414272]" back in the REST response, but the decoded JSON is reporting "0:  15743151143831415000".  Oddly enough, using the Copy to Clipboard gets you the correct  value.  (Context: I'm using this to talk to a Ryu SDN Controller, and one of my switches is reporting the above number as it's ID).   I'm using Chrome 48.0.2564.109 on OSX 10.11.3

**Comment by jarrodek** [comment]
I'm not sure how to proceed with it. 
When I receive a JavaScript object from JSON (using JSON.parse) it will result with JavaScript Number object if the value is a number. Because numbers in JavaScript are considered accurate up to 15 digits it is impossible for the app to display it correctly. 
I could use custom JSON parser but it will influence performance which is already compromised by custom highlighting. 
"Copy to clipboard" is working properly because it use source data represented as string not a number so there is no problem with 64-bit numbers.
I have it in mind to do something with it but I need to figure it out how to to custom parsing without compromising performance.

**Comment by Imagix** [comment]
Any way to mark it as "incomplete" or something so that users at least know that it's the wrong number?

**Comment by jarrodek** [comment]
It makes sense. 
I'll either provide information about inaccuracy or implement different JSON parser.
