### ISSUE TITLE
Show .png response as image

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#304]
Originally reported on Google Code with ID 308
```
When testing WMS services (http://en.wikipedia.org/wiki/Web_Map_Service), it is very
common to receive an image (.png, .jpg, .gif) as response. It would be nice to see
the image itself in the response pane instead of the bytes. I have attached a screenshot
to clarify this.

When I paste the same url in a new browser tab, the image is shown correctly.

An example of such a (GET) request: http://geo.api.agiv.be/geodiensten/raadpleegdiensten/GRB-basiskaart/wms?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=GRB_BASISKAART&WIDTH=1680&HEIGHT=674&CRS=EPSG:3857&BBOX=468241.9483493314,6638450.68553925,476267.8363194879,6641670.595355849

```

Reported by `ward.delabastita` on 2015-04-29 13:00:01

<hr>
 * *Attachment: 2015-04-29 14_54_34-Advanced Rest Client Application.png<br>![2015-04-29 14_54_34-Advanced Rest Client Application.png](https://storage.googleapis.com/google-code-attachments/chrome-rest-client/issue-308/comment-0/2015-04-29 14_54_34-Advanced Rest Client Application.png)*

**Comment by jarrodek** [comment]
It may require change in core request class and replace XHR2 with fetch API which is more flexible for getting a binary data.

**Comment by henrik242** [comment]
+1 on this.  Also support for .svg :)

**Comment by jarrodek** [comment]
But svg id a XML data. I'm not sure if the app should display it as an image or as a source.

**Comment by henrik242** [comment]
How about both? One tab with the image and one tab with the xml?

**Comment by jarrodek** [comment]
It may work. Right now, however, I'm working on an app upgrade to Chrome Packaged apps. It also brings new UI for the app. It may be good opportunity to do so. But I'll can handle it in couple of weeks since I have a lot of work with upgrade itself.
