### ISSUE TITLE
Chrome cache

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#316]
Add support for clearing the cache.

It may be very difficult to clear the cache since it's heavy lifting operation in the background using the chrome.browsingData API.
Other approach is to append header / parameter to the request but it will interfere with the request too much and it may broke some types of the requests.
Need to check how Chrome Dev Tools keep cache clean while it's open (it's an extension after all).

**Comment by Hao-Wu** [comment]
hello @jarrodek , Is the feature clearing cookie already released ?

**Comment by jarrodek** [comment]
The app is no longer depends on Chrome cache system since it is using sockets instead of standard transport. It's in beta channel right now and will be released very soon.
