### ISSUE TITLE
History Grid

### ISSUE THREAD

**Issue by DiggaTheWolf** [jarrodek/ChromeRestClient#323]
Hi

The latest update has affected the display of the history grid. The previous version had a layout where the URL was fully visible and enabled the selection of an item by seeing the URL. Now a great percentage of the grid area is taken up with the Method column and the URL column data is truncated.

Kind regards,

Lee

**Comment by jarrodek** [comment]
I'll look into this but I haven't touch this view. Can you provide a screenshot for this issue?

**Comment by DiggaTheWolf** [comment]
[cid:image001.png@01D12C56.86EDDC40]

Kind regards,

Lee Diggins
Phone +44 1494 714060 | Mobile +44 7876 331053
lee.diggins@iisdev.com<mailto:lee.diggins@iisdev.com>
www.iisdev.com<http://www.iisdev.com/>
[cid:image002.png@01CE7414.5E7F92F0]<http://www.facebook.com/lee.diggins>[cid:image003.png@01CE7414.5E7F92F0]<https://www.linkedin.com/in/leediggins>[cid:image004.png@01CE7414.5E7F92F0]<http://www.youtube.com/user/diggathewolf>[cid:image005.png@01CE7414.5E7F92F0]<https://twitter.com/DiggaTheWolf>[cid:image007.png@01D12C56.86F11090]<https://plus.google.com/100360931168906033671>

**Comment by DiggaTheWolf** [comment]
Here you go...
![restclient](https://cloud.githubusercontent.com/assets/16100407/11507058/27c4a25c-984a-11e5-9508-0f9634093a81.png)

**Comment by jarrodek** [comment]
Thanks @DiggaTheWolf I'll look into it today.

**Comment by jarrodek** [comment]
It's fixed in develop branch. Soon it will be updated in Chrome Web Store.

**Comment by DiggaTheWolf** [comment]
Many thanks @jarrodek for the speedy response and fix. It's really appreciated.

**Comment by DiggaTheWolf** [comment]
Hi @jarrodek 

Just wondering what is your release schedule and when is this update likely to get pushed to the store? As it's proving difficult to use in it's present state

**Comment by jarrodek** [comment]
Hi

**Comment by jarrodek** [comment]
Hi,

I'm not yet ready to announce release scheduler publicly. But I'll do it in some time. Just want to think through it very carefully before I'll promise something.

The update is already in CWS. However it's incremental publish so you may need to wait to next week until you'll receive an update.

Thanks
Pawel
