### ISSUE TITLE
How to Solve Cors [it's not your app fault, is mine, but work in yours ]

### ISSUE THREAD

**Issue by deadmann** [jarrodek/ChromeRestClient#324]
I know here is not a place to ask questions, but I can't find resources which talk about this issue in a way I require it. 

My boss have a aged wcf service, which I cannot change and required me to provide android application,  due to design requirement,  I decide to go with a hybrid application,  which consume Haml,  so I did it using vs Cordova and angular js,  and now I'm requiring a XmlHttpRequest to be made to server data,  but when I use your client everything is fine,  but when i use the service within my app or fail due Cors issue,  I was wonder due your knowledge based on these stuff,  may by any chance you can help me...

**Comment by jarrodek** [comment]
I can't help you with it since I know little about android apps development. You can start with https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS where this issue is described.

**Comment by deadmann** [comment]
thank you.
