### ISSUE TITLE
[JSON Parser] CSS for link not needed (hide information)

### ISSUE THREAD

**Issue by Bew78LesellB** [jarrodek/ChromeRestClient#325]
Hello,

When I have a JSON response like : 

```json
{ "deleted":true,"lastVersion":109,"path":"\/etc\/vim74\/"}
```

I expect the JSON Parser to give me : 

```json
{
    deleted: true,
    lastVersion: 109,
    path: "/etc/vim74"
}
```

But it displays me : 

```json
{
    deleted: true,
    lastVersion: 109,
    path: "/ETC/VIM74"
}
```

**Note the uppercases...**

It's because `/etc/vim74` is detected as a URL, and the JSON Parser transform it as a link..
And the uppercases are because all links of your app are in uppercase, *including thoses in the JSON Parser....*

Thanks for reading

**Comment by jarrodek** [comment]
Hi,
Thanks for reporting.
I've already updated it in Chrome Web Store. Sorry for it.
You should receive update automatically.

**Comment by Bew78LesellB** [comment]
Works perfectly, thanks !
