### ISSUE TITLE
The UI, all of a sudden, looks really bad and is rather sluggish

### ISSUE THREAD

**Issue by robertkuhar** [jarrodek/ChromeRestClient#326]
The Advanced REST Client has suddenly become pretty sluggish and renders very poorly.  What changed?  I've been using this for a couple of years now and its never behaved like this.

The presentation issue is annoying, but not such a big deal (see attached).

The sluggishness, though.  Is a much bigger issue.  The requests themselves seem to be running fine, but it takes a couple of seconds for Advanced REST client to render a request that itself took something like 171ms.

![screen shot 2015-12-07 at 4 53 17 pm](https://cloud.githubusercontent.com/assets/190304/11644710/3e2f002e-9d03-11e5-90b5-73db759e7c43.png)

I tried closing Chrome hoping that it had something to do with the other tabs or something, but to no avail.

This is Chrome on OS X El Capitan Version 10.11.1

Whats up with that?

**Comment by robertkuhar** [comment]
Hmm.   Do "Projects" make a difference?  The UI doesn't look nearly as bad on Saved queries.  The sluggishness, though, remains whether Saved query or Project query.

**Comment by vanquang9387** [comment]
I have the same bad UI in "Projects".

Advanced Rest Client Application version: 3.3.1.1 Stable
Chrome Windows version 47.0.2526.73 m

**Comment by jarrodek** [comment]
I've corrected "projects" dropdown in the top bar. Update is already published in the store. That was the only thing I haven't tested before the release and I'm sorry.

Beside that the only change is color of the top bar and new icons for the URL filed.

**Comment by jarrodek** [comment]
It should be OK now.
