### ISSUE TITLE
Remove switch options for CodeMirror from settings

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#333]
CodeMirror is well tested and should be enabled by default without turning off option in settings.

**Comment by justinhelmer** [comment]
I disagree :-)

@see [#354](https://github.com/jarrodek/ChromeRestClient/issues/354)

**Comment by jarrodek** [comment]
It's a long term issue. 
Before I totally move to code mirror I will update CM lib to the newest one and fix #354

**Comment by jarrodek** [comment]
CodeMirror integration has been rewritten and ARC is fully integrated with current version of the library. There is no option to disable it since it has ability to auto fill headers value and format payload editor.
Also any previous issues related to change event has been resolved in upcoming version.
