### ISSUE TITLE
Add ordered list for the project endpoints 

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#340]
Add ability to reorder the projects and the requests inside a project to group them logically.

**Comment by justinhelmer** [comment]
awesome. sorry I missed this and took your time.

**Comment by jarrodek** [comment]
No worries.

**Comment by jarrodek** [comment]
There is a model base class [OrderedList](https://github.com/jarrodek/ChromeRestClient/blob/chrome-app/app/scripts/libs/app.types.js#L262) that will support ordering in the list.
RequestObject and ProjectObject models will extend this class. Then whey will gain the ability to order themselves in the list.

**Comment by jarrodek** [comment]
The release with fix has been published today.
Thanks for reporting the bug.
