### ISSUE TITLE
Unknown error occured with the latest version

### ISSUE THREAD

**Issue by Muhammed-Musthafa** [jarrodek/ChromeRestClient#343]
The app got upgraded to version 4.3.0 today and is not working afterwards.
Whenever a requested is triggered to a locally hosted/remote rest endpoint, chrome pops up the following error.

Unknown error occured: Unknown background page communication system @com.google.gwt.chrome.messag.ChromeMessagePassingImpl::sendExtensionMessage

Chrome version: Version 33.0.1736.2

**Comment by JohanBohan** [comment]
Check Content-Type: it always ->  application/x-www-form-urlencoded

**Comment by Muhammed-Musthafa** [comment]
Tried with content type application/x-www-form-urlencoded and Content-Type: application/json but the issue still exists.

**Comment by mcdoma2000** [comment]
I am seeing the same thing, and it couldn't come at a worse time for me. I rely on this tool, and now it's useless to me.

**Comment by jarrodek** [comment]
Is this happening all the time or in specific situation? I fixed issue related to this error last night but I'm not sure it there's more situations like that.

**Comment by Muhammed-Musthafa** [comment]
Its happening all the time for me.

**Comment by jarrodek** [comment]
Are you using a repo version or from the Chrome Web Store?
It could happen only if there's an error in the background page. And I'm talking about error like Syntax error which will stop background script from initialization the code in overall. 
The error you see can only be caused if specific function in the background page does not exists. Please, go to the chrome://extensions/ URL in the "Advanced REST client" item click on "background page" in "Inspect views" area. Then copy any error it contains.

**Comment by Muhammed-Musthafa** [comment]
Im using the version installed from Chrome Web Store. 

Please find the error from inspect view: background page

Uncaught SyntaxError: Use of future reserved word in strict mode app.db.websql.js:87
Uncaught SyntaxError: Use of const in strict mode. background.js:23

**Comment by Honey-Haidi** [comment]
Is there any solution u guys found ?
I am facing the same problem.

**Comment by tenwx** [comment]
![image](https://cloud.githubusercontent.com/assets/3733304/12287627/fee41df0-ba08-11e5-909c-b5877985634d.png)
I am facing the same problem too.

**Comment by jarrodek** [comment]
According to this log your Chrome version is just too old. Fetch API was introduced in Chrome 42. Current stable version is 47. Right now the app is in active development to to gain on performance and flexibility it will use new web APIs.
Currently minimum version for the Chrome that supports the app is 45. 
The only possibility to return to previous version is to build the app from the source code, from master branch, from the beginning of November 2015. That's all I can do.
Wait however for today's update and check if it start working. If not there's no going back. New version is 4.5.1.

**Comment by Muhammed-Musthafa** [comment]
@jarrodek Thanks,
Upgraded chrome to version 47, and issue resolved.

**Comment by jarrodek** [comment]
It should work in 45 as well but it's always good to have latest version.
