### ISSUE TITLE
header settings are not saved

### ISSUE THREAD

**Issue by wizard-joe** [jarrodek/ChromeRestClient#345]
eg. if "Content-Type: application/json" is saved, reloading entry will default to "Content-Type: application/x-www-form-urlencoded"

**Comment by JohanBohan** [comment]
The same problem for all saved projects! 
Edit Content-Type doesn't work, have to change it manually inside the body.

**Comment by justinhelmer** [comment]
Same issue here.

More specifically:

When endpoints are _not_ saved to a project, navigating to the endpoint will initially display `application/x-www-form-urlencoded`. However a hard refresh (`shift+refresh`) corrects the problem.

When endpoints are saved to a project, the `Content-Type` header always reverts to `application/x-www-form-urlencoded`. A hard refresh has no effect.

Additionally, toggling `CodeMirror` settings has no effect.

**Comment by jarrodek** [comment]
I found the problem.
The old dropdown option had it's own field in the database. When data was restored the the value for this field was overriding the value in headers list. This is an error and it is fixed in a hotfix branch.
When I test is I'll update the app in the store.

**Comment by JohanBohan** [comment]
So far so good, particularly for Content-Type. Thanks good job !

**Comment by justinhelmer** [comment]
@jarrodek we all appreciate the quick turnaround. Cheers.
