### ISSUE TITLE
ContentType Header Add/Remove/Re-Add

### ISSUE THREAD

**Issue by smithcb** [jarrodek/ChromeRestClient#346]
If you add a Content Type Header, via the Form, then remove it, re-adding it doesn't work.  you have to refresh the screen (F5) to re-add the content type value.

**Comment by jarrodek** [comment]
Thanks for reporting. I checked it and it looks like it does not propagate changes in the editor accordly. 
I'll look into it right now.

**Comment by justinhelmer** [comment]
Most likely related to [header settings are not saved #345](https://github.com/jarrodek/ChromeRestClient/issues/345). My guess is you are killing two birds with one stone.

Thanks for looking into this.

**Comment by jarrodek** [comment]
Duplicate of #345
