### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by mrogoff** [jarrodek/ChromeRestClient#347]
When I past the "Content-type: application/json" or "X-Auth-Token: 983756923879238769823857" into the headers box it splits it across two lines. Send gives a "Probably the value you entered is not a valid headers value" until the pasted input is made into one line.

**Comment by jarrodek** [comment]
Is there any possibility that copied text have new line character between header name and value?
This behaviour is expected when you paste non header like value - like in you case. The parser is trying to parse a headers value and when discovers that some values are missing (in this case moved to next line) then it rise an error.
The app however do not move values to new lines. It must be copied from the original source.
Can you check this first, please?

**Comment by mrogoff** [comment]
I am copying it from the response header section of the app to the headers
box just like I have been doing for years. With this latest update the
paste puts it on two lines.
[image: Inline image 1]



[image: Inline image 2]

**Comment by jarrodek** [comment]
OK, now I get it.
Thanks for letting me know!

**Comment by jarrodek** [comment]
This will be fixed in next hotfix release (in couple of hours).
