### ISSUE TITLE
Payload and headers ignored without keypress event, when CodeMirror is enabled

### ISSUE THREAD

**Issue by justinhelmer** [jarrodek/ChromeRestClient#354]
Not sure if it's `keydown` or `keyup` or what (didn't look into it), but I noticed a funny little bug where things weren't working as expected.

I often times (as I'm sure others do as well), copy/paste large payloads. However the payload is ignored if I don't interact with the `payload` textarea before sending the request.

The same holds true the other way: if I _cut_ text out of the payload textarea, the previously registered payload gets sent with the request.

I did not try toggling `localStorage` settings to see if it had an impact.

EDIT: although to me this is very minor, it may not be immediately recognizable by others, and may seems like a major bug that causes a lot of headache.

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
Is this related to regular textarea or do you have CodeMirror enabled?

It basically should update current payload value when the input fields (any in the editor) lose focus. 
I just tried to do it in the latest app (both for code mirror and without it) and it works as expected (request have proper payload). I will however try to figure it out.

**Comment by justinhelmer** [comment]
@jarrodek - just checked, it is consistently related to `CodeMirror`. this issue does not exist with the `CodeMirror` editor enabled. It also occurs for _both_ the payload _and_ headers and is consistently related to `CodeMirror` being enabled.

To expand further, the event isn't firing for `cut`, `paste`, `undo`, `redo`, etc.

If I go into headers or payload, add a `space`, it registers and all is well.

For the meantime, I will disable `CodeMirror`

**Comment by jarrodek** [comment]
Thanks for further explanation. I'll look into it in some time.

**Comment by justinhelmer** [comment]
updated issue title to reflect new discoveries relating to headers and `CodeMirror`, as outlined [here](https://github.com/jarrodek/ChromeRestClient/issues/354#issuecomment-171393117)

**Comment by justinhelmer** [comment]
Thanks!
