### ISSUE TITLE
New projects don't show up until fresh serve

### ISSUE THREAD

**Issue by justinhelmer** [jarrodek/ChromeRestClient#355]
During the `save` process, if `create new project` is used, the project does not show up in the menu without a refresh.

At least this is the case in the scenario where there was previously an empty set. 

I had initially thought that the request and project were not successfully saved, and it could be potentially misleading.

It's also likely that some of the other issues in this queue related to missing projects will be cleared up as a result.

**Comment by jarrodek** [comment]
I've noticed it couple of days ago and I'm aware of it. I can't however fix it right now since I begun work on app upgrade to new Chrome apps architecture. I'll fix it as soon as I have some time for it.

**Comment by jarrodek** [comment]
I've fixed it last week. Should works now.

**Comment by justinhelmer** [comment]
Great thanks @jarrodek
