### ISSUE TITLE
Content-Type drop down no longer available?

### ISSUE THREAD

**Issue by stevehall19** [jarrodek/ChromeRestClient#361]
Hi,

I'm using version 4.5 of the client. Previously, when sending POST requests there would be a drop down under the textarea for the payload where the content-type could be specified. This drop down is no longer appearing for me and I don't see anyway to set the content-type (it always submits as application/x-www-form-urlencoded). See the attached screenshot. Am I missing something obvious?
![screen shot 2016-01-14 at 10 31 56 am](https://cloud.githubusercontent.com/assets/5874027/12330406/8bf03908-baaa-11e5-926c-452ab082a858.png)

**Comment by jarrodek** [comment]
Please, reffer to my blog post: http://restforchrome.blogspot.co.uk/2016/01/encoding-drop-down-removal-from-app.html
