### ISSUE TITLE
History not restoring headers

### ISSUE THREAD

**Issue by matdelong** [jarrodek/ChromeRestClient#362]
When I select an item from the history, it doesn't restore the headers I was setting in the original request.

**Comment by jarrodek** [comment]
Can you tell me on which Chrome version you are? And app version?
Is there any error in the console? Are headers saved in the request? You can check it clicking on a request row in saved view. It should expand request details. On the right side of expanded view there should be a list of headers saved with the request.

**Comment by matdelong** [comment]
The headers aren't shown in the history row when expanding the row (clicking on it.) The URL is there, and then when expanded I see "application/x-www-form-urlencoded" (Even though I had set a Content-Type header with a value of application/json).

Chrome Version: 46.0.2490.86 (64-bit)
OS: OS X Yosemite
App Version: 4.6.0 Stable

**Comment by jarrodek** [comment]
The 'application/x-www-form-urlencoded' it's a legacy thing. It doesn't do anything actually. If there are header saved with the request they should be on the right in expanded panel. On the left where is a 'encoding' field. If there's no headers definitions it means that they weren't saved. Maybe there's some error during save? No one complain about it earlier and this module hasn't changed for two years now. 
I may run some test and find something but it would be great if you find a time to test it by yourself as well and check is there an error.
