### ISSUE TITLE
It isn't good that appending the default Content-Type in the http header

### ISSUE THREAD

**Issue by shengang1978** [jarrodek/ChromeRestClient#364]
Now, all the POST/PUT/? method append the default Content-Type(Content-Type: application/x-www-form-urlencoded) in the header field. And I don't find the setting to replace this default value. It's realy not good to me because we use the "Content-Type: application/json". 
I have to replace the content-type by hand when I change the api.

Where can I set the default content-type?

**Comment by jarrodek** [comment]
There's no such setting. It is the same behaviour how it always was in the app. But earlier it was covered by encoding drop-down.

Adding the header into the list is a handy feature. 1) it notice developer that there is some change and he should react if required 2) the developer don't need to do it manually. 
There are a lot of different mime types. For you most common mime type for the request is application/json, for others it will be something else. I used the most basic and generic web content type for data sending and you can always change it.

I also decided not to complicate application more so I'm not planning adding another setting. It may change in the future but current status will be wontfix.
