### ISSUE TITLE
Error "You do not have Advanced Rest Client Installed" using Google Drived saved calls

### ISSUE THREAD

**Issue by titelivebe** [jarrodek/ChromeRestClient#369]
Hi,

I'm developping REST APIs, and your app is what I suggest to our customers.

I tried to share some savec calls with them via Google Drive, but I face some troubles.
The file sharing seems to work ; it opens prompting "open me with Advanced Rest Client".  Then the Client seems to lanch well (I land on the white page with the two-arrowed-icon and the timer), but after a few seconds, it says "You do not have Advanced Rest Client Installed".

What do I do wrong ?

Thanks a lot for the help (and for the app, of course).

**Comment by jarrodek** [comment]
It looks like the script in [gdriveinit.js] file is executed after page load so the content script is not calling the backgroud page.

That's an irony. Couple of days ago I helped someone with the same issue.

But I also noticed another issue in [background js].
The `var query = request.params;` should be actually a `var query = request.data;`.

I can't update it right away but I'll try to do it in next 24 hours. Meanwhile you and your client can use "Open from google drive" button in saved list instead. They will see all ARC files shared with them.

[gdriveinit.js]: <https://github.com/jarrodek/ChromeRestClient/blob/master/RestClient/war/gdriveinit.js#L24>
[background js]: <https://github.com/jarrodek/ChromeRestClient/blob/master/RestClient/war/background.js#L194>

**Comment by titelivebe** [comment]
Wow, thanks a lot.  That's quick enough :D

Everybody mess up again and again with JS load order, even the best ones, so don't blame you ;)

**Comment by jarrodek** [comment]
The commit is in hotfix branch that is is not yet merged with master and therefore not published to the store.
Since I have end-of-term examinations now I have to delay it until next week. Still I need to test couple of things before I do a release.

**Comment by titelivebe** [comment]
That's great !

Can't wait until there...  That's something very usefull you provide.

**Comment by titelivebe** [comment]
Mmmh, now that seems to launch but fail...
- I click on the Google drive Link,
- then on "Associated application : Advanced Rest Client",
- an "about:blank" page opens with the logo and a timer,
- then an URL blinks for about 0.1 sec showing "chrome rest client appspot" or something like that,
- then again on the "about:blank", which remains :(

Hope that helps !

**Comment by jarrodek** [comment]
I didn't noticed that Chrome's behaviour changed. I can't assign chrome-extension:// scheme anymore to window.location object.
I changed the script so it will update the tab from the background page instead of content script. 
I'll update it today and it's definitely working now.
