### ISSUE TITLE
Payload not updated in code-mirror when pasted, ctrl+z or ctrl+y

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#370]
The CodeMirror component do not update the content when ctrl+z or ctrl+y or ctrl+v.
Instead old payload data is sent.

Observe events fired logs in console. For this actions there are no logs. Logs are printed only on change by adding or removing some text "manually".

**Comment by mukundgoel** [comment]
Hi @jarrodek is there an ETA for this fix? It started happening in the new version of rest client that was released in end of Jan. Thanks!

**Comment by jarrodek** [comment]
I'll make a release within 24 hrs.

**Comment by mukundgoel** [comment]
thanks @jarrodek appreciate the quick turnaround
