### ISSUE TITLE
POST and PUT not working at all.

### ISSUE THREAD

**Issue by vishalvgy** [jarrodek/ChromeRestClient#371]
I'm trying GET, PUT and POST requests. Only GET is working not PUT and POST. I wasted lot of my time tracking for  a bug in my code.

**Comment by vishalvgy** [comment]
Please tell me how to revert to older version.

**Comment by JamiePattison** [comment]
I had the same issue. I used Fiddler > Composer within the request header i added Content-type: application/x-www-form-urlencoded (in other words you may not need to do this depending on the type of request your sending) and in the body added my form variables which resolved my issue. Hope this helps

**Comment by jarrodek** [comment]
Are you sure that there was proper content type header in the request? You may removed it and then the request **may fail** (it depends on the server because spec describes that if there is no CT header the implementation may try to identity content type based on payload). Can you confirm it?

**Comment by vishalvgy** [comment]
Well now it's bigger headache than earlier.  I'm trying to send a GET
request from client but it is sending  a POST to my webservice. You can
refer to the screen shots.

**Comment by vishalvgy** [comment]
Please tell me how to revert back to older version. I can't afford to waste
anymore time with this now.

**Comment by jarrodek** [comment]
GitHub is not processing images from email. This issue is very rare and I couldn't detect it on Chrome >= 44. What version of Chrome are you using? Is there an error in console?

**Comment by vishalvgy** [comment]
Version 48.0.2564.97 (64-bit)

**Comment by wilburdsouza** [comment]
Post requests are not working for me.  Just keeps spinning.  Request that worked prior to upgrade are not working too.

**Comment by jarrodek** [comment]
@wilburdsouza Can you check if there is any error in the app? It will help me find a bug.
To do it go to `chrome://extensions` page, **check the developer mode checkbox**, and the in the apps listing find ARC and click on 'index.html' view. This will enable Chrome Dev Tools for the app. You should see an error.
After you finish I suggest to turn off developer mode for better performance.

**Comment by wilburdsouza** [comment]
@jarrodek 


elements.js:24548 Uncaught (in promise) ReferenceError: URLSearchParams is not defined(…)_createFileBuffer @ elements.js:24548Promise @ elements.js:24443generateMessage @ elements.js:24441_onConnected @ elements.js:24426promise.then @ elements.js:24194

Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/18309026/14320284/7cfbd6b8-fbe2-11e5-9887-a8415b0fac63.png)

**Comment by jarrodek** [comment]
OK, thanks for debug info.
It looks like I have used interface that is available from Chrome 49 (which is previous release). However I marked minimum version for upgrade to 47. I'll hotfix it.

**Comment by jarrodek** [comment]
This is fixed in beta now.
