### ISSUE TITLE
Import Project data from file issue

### ISSUE THREAD

**Issue by Jezzy29** [jarrodek/ChromeRestClient#372]
Since the last update, I'm not able to load a file with 2 projects.

Version : Application version: 4.10.0 - Stable
Chrome : 47.0.2526.11 m

The import seems to works: 
- I see all my requests before clicking import
- The projects appear under the "Projects Menu".

But when selecting any of the projets, I get the error "Can't find default endpoint for this project."

I can't see any of the request...

See attached file.

Thanks
[arc-2016 Jan 22 11-19-32.json.txt](https://github.com/jarrodek/ChromeRestClient/files/109472/arc-2016.Jan.22.11-19-32.json.txt)

**Comment by jarrodek** [comment]
I already started working on that. Should be available in a matter of days.
