### ISSUE TITLE
Post data using form variables not working

### ISSUE THREAD

**Issue by JamiePattison** [jarrodek/ChromeRestClient#373]
I receive some form variables and can see them within ARC. When i click send these form variables are not submitted - they are empty.

Appreciate a quick fix on this or advise on how to revert back to a previous version?

**Comment by JamiePattison** [comment]
Actually i just used Fiddler and added Content-type: application/x-www-form-urlencoded to get the same operation as this

**Comment by jarrodek** [comment]
I'm not sure where's the issue. Are you trying to send POST data and the payload isn't there?

**Comment by jarrodek** [comment]
is this related to #371 ?
