### ISSUE TITLE
url textbox padding issue

### ISSUE THREAD

**Issue by ahmedali5530** [jarrodek/ChromeRestClient#376]
in url textbox padding creates issue, when i type a url in it, it dont display the url, please decrease the top and bottom padding and increase height.
![image](https://cloud.githubusercontent.com/assets/4495669/12879604/59a679d8-ce57-11e5-9761-d8e5f2aaa6d5.png)

as you can see in this screenshot **URL** placeholder is missing and padding is covering all textbox.

**Comment by jarrodek** [comment]
It looks like some change in Chrome itself. This components hasn't been modified for a long time.
I'm fixing it right now.
