### ISSUE TITLE
After 2016/02/08 update, projects are not listed.

### ISSUE THREAD

**Issue by dan956** [jarrodek/ChromeRestClient#380]
After latest update There are no projects listed under Projects side bar tab.  Only "No projects here" is listed.  In Chrome developer tools under Web SQL, I can see the projects and the associated request_data.

When I save a new request, it correctly asks me which project I want to add it to.  After saving, it still does not show in Projects list.

```
IndexedDB global error Error: Database version changed by other database connection. libs.js:237
    at IDBDatabase. <anonymous> (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/components/dexie-js/dist/latest/Dexie.js:80:37)
(anonymous function) @ libs.js:237
(anonymous function) @ Dexie.js:80
```

**Comment by jarrodek** [comment]
Can you see data under IndexedDB? This update switched database engine to IndexedDB. I tried to reproduce an error but nothing happens. I'll dig to it now.

**Comment by jarrodek** [comment]
You can alternately go to settings and click on "Clear IndexedDB and import data from WebSQL". This will destroy IDB database and recreate it from WebSQL data.
I strongly discourage switching off IndexedDB since next major update will make impossible to read WebSQL data and data synchronization between engines won't be possible.

**Comment by dan956** [comment]
My IndexedDB is empty and I don't see the option to "Clearn IndexedDB and import data from WebSQL".  I am on Mac OS X Yosemite 10.10.3, with Google Chrome Version 46.0.2490.86 (64-bit).

Here is the entire console log when I navigate to ARC:
[hgmloofddffdnphfgcellkdfbfbjeloo-1455059553419.txt](https://github.com/jarrodek/ChromeRestClient/files/123914/hgmloofddffdnphfgcellkdfbfbjeloo-1455059553419.txt)

**Comment by jarrodek** [comment]
This option is in settings. 2nd on the list from bottom. Just above factory reset option.

As for the logs - it doesn't have any sense to me. It missing some logs. Maybe you can help me more.
There's definitely an error during initialization. However I can't see any errors here.
If you could set a breakpoints in your instance and tell me what error was causing database not to be initialized it would be helpful.

Please, setup breakpoints just like on image below and refresh the app (dev tools must be opened).

![console](https://cloud.githubusercontent.com/assets/3320020/12936302/757a92ae-cf95-11e5-8e1e-e7b2163fc4e6.png)

When it stops you'll be able to print error variable (eg. `JSON.stringify(error)`). Please, paste the result here. I couldn't reproduce the problem in my test environment.

**Comment by sataris** [comment]
I'm having similar problems, I receive the following errors 

Breakpoint on line 336 of lib.js

Uncaught (in promise) Error: Database not open. Following error in populate, ready or upgrade function made Dexie.open() fail: AbortError occurred when opening database arc. Version change transaction was aborted in upgradeneeded event handler.(…)

**Comment by jarrodek** [comment]
It is a temporary workaround. However after next major update (2-3 weeks) WebSQL won't work and the data will be lost. I'll work on this issue later this week.

**Comment by drdorne** [comment]
I am having the same issue with Projects not showing up. I have disabled using IndexedDB in settings and will wait for an update from you on this bug.

**Comment by drdorne** [comment]
Is there a new build coming with this fix?

**Comment by jarrodek** [comment]
Yes, I've send an update to the Chrome Web Store. It seems that the issue is resolved (at least in my test environment) but I'd be glad for an info if it is working properly.

**Comment by arismydoc** [comment]
I can tentatively confirm that this seems to be working now. Thanks for the quick fix!

**Comment by sataris** [comment]
I can tentatively confirm that this is does fix the issue, I've switched back to IndexedDB and can  see all my projects. 

Thanks for the quick fix!

**Comment by jarrodek** [comment]
@sataris but is it working now if you switch to IndexedDB? Try to recreate the datastore (next button after switch option). It should work now.

**Comment by sataris** [comment]
@jarrodek 

Sorry if I wasn't clear before, but yes switching to IndexedDB does work, I've also tried recreating the datastore and that also works correctly!

**Comment by jarrodek** [comment]
Good to know. Thanks!
