### ISSUE TITLE
Missing request/response header for HTTP redirect request

### ISSUE THREAD

**Issue by imamitjain** [jarrodek/ChromeRestClient#381]
Previous version used to display complete information when HTTP request gets redirected to another resource.
- Response header of original request.
- New request header, because of HTTP redirection.

Please bring back that feature, it's quite help for developer community.

**Comment by imamitjain** [comment]
Duplicate of #64

**Comment by jarrodek** [comment]
It seems to work in current version.Do you can see any error in the console?

![redirectds](https://cloud.githubusercontent.com/assets/3320020/12928481/88e39014-cf65-11e5-91ea-f758857a11ec.png)

**Comment by imamitjain** [comment]
Sorry for the churn, It is working fine. Thanks! 

Maybe I was using old version, reinstallation did the job.
