### ISSUE TITLE
New Requests not Saving in Project

### ISSUE THREAD

**Issue by spbatcognizant** [jarrodek/ChromeRestClient#382]
With the latest release, I am not longer able to save a new request to a project.  I am able to update an existing request, but not able to save a new one.  When I try and save, the drop down list for the requests goes away.  I have to then select another project and then come back to the desired project to see the drop down list again.  The new request is not present in the list.

**Comment by jarrodek** [comment]
The app is adding it to the 'saved' list instead of project. Therefore there is an issue with project saving flow.

**Comment by rupat** [comment]
can confirm this problem here too

Application version: 4.12.2
Stable

And yes: requests are saved to "saved" instead

**Comment by jarrodek** [comment]
I'll correct it this week. Today it won't be possible.

**Comment by JohanBohan** [comment]
Is it possible to deny auto-update to avoid some unexpected problems ? After latest update No any saved projects, only way to search through the history - it's not convenient!
