### ISSUE TITLE
Headers are with wrong format

### ISSUE THREAD

**Issue by galitc** [jarrodek/ChromeRestClient#386]
in headers - instead ':' imgetting ','.

For example:
header was define:

x-identity: {"deviceType": "ANDROID"} 

but when openning the call from saved project, the header become like below, and the rest request fails:

x-identity: {"deviceType", "ANDROID"} 

PLEASE fix it, it is very difficult to work this way...

**Comment by jarrodek** [comment]
Duplicate of #383
