### ISSUE TITLE
No saved project available after RestClient update

### ISSUE THREAD

**Issue by S-Sheetal** [jarrodek/ChromeRestClient#391]
None of my previously saved projects are available under 'Projects'. Application version: 4.12.8. 
I tried re-importing the projects from an old json file which did not work either.

**Comment by jarrodek** [comment]
Hi,

Thanks for an issue report. 
Can you see projects after import and after refreshing the tab? I thought I've fixed this earlier. Or it might be different problem.
It would be helpful if you could paste here console output after you import the file.

**Comment by amafernandes** [comment]
Hi,

I have the same issue, I can't save requests with projects associated with them. The error log is attached, also if I export the request there are projects defined like this: {"id":10, "name":"[object Object]", "created":NaN}.

[error_log.txt](https://github.com/jarrodek/ChromeRestClient/files/166980/error_log.txt)

**Comment by S-Sheetal** [comment]
I did not see projects after import, after refreshing the tab or even after restarting chrome.
However following workaround worked for me as I had all my project and tests backup in a json.
Workaround:
Remove ARC plugin, re-install it and import the project again (from backup json).
Unfortunately I did not capture the screenshot of issue before trying the workaround.

**Comment by jarrodek** [comment]
According to feedback I received it helps if you export data to file and re-import them again (no reinstall is required). I still can't reproduce the error and I can't find a bug. There will be an update in coming days. I tested it a lot and it should work.

**Comment by sc-theberling** [comment]
Where would ARC put saved items if not in drive? It recently updated to the standalone app but I don't have any of my saved REST requests.   I signed in here https://chromerestclient.appspot.com/listing.jsp
to see if they were stored there but I get a 500 error.

**Comment by jarrodek** [comment]
As per my discussion with a user of the app on my email I can conclude what happened.
About two months before the **big** upgrade there was "small" update on the datastore. Chrome apps do not support WebSQL storage and before update I needed to move all data to IndexedDB. And this did happened. However if you haved used the app for this time period the app finally has upgraded to new app and WebSQL database become unavailable for the apps.
Therefore if this is the case there's nothing I can do anymore. I've put a lot of effort in data migration befor but it the app wasn't use I couldn't do much about it.
