### ISSUE TITLE
Crush/Hang when using Hebrew characters in the payload field

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#401]
After some highlighting text attempts, the following payload makes the app freeze (It contains Hebrew characters):
START c=node:CategoryNameIdx('name:(אחת~0.7 AND שתיים~0.7)') 
return s

**Comment by jarrodek** [comment]
It is possible that the CodeMirror library (that is used to highlight the code) is crashing. 
I need investigate it.

**Comment by RanGold** [comment]
In case it could help, before you started updating the version, it didn't crash

**Comment by jarrodek** [comment]
In new version of the app I've changed the library that is highlighting the code. I tried the text you provided and it didn't crashed and displayed the text without an error. I guess it helped.
The app is in beta right now but soon enough will be released. If you'd like to try it by yourself before the release you can do it joining ARC beta program. More info here: http://restforchrome.blogspot.co.uk/2016/03/join-advanced-rest-client-beta-program.html
