### ISSUE TITLE
Clicking "clear all" button doesn't clear it all

### ISSUE THREAD

**Issue by avm99963** [jarrodek/ChromeRestClient#410]
## Steps to reproduce
1. Open ARC beta.
2. Go to the request tab.
3. Fill in the request URL, and afterwards expand it by clicking the arrow.
4. Click the "clear all" button in the top right corner of the window.

## Expected outcome
5. The host, path, query parameters and hash fields should be cleared.

## Actual outcome
5. The host, path, query parameters and hash fields are not being cleared.

## Versions
App: 5.2.4.70-beta
Chrome: 50.0.2661.49
Platform: Mac OS X (10_11_0)

**Comment by jarrodek** [comment]
Thanks for issue report.
Only "simple" form is cleared. Detailed form stays intact.
