### ISSUE TITLE
'LEARN MORE' button in introduction to beta app goes to 404 page.

### ISSUE THREAD

**Issue by frankkienl** [jarrodek/ChromeRestClient#411]
When you click on the Learn More button, you will be directed to:

http://restforchrome.blogspot.nl/2016/03/new-advanced-rest-client-chrome-app.html

![image](https://cloud.githubusercontent.com/assets/1552295/14100081/ad5d8588-f582-11e5-9ea9-609fa0cc4a8a.png)

This paged does not exist.

**Comment by jarrodek** [comment]
Thanks for an issue report. 

The 404 error is there because I haven't published articles yet. Since I'm not a native speaker I wanted to consult someone first about the content of the articles. I'll publish it very soon.

**Comment by jarrodek** [comment]
Articles are now published.
