### ISSUE TITLE
Textbox for raw payload as good as invisible.

### ISSUE THREAD

**Issue by frankkienl** [jarrodek/ChromeRestClient#412]
Your description here

## Expected outcome
I expected to see a textbox where I can enter a raw payload.

## Actual outcome
I saw nothing, but its there. I clicked on the space where its supposed to be, and began typing.
Its there, its just as good as invisible.
Idea: please add a border, so people can see there is a textbox there.

## Versions
App: 5.4.4.70-beta
Chrome: 49.0.2623.87
Platform: Windows (10)

## Steps to reproduce
1. Open ARC
2. Click Request
3. Click Raw Payload 

![image](https://cloud.githubusercontent.com/assets/1552295/14100305/62e925b4-f584-11e5-95fd-847c41d6a981.png)

**Comment by jarrodek** [comment]
Thanks for an issue report.

There's actually a border there. I can see it even in your screen shot.
Though, it's a thin light grey line and might be invisible in low contrast screens. I've consult a graphic designer about that before I start any change.

**Comment by frankkienl** [comment]
Thanks for the response, I checked it out on a different monitor, you're right. There is indeed a border.
I will try to adjust my monitor. :D !

**Comment by jarrodek** [comment]
But still it's a valid issue. Not everyone have calibrated monitor and it may lead to different experience on different devices. I'll see what I can do about it.
