### ISSUE TITLE
[BETA] Unclear how to add Request to Project if there aren't any Projects yet.

### ISSUE THREAD

**Issue by frankkienl** [jarrodek/ChromeRestClient#413]
I have a request I want to save to a project.
There are not projects yet.
But the save request dialog does not give me an option to make a project now.
The older version (non beta) did gave me that option.

## Expected outcome
When I save a request that I want to add to a project, and there isn't a project, I expect a possibility to add a project.

## Actual outcome
I don't see such option.

## Versions
App: 5.4.4.70-beta
Chrome: 49.0.2623.87
Platform: Windows (10)

## Steps to reproduce
1.  Request, make request
2. Save the Request, in the Dialog, click the box for 'save to project'
3. Press save.
4. Error message: 'Enter projectname or select from project list'. I don't see a textbox to enter projectname.

![image](https://cloud.githubusercontent.com/assets/1552295/14101031/96bd2502-f589-11e5-823a-ab519b1d1a53.png)

**Comment by jarrodek** [comment]
Thanks for an issue report!

There is an error associated with this behaviour:

> Uncaught TypeError: Cannot read property 'length' of null
> Polymer._computeShowProjectSelector	@	arc-save-dialog-view.js:114
> Polymer.Base.extend._annotatedComputationEffect	@	polymer.js:1579
> Polymer.Bind._modelApi._effectEffects	@	polymer.js:1382
> Polymer.Bind._modelApi._propertySetter	@	polymer.js:1366
> setter	@	polymer.js:1445
> (anonymous function)	@	polymer.js:1490
> Polymer.Base._addFeature._flushHandlers	@	polymer.js:2006
> Polymer.Base._addFeature._afterClientsReady	@	polymer.js:1972
> Polymer.Base._addFeature._ready	@	polymer-mini.js:63
> Polymer.Base._addFeature._tryReady	@	polymer-mini.js:49
> Polymer.Templatizer._constructorImpl	@	polymer.js:3864
> TemplateInstance	@	polymer.js:3668
> Polymer.Templatizer.stamp	@	polymer.js:3892
> Polymer._ensureInstance	@	polymer.js:4669
> Polymer._render	@	polymer.js:4651
> Debouncer.complete	@	polymer-mini.js:2087
> boundComplete	@	polymer-mini.js:2066
> Polymer.Async._atEndOfMicrotask	@	polymer-mini.js:2043
> window.MutationObserver.observe.characterData	@	polymer-mini.js:2058
> Mutation (async)		
> Polymer.Async.run	@	polymer-mini.js:2019
> Debouncer.go	@	polymer-mini.js:2075
> debounce	@	polymer-mini.js:2097
> Polymer.Base._addFeature.debounce	@	polymer-mini.js:2107
> Polymer.Templatizer._debounceTemplate	@	polymer.js:3709
> Polymer._queueRender	@	polymer.js:4631
> Polymer.Base.extend._observerEffect	@	polymer.js:1543
> Polymer.Bind._modelApi._effectEffects	@	polymer.js:1382
> Polymer.Bind._modelApi._propertySetter	@	polymer.js:1366
> Polymer.Bind._modelApi.__setProperty	@	polymer.js:1375
> Polymer.Base._addFeature._applyEffectValue	@	polymer.js:1874
> Polymer.Base.extend._annotationEffect	@	polymer.js:1526
> Polymer.Bind._modelApi._effectEffects	@	polymer.js:1382
> Polymer.Bind._modelApi._propertySetter	@	polymer.js:1366
> setter	@	polymer.js:1445
> (anonymous function)	@	polymer.js:1490
> Polymer.Base._addFeature._notifyListener	@	polymer.js:1996
> (anonymous function)	@	polymer.js:1511
> Polymer.Base._addFeature.fire	@	polymer.js:1252
> Polymer.Bind._modelApi._notifyChange	@	polymer.js:1349
> Polymer.Base.extend._notifyEffect	@	polymer.js:1534
> Polymer.Bind._modelApi._effectEffects	@	polymer.js:1382
> Polymer.Bind._modelApi._propertySetter	@	polymer.js:1366
> setter	@	polymer.js:1445
> Polymer.PaperCheckedElementBehaviorImpl._buttonStateChanged	@	paper-checked-element-behavior.js:32
> Polymer.IronButtonStateImpl._changedButtonState	@	iron-button-state.js:200
> Polymer.IronButtonStateImpl._activeChanged	@	iron-button-state.js:185
> Polymer.Base.extend._complexObserverEffect	@	polymer.js:1553
> Polymer.Bind._modelApi._effectEffects	@	polymer.js:1382
> Polymer.Bind._modelApi._propertySetter	@	polymer.js:1366
> setter	@	polymer.js:1445
> Polymer.IronButtonStateImpl._userActivate	@	iron-button-state.js:107
> Polymer.IronButtonStateImpl._tapHandler	@	iron-button-state.js:93
> handler	@	polymer.js:496
> Polymer.Base._addFeature.fire	@	polymer.js:1252
> Gestures.fire	@	polymer.js:833
> Gestures.register.forward	@	polymer.js:1123
> Gestures.register.click	@	polymer.js:1108
> Gestures.handleNative	@	polymer.js:723

It is an issue in the condition check. To be fixed very easily and very soon.
