### ISSUE TITLE
Error no show

### ISSUE THREAD

**Issue by TheoSabattie** [jarrodek/ChromeRestClient#419]
Hi, 

php text errors were show. 
Why do you remove that?
How can we repair my error If we have an icon instead of error text?

Ahah, you set that 4 days before I have to give my work to my teachers :')
Don't you want set that again? Please? :)

**Comment by jarrodek** [comment]
I don't understand the issue

**Comment by TheoSabattie** [comment]
Sometimes, there is php error.

Before update, error was in "raw" tab. Now, there is just a smiley with "Error with request".
It isn't very helpful for debugging... :/

**Comment by jarrodek** [comment]
It means that there were no message with the response. It displays the response even if it is errored response. But if status of the response can't be determined this message will be displayed. 

Can you copy here an errored response from your server? With the headers, status and message (remove sensitive data). Then I'll be able to recognized how to help you.

**Comment by TheoSabattie** [comment]
Sorry for delay, It is when an Exception is throwed. I was waiting stacktrace output of it.
Before update, stacktrace was showed.

I didn't set specific headers or message.

**Comment by Kivshar** [comment]
Hello. I have this problem too. 
Sometimes i see error look like this:

> "The requested URL can't be reached
> The service might be temporarily down or it may have moved permanently to a new web address.
> Failed to construct 'Response': Invalid statusText"
> 

But in other REST client i can see this: 

> "Status: 403: В доступе отказано".

I think your REST client can't work with cyrillic in status. 

![device-2017-01-10-112331](https://cloud.githubusercontent.com/assets/23550075/21801587/eeca5c6e-d72a-11e6-9a8f-65fd79b8ce62.png)

**Comment by jarrodek** [comment]
@Kivshar 
It might be not related to this issue. However, it might be Chrome issue and I've reported a bug in Chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=680965&can=1&q=Response%20statusText&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by jarrodek** [comment]
@TheoSabattie 
Can you see any error in the logger? It either means that there's an error with the app or the app don't receive the response (due to a server error?).
