### ISSUE TITLE
Error for DELETE request

### ISSUE THREAD

**Issue by angelynzhou** [jarrodek/ChromeRestClient#421]
Your description here

With the new version of ARC, whenever I do a DELETE request, I always got following error although the request did get sent to my http server and my server handled it fine.

"There was an error during the request. "
"request.headers.get is not a function"

With previous browser version, I never got such error with my DELETE request. The same DELETE requests always worked fine.

## Expected outcome
What should happen?

I shouldn't see such error. My same DELETE requests have worked fine under yesterday - I got the new ARC version.

## Actual outcome
What happened?

## Versions
App: 6.1.10.93-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. just issue a DELETE request 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Did you provided anything in the headers field? I'm not sure where to start with. I've tested it for DELETE method and it is working.

**Comment by angelynzhou** [comment]
Hi Jarrodek, it doesn't matter. I have two DELETE requests. One has no header nor payload, I got the error. The other has header content-type as applicaton/json and payload has the json body. I got the same two error messages. It's really bizarre. It always happens for me.

**Comment by angelynzhou** [comment]
Hi Jarrodek, it doesn't matter. I have two DELETE requests. One has no header nor payload, I got the error. The other has header content-type as applicaton/json and payload has the json body. I got the same two error messages. It's really bizarre. It always happens for me.

See the screen shot

[cid:image001.jpg@01D18F2D.2A766EC0]

**Comment by jarrodek** [comment]
I found a cause. It's very rare case actually. It's a bug in socket-fetch library causing an error when the server do not return any header. Usually there are some. It can be fixed quickly. I've created an issue there [issue #3](https://github.com/jarrodek/socket-fetch/issues/3).

**Comment by angelynzhou** [comment]
Great and thanks so much!  You’re right that in our case, we don’t return any header back when we do DELETE.

**Comment by angelynzhou** [comment]
Hi I also have a question. Is there an ARC user group that I could subscribe to? I would love to get updated on coming updates/releases or user experience/tips. I’m currently not in any ARC email list or group. It would really help me. Thanks!

From: Quan Zhou
Sent: Tuesday, April 05, 2016 12:37 PM
To: jarrodek/ChromeRestClient <reply@reply.github.com>; jarrodek/ChromeRestClient <ChromeRestClient@noreply.github.com>
Subject: RE: [jarrodek/ChromeRestClient] Error for DELETE request (#421)

Great and thanks so much!  You’re right that in our case, we don’t return any header back when we do DELETE.

**Comment by jarrodek** [comment]
Sure, there is a beta testers group.
Join the group: https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel
to be able to install beta channel: https://chrome.google.com/webstore/detail/advanced-rest-client-beta/epgngalmiadbjnoompchcohonhidjanm

Betas are pre-release versions. I test them with others that are already in the groups and listen for feedback. There's always a time to fix something before the release.

But there is another channel if you are interested in. It's a dev channel released once every feature is changed / added (meaning the "feature" branch is merged into the develop branch). It's unstable and should not be used in production. The group is here: https://groups.google.com/forum/#!forum/advanced-rest-client-dev-channel

**Comment by angelynzhou** [comment]
Thanks! Will I be able to get the fix for the DELETE issue soon?  I see you already committed the fix. Thanks.
