### ISSUE TITLE
Www-Authenticate: Basic realm="REST API"

### ISSUE THREAD

**Issue by smallshi** [jarrodek/ChromeRestClient#422]
Hello,
As the username and password for a system indicated restfull with http authentication api ? similiar to curl
   curl_setopt ( $ curl, CURLOPT_USERPWD , " $ user : $ pass" ) ;

**Comment by jarrodek** [comment]
Not sure what you mean.

If you have basic authorization on server side you must pass an "Authorization" header where value is "Basic " + base64 of (username + ":" + password).
In the headers form you have a constructor for auth headers that you can use.

**Comment by smallshi** [comment]
Hello
Is exactly what you mention me , thank you very much
