### ISSUE TITLE
200 Success fetches no Response

### ISSUE THREAD

**Issue by venupendiyala** [jarrodek/ChromeRestClient#426]
![200_case](https://cloud.githubusercontent.com/assets/18294494/14296980/78b1a8dc-fb31-11e5-8ba0-0dd26fa28801.png)
Your description here:
When you try to validate a rest endpoint 
Get /URL 
Post /URL

## Expected outcome
Should get response code 200 along with the contents in body

## Actual outcome
Don't get back any response just keeps trying and hangs.
When i pass some incorrect values get the correct error code only issue happens for 200

## Versions
App: 6.1.10.93-stable
Chrome: 49.0.2623.87
Platform: Windows (7)

## Steps to reproduce
1. Try any URL with successful scenario
2. Perform Get or POST operation and expect to get 200
3.

**Comment by jarrodek** [comment]
Are you sure that the server responded with any data?
Can you add "Connection: close" to the headers list? Just to check how it will behave with this endpoint.

Thanks.

**Comment by venupendiyala** [comment]
Yes the server is responding correctly on the Firefox rest client and also old version of Rest client. My chrome rest client got updated today only and it stopped working.

**Comment by jarrodek** [comment]
Do you know if the response is compressed? There was an issue causing the app to crash when compression was enabled.
Also, please, join the beta testers group https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel and instal beta channel (https://chrome.google.com/webstore/detail/advanced-rest-client-beta/epgngalmiadbjnoompchcohonhidjanm) and test this request again with this app. I just updated it on Chrome Web Store with several bug fixes but I need to test it with others before I hotfix current release.

**Comment by jarrodek** [comment]
Can issue author can confirm that the bug do not exists in current stable version?

**Comment by vvoytovych** [comment]
Advanced REST client 7.7.26.168-stable still has this issue.

In logs I see the following:

`Received headers list Date: Tue, 19 Apr 2016 09:42:41 GMT
Location: http://my.domain.com/management/v1/queries/815/versions/29
Content-Type: application/json
Content-Length: 0 {"Date":"Tue, 19 Apr 2016 09:42:41 GMT","Location":"http://my.domain.com/management/v1/queries/815/versions/29","Content-Type":"application/json","Content-Length":"0"}
at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)
at SocketFetch._parseHeaders (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25201:10)
at SocketFetch._processHeaders (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24938:10)
at SocketFetch._processSocketMessage (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24879:19)
at SocketFetch.readSocketData (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24822:14)
at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
at EventImpl.dispatch_ (extensions::event_bindings:371:35)
at dispatchArgs (extensions::event_bindings:243:26)`

**Comment by jarrodek** [comment]
The app is not logging status code in this case. Can you please check status code of the response?

**Comment by vvoytovych** [comment]
It's 200.

**Comment by vvoytovych** [comment]
GET works fine for me. Having issues with POST only.

**Comment by jarrodek** [comment]
Thanks for an issue report.
I see now. There is an issue with the response processing. The response size is zero (0) but the app was trying to get the response anyway causing an error in the response module. 
It will be fixed.

**Comment by jarrodek** [comment]
This issue was fixed in previous update.
