### ISSUE TITLE
can't send mutlipart/mixed with boundary information

### ISSUE THREAD

**Issue by x2764tech** [jarrodek/ChromeRestClient#436]
I'm trying to send a Post request with the following header:

`Content-Type: multipart/mixed; boundary="batch_357647d1-a6b5-4e6a-aa73-edfc88d8866e"`

## Expected outcome
Content-type header should be set to:

`Content-Type: multipart/mixed; boundary="batch_357647d1-a6b5-4e6a-aa73-edfc88d8866e"`

## Actual outcome
Content-type header was set to

`Content-Type: multipart/mixed`

## Versions
App: 6.1.10.93-stable
Chrome: 49.0.2623.110
Platform: Windows (8.1)

## Steps to reproduce
1. Change content type to multipart/mixed
2. Either paste or try to type the `; boundary' parts
3. Content-type gets reset to `Content-Type: multipart/mixed`

**Comment by jarrodek** [comment]
Are you referring to removing a `; boundary="batch_357647d1-a6b5-4e6a-aa73-edfc88d8866e"` part from the headers list? It happened to me when I tried to reproduce the issue. 

When I finally set the header the request was sent with success. Anyway there is a bug but can you tell if your issue report is about the transport or the headers editor?

**Comment by x2764tech** [comment]
Yeah, sorry, it's about the editor

**Comment by jarrodek** [comment]
OK, Thanks for the info. I'll try to fix it ASAP and release the update.
