### ISSUE TITLE
manage projects

### ISSUE THREAD

**Issue by mmoussawi** [jarrodek/ChromeRestClient#437]
i cannot manage my project change name , each time the system creating new project even if the project with same name , I cannot move request from one project to another , I cannot delete projects manage project 

## Expected outcome
to be able to manage project and request in projects 

## Actual outcome
new project created with same name 

## Versions
App: 6.1.10.93-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3. 
![capture3](https://cloud.githubusercontent.com/assets/18330660/14353867/463c3f7e-fcdb-11e5-9168-6c54ba75143b.JPG)

**Comment by jarrodek** [comment]
It is fixed in current beta. Stable will be updated very soon.
