### ISSUE TITLE
HTTP HEAD speed too long time 

### ISSUE THREAD

**Issue by YueminJi** [jarrodek/ChromeRestClient#440]
Your description here
when I HTTP HEAD something ,it will speed me too many time.
then I use wireshark find chrome rev response,but ARC didnot display response(such as  response header).after 30s later,chrome send tcp FIN ,now ARC display  response header.
## Expected outcome
What should happen?
use HTTP HEAD 
## Actual outcome
What happened?
speed too many time.
## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.87
Platform: Windows (7)

## Steps to reproduce
1. input some url,such as www.google.com  .then use HTTP HEAD 
2. click send
3. you will find

**Comment by jarrodek** [comment]
This looks like an error in [socket-fetch](https://github.com/jarrodek/socket-fetch) library. I'll put it on an issue list there. This will be an [issue #4](https://github.com/jarrodek/socket-fetch/issues/4)
