### ISSUE TITLE
Can no longer verify cert verification by browsing and accepting untrusted certs through Chrome. 

### ISSUE THREAD

**Issue by nos4a2n** [jarrodek/ChromeRestClient#441]
Can no longer verify cert verification by browsing and accepting untrusted certs through Chrome. 

## Expected outcome
POSTs to untrusted certs should work once accepted through Chrome.

## Actual outcome
Error thrown: ERR_CERT_AUTHORITY_INVALID

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Make a POST request to a untrusted site (test environmet).

**Comment by jarrodek** [comment]
As long as the certificate is installed in the system it will use it. Try instructions from http://superuser.com/questions/830506/self-signed-certificate-is-not-appearing-in-chrome-after-importing and check again. Can you please test it and say if it worked?

**Comment by alexscottrhodes** [comment]
Same issue here, but we develop by switching between a live server and a VM, so Chrome won't even allow the use of the self signed cert the VM server passes. We used to use the same process, visit a page through the browser, accept the bad cert, then it would work as expected. I think it would be a very useful feature to optionally allow requests against invalid certs.

**Comment by jarrodek** [comment]
I see that the solution might be allowing to choose between socket transport and XHR. It's less flexible (there are ssome limitations for setting up headers in request / response) but it works with the certificates.
That would be quick fix.
Another is is to implement cert storage in the app so it would use certificates and negotiate connection by it's own. But it will take longer to implement. And it's less error proof.

**Comment by jarrodek** [comment]
I'm merging it into #432
