### ISSUE TITLE
modal option by default

### ISSUE THREAD

**Issue by ipedrazas** [jarrodek/ChromeRestClient#442]
Not sure why, but this is less than ideal. I mean, come on, at least give the option of running a non-modal window!

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.75
Platform: Linux (-)

## Steps to reproduce
1. Start ARC
2. cry...
3.

**Comment by jarrodek** [comment]
Can't do anything about it.
Chrome deprecated old type of apps (ARC was the old type) and support for this apps has been removed from Chrome Web Store. Eventually it will be removed from Chrome. Every author is obligated to update their apps. There's really nothing I can do about it.
