### ISSUE TITLE
Make relative redirects work correctly

### ISSUE THREAD

**Issue by NichUK** [jarrodek/ChromeRestClient#443]
I sometimes use the RestClient to simulate POSTs to websites if I'm trying to test with complex forms or payloads. When the client receives a relative redirect, I get a "Not Resolved" error, whereas if the full URL is given the redirect works.

**Comment by jarrodek** [comment]
Thank you for an issue report. 
I've created an [issue report](https://github.com/jarrodek/socket-fetch/issues/5) in the library that is used as the transport. It should be fixed soon.

**Comment by jarrodek** [comment]
It is fixed in beta now. There was an issue with build script that put wrong path to a script in the  manifest file. I've fixed and now publishing hotfixes.

**Comment by NichUK** [comment]
Thank you!
