### ISSUE TITLE
New version doesn't work behind a proxy

### ISSUE THREAD

**Issue by nicolasgelly** [jarrodek/ChromeRestClient#444]
Since the update 6.15.15.114-stable i cannot use the extension.
I got "err::ERR_NAME_NOT_RESOLVED".

I am behind a proxy

**Comment by jarrodek** [comment]
It looks like there is a bug in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=172285
I need time to investigate possibilities and propose a solution.
