### ISSUE TITLE
I can't windows authentication

### ISSUE THREAD

**Issue by lezanaja** [jarrodek/ChromeRestClient#446]
I can't windows authentication but Old version can do it.

## Expected outcome 
200 - Ok 

## Actual outcome
What happened?
401 - Unauthorized: Access is denied due to invalid credentials.
## Versions
App: 6.15.15.114-stable
Chrome: 50.0.2661.66
Platform: Windows (8.1)

## Steps to reproduce
1. windows authentication by chrome
2. Send request by advanced REST client
3.

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
I'm not sur what you mean by Windows authentication. You mean domain login? Or you referring to basic authentication?

**Comment by jarrodek** [comment]
Is this related to #453?

**Comment by jarrodek** [comment]
NTLM authentication is fixed in the dev channel.
