### ISSUE TITLE
I can't find text

### ISSUE THREAD

**Issue by againsley** [jarrodek/ChromeRestClient#447]
Why can't I find text in ARC window? That's a pretty huge flaw. Also not just operating in a tab like a normal web app is silly. Don't break reasonable UX expectations. You're 'fixing' things that aren't broken. This is very frustrating.

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Duplicsate of #429 
As for switching to new Chrome apps - it has to be  done. Old type of apps are deprecated and not even available to upload in Chrome. Authors was forced to upgrade their apps.
