### ISSUE TITLE
SSL certificates not being shared with Chrome

### ISSUE THREAD

**Issue by jmireles** [jarrodek/ChromeRestClient#448]
I'm trying to hit an SSL url but keep getting 

## Expected outcome
I'm expecting SSL to be configurable or shareable with chrome

## Actual outcome
![arc-error](https://cloud.githubusercontent.com/assets/3086590/14396416/0af86e2a-fd9d-11e5-829b-a01c37d6979c.jpg)

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Add an https url
2. submit request

**Comment by jarrodek** [comment]
Duplicate of #432

**Comment by jarrodek** [comment]
Merging it into one thread becasuse it looks like it is a general issue with certificates.
