### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by mluvw47** [jarrodek/ChromeRestClient#451]
Your description here
I have many requests that I saved from previous version and I got update the ARC today and try to use all those query. All of them get net::ERR_CERT_AUTHORITY_INVALID

I even try to use a simple request, still getting this error. None of my request works since I update.

## Expected outcome
What should happen?
It supposed to get the response back. 

## Actual outcome
What happened?
net::ERR_CERT_AUTHORITY_INVALID

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. create a request from previous version
2. Send the request. 
3.

**Comment by mluvw47** [comment]
please fix it

**Comment by jarrodek** [comment]
Dupliocate of #432
