### ISSUE TITLE
New app has many issues

### ISSUE THREAD

**Issue by sanjayrnath** [jarrodek/ChromeRestClient#454]
I find the new updated app with many bugs. Suddenly while using POST method only RAW PAYLOAD is seen and post form is missing and i cant type any POST parameters. And the request is not sending any POST parameters. 
The previous version was working quite well. Please fix this issue or provide some guidance to clear it out. 

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.87
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Is there a proper content-type header set for the request? I'm assuming that you want to send regular form data. In this case you suld use 'application/x-www-form-urlencoded' content type header.
Also you can use 'multipart/form-data' if you want to send files wioth the same request.
Is that the reasone of the issue?

**Comment by jarrodek** [comment]
I read you issue again and I can see that you are missing the form for payload. It will be visible when you set 'application/x-www-form-urlencoded' content type header. It behaves this way because this form is only relevant to this king of the request.
