### ISSUE TITLE
New implementation causes CHROME CORS functionality

### ISSUE THREAD

**Issue by ariskartalos** [jarrodek/ChromeRestClient#455]
It seems that with new implementation under javascript development, CHROME automatically generates CORS OPTION requests to API Servers resulting in unauthorized access in case servers do not support OPTION method (actual message: 
![image](https://cloud.githubusercontent.com/assets/13849696/14425689/c4b07802-fff1-11e5-8ab2-300bd470ac15.png)

With old version under java development, there was no such problem.
With this problem we can not check API calls on servers not supporting OPTION method (for CORS support) and there is no way out of it.
Supplied API example is of real server problem and can be used for debugging. If this example API is provided with previous ARC version there was no problem and an answer was provided by server.

**Comment by jarrodek** [comment]
Duplicate (ish) of #432. I'm putting there all cert related issues.
