### ISSUE TITLE
ssl error cannot be bypassed or ignored in New arc client

### ISSUE THREAD

**Issue by user23498723452** [jarrodek/ChromeRestClient#459]
if I try to access an https url with an invalid ssl name, i cannot ignore the error.  this previously was not a roadblock.

## Expected outcome
the app should provide an option to ignore ssl errors

## Actual outcome
error received:
net::ERR_CERT_COMMON_NAME_INVALID

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1.  access a url  with a different dba name than the cert.
2.  watch it fail
3.  don't profit?

**Comment by jarrodek** [comment]
Merging into #432
