### ISSUE TITLE
No way to use in a regular tab

### ISSUE THREAD

**Issue by arasmus8** [jarrodek/ChromeRestClient#462]
The app always opens in a popup window, no way to keep it in a regular tab.

## Expected outcome
App opens in tab in chrome

## Actual outcome
App opens in popup window

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Open app
2. Search settings for 10 minutes looking for a way to change the annoying default behavior
3. Cry manly tears of frustration

**Comment by jarrodek** [comment]
It can't be done. App's are separated from the Chrome. Old (and deprecated) apps was a hybrid between extensions and apps so they were allowed to open it in tabs. But because they are no longer supported by Chrome Web Store and eventually by Chrome it can't be fixed.
