### ISSUE TITLE
New version doesn't show json prased response

### ISSUE THREAD

**Issue by jackgreentemp** [jarrodek/ChromeRestClient#467]
the old version has a tab to show json prased response, where can get the prased response in the new version?

**Comment by jarrodek** [comment]
It's still there. What do you see instead? And what's the response content type?

**Comment by jackgreentemp** [comment]
Thanks for your reply.
I tested with a URL which is http://phr191.cmri.cn/pregnancy_yjy/question/queryHistoryQuestion.do?uuid=2da82a9a-575e-4c0c-b746-3a6764e93094&userphone=13810870564&password=c4ca4238a0b923820dcc509a6f75849b&apptype=android

**Comment by jackgreentemp** [comment]
sorry, I found the content-type of the response is "text/html;charset=utf-8", does the new version show the json tab only if the content-type is "text/json"?

**Comment by jarrodek** [comment]
That's right. Old version actually did the same thing. The app can't afford to parse content using JSON parser, XML parser and any other parser to determine it's type because it will take too long to determine it's type. JSON type response should have proper content type set anyway.
