### ISSUE TITLE
Show more of the url on the history view

### ISSUE THREAD

**Issue by timgaunt** [jarrodek/ChromeRestClient#470]
At the moment the url gets truncated very early when the most important part is often the end i.e. I often just get the domain, the time/method are useful but shouldn't take as much room up as they do. 

It would be better reducing the column width of the checkbox, time and method so the url can fit more onto the screen -or at lest show it all on hover.

**Comment by jarrodek** [comment]
You can double click on an item.  There is a similar issue #468

**Comment by jarrodek** [comment]
This is fixed already. The list has been redesigned.
