### ISSUE TITLE
No answer

### ISSUE THREAD

**Issue by Pabloces** [jarrodek/ChromeRestClient#471]
Some services that have only a 200 code and no detail as answer, remain looping and do not get the response. 

## Expected outcome

Should recibe a 200.

## Actual outcome
keeps on working. 

![image](https://cloud.githubusercontent.com/assets/13266920/14473474/ab425d9e-00ce-11e6-8d46-4787408aada7.png)

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

## Steps to reproduce
1.
2. 
3.

**Comment by jarrodek** [comment]
The same issue as #474

**Comment by jarrodek** [comment]
This is fixed in develop branch. Soon it will be released as beta.

**Comment by Pabloces** [comment]
Thanks Good Job


*Pablo Ces*

Business Consultant Partner

*flexibility + ideas*

(+54911) 4022-1303

www.flexibility.com.ar


2016-04-15 11:04 GMT-03:00 Paweł Psztyć <notifications@github.com>:
