### ISSUE TITLE
New window doesn't share session. 

### ISSUE THREAD

**Issue by rtugeek** [jarrodek/ChromeRestClient#473]
Seems the new window doesn't share session with chrome tabs. Is there any way to solve this issue?

**Comment by jarrodek** [comment]
Chrome apps do not share the same session with Chrome. However I may be able to create an extension to share cookie data between the app and chrome. Unfortunately it will require to install additional extension. I'll explore this topic.

**Comment by velo** [comment]
This is a major problem for me as well

Is there a way to get it as tab again?

**Comment by jarrodek** [comment]
There's no point of doing it since the chrome legacy apps (previous version) are deprecated in chrome and already blocked in Chrome Web Store.

**Comment by velo** [comment]
If i knew I wouldn't have upgrade it... =(

**Comment by jarrodek** [comment]
Duplicate of #472
