### ISSUE TITLE
hangs on DELETE

### ISSUE THREAD

**Issue by mk229797** [jarrodek/ChromeRestClient#474]
Your description here
Doina a DELETE - server gives 200 or 204 - but the new plugin just keeps reading response

## Expected outcome
just show 200/204 status and stop reading repsonse

## Actual outcome
hanging around

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. CALL delete on http://xxx/app/rest/builds/id:yyy
2. with header authorization: Basic zzzzz
3. with header Content-Type: text/plain (not required - dows nto work eighter way)

**Comment by jarrodek** [comment]
Hi,

Thanks for an issue report. I've created an [issue report](https://github.com/jarrodek/socket-fetch/issues/6) in the library that supports sockets in the app. 

Before the update I can only suggest adding `Connection: close` header to the request. Then the connection will be closed and the library report a success.
