### ISSUE TITLE
Header Parameter get changed

### ISSUE THREAD

**Issue by HEMKUMTE** [jarrodek/ChromeRestClient#480]
Header parameter get changed to lower case
Example  : 
_DeviceId: DeviceId_ios
DeviceType: DeviceType_ ios_v1
Language: en
X-IMG-AUTH: test
_

Changed to  

_ [deviceid] => DeviceId_ios
 [devicetype] => DeviceType_ ios_v1
 [language] => en
 [x-img-auth] => test

_
## Expected outcome

It should not changed

## Actual outcome
All the header parameters changed to lowercase

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1.  set any header with  "DeviceType: <value>"
2.  Call GET / POST
3. Print HEADER  value

**Comment by jarrodek** [comment]
This works as intended. 
According to the HTTP spec headers are **case insensitive**. The app is using build-in JavaScript [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) object that handles headers in the request and the response and this object is transforming headers. 
If you believe it is abnormal behaviour you can join a discussion for [the spec](https://fetch.spec.whatwg.org/#headers-class).

**Comment by HEMKUMTE** [comment]
Got it, Thanks
