### ISSUE TITLE
Not an issue, i wanted some assistance

### ISSUE THREAD

**Issue by akshansh04** [jarrodek/ChromeRestClient#482]
Hey, 
I am writing not regarding any issue but for a help and I did not get any better place to start the thread. I will give you some background of the scenario I want to ask you about:
I send some data in chinese/japanese etc through an upload API using your rest client. And similarly I download the data through a different API, but when i download it sends my an Array buffer. If i check the network call, it shows me some random values being returned from the API but when I check it on you response div, it shows me the correct data, even though the network call has some random values in your browser's network too. I wanted to ask how are you converting the data being returned from the network to the correct format? 
I will share how i was doing:
var data:string = String.FromCharCode.apply(null, new UInt8Array(arrayBufferReturnedFromAPI));

This works fine for english but while testing it for chinese/japanese this does not work. But as i could see you dont have any issue in your scenario even if network returns some random values. Can you please share me how you converted it? It would be of great help. Thanks in advance. 

I have share the screenshots of what i am talking about, The network has some value which you converted into correct response in your code-mirror div.

![askresponse](https://cloud.githubusercontent.com/assets/18476237/14551198/7f790e76-02ed-11e6-91a6-1280d5c444d6.PNG)
![asknetwork](https://cloud.githubusercontent.com/assets/18476237/14551199/7fa3f7e4-02ed-11e6-81f6-b15fd293aecf.PNG)

**Comment by jarrodek** [comment]
I can see that you are still using old version of the app. The transport is based on XHR object there. It converts data for the app. So all I do is to take data from `XHR.response` property and displays it. 

However new version of the app is using pure sockets. It always receive bytes stream. I convert it to string using javascript's String class functions. You can see how it works in [socket-fetch](https://github.com/jarrodek/socket-fetch/blob/master/app.fetch.js) library.

**Comment by akshansh04** [comment]
I am also working with byte stream only but the issue is that data returned is not in the expected form. I am also using String class functions to convert array buffer to string with the code snippet I wrote above in my issue.
Is there anything else I might be missing? as it looks like the same thing worked for you but not working for me.

Thanks in advance!

**Comment by jarrodek** [comment]
What language is that?:
```
var data:string = String.FromCharCode.apply(null, new UInt8Array(arrayBufferReturnedFromAPI));
```
See a covert function here: https://github.com/jarrodek/socket-fetch/blob/master/app.fetch.js#L1407 (arrayBufferToString). I think you are looking for something like this.

**Comment by akshansh04** [comment]
Language i am using is typescript and i think the code you sent me is the
same i wrote, except that you are using for loop and i am using .apply
method directly over the buffer. I will try out the for loop and come back
to you by tomorrow. Thanks.

**Comment by jarrodek** [comment]
Sorry, it is morning for me :)
Basically this is the same function call. 

It doesn't actually looks like an issue with converting ArrayBuffer to string. At least if you use UTF-8. The screenshot you attached, it looks like it is an compressed data like using gzip or deflate.
XHR decompress data automatically for you. I'm using Zlib library to decompress data if the response is compressed.
Is it the issue in your case?

**Comment by akshansh04** [comment]
If that is the case (compressed data coming from API response), how did it
work fine for English text? why only chinese, japanese?

**Comment by akshansh04** [comment]
Hey, Any updates on this ??

**Comment by jarrodek** [comment]
This is not an issue so I'm closing it.
