### ISSUE TITLE
ARC hangs indefinitely on a 204 reponse

### ISSUE THREAD

**Issue by KTMNealio** [jarrodek/ChromeRestClient#483]
Your description here

## Expected outcome
It should return from the call and indicate the status was 204 "no content"

## Actual outcome
The "activity" bar by the send button "spins" indefinitely

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Linux (-)

## Steps to reproduce
1. set URL to a web resource/endpoint that returns a 204 response
2. get method to "GET"
3. hit SEND

**Comment by jarrodek** [comment]
This is fixed in develop branch and soon will be released in beta channel.
It is related to [issues #6](https://github.com/jarrodek/socket-fetch/issues/6).
