### ISSUE TITLE
Project Endpoints List is not showing correctly

### ISSUE THREAD

**Issue by WajdyEssam** [jarrodek/ChromeRestClient#486]
The endpoint APIs (Already Registered APIs) is not clearly displayed 

see this image to know the issue:
[https://dl.dropboxusercontent.com/u/63101982/RestBug.png](url)

## Expected outcome
the list should be opened and I should see all the method names

the vertical scrolling is working fine, but the horizontal scrolling is not, and now I can't see the methods name
## Actual outcome
When you have list of predefined APIs added and you open that list, it will not be displayed correctly

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. Add Project Name
2. Add any numbers of APIs
3. the list will not be displayed correctly.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
It was fixed in latest update.
