### ISSUE TITLE
Chrome sessions are not passed to the socket

### ISSUE THREAD

**Issue by jakubleska** [jarrodek/ChromeRestClient#487]
Our page have complex login procedure, but whole login process end, with some cookies set up. When XHR was used this cookies was send automatically from chrome(f.e. when page was logged-in from another tab.). Now cookies are not send through socket implementation (It's not fault of ARC,
but it will great if there will be option to select between XHR and socket). Without this I couldn't use ARC.

## Expected outcome
After request to api response should return.

## Actual outcome
Every request ends with unauthorized response.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Linux (-)

## Steps to reproduce
1. ----

**Comment by jarrodek** [comment]
XHR will not help here either. The whole networking is separated from Chrome and it doesn't matter which transport will you use.
I'm considering different approaches here and I'm planing to implement less invasive to the users and most flexible for usage.

**Comment by jakubleska** [comment]
OK, before last update this was working so I think that the implementation using socket break it. 

I think that biggest problem now is that cookies are not set between request. I know that is much cleaner without  automatic cookies. But now I must add cookie by hand after each request to server (because server response new cookie after every request ... some security reasons not my idea :) ) and it make usage of ARC really painful for me.

So if there will be some option to use cookies from previous responses this will be really awesome.

**Comment by jarrodek** [comment]
Naturally it will be. 
Here is my options:

1. Create additional extension so it will act as a proxy between the app and Chromes cookie storage
Pros:
* access to existing session cookies and ability to use it when making a request
* ability to update cookies in Chrome browser when the response ask for it
* user can log-in on a website and obtain the cookie and use it in app 

Cons:
* additional extension to be installed
* additional (and possible invasive) permission to cookie storage
* additional code base to support this functionality 
* more time needed to make a request (first it will need to ask the extension if there are cookies to send with the request)
* more complicated UI - there should be an option to switch off this behaviour 

2. Create a simple mechanism to store and set cookies in the app
Pros:
* less complicated than creating a proxy extension
* relatively easy to implement
* simply mimics chrome cookie store behaviour
* much faster work time (querying the database vs querying external extension)
* more secure - the app do not have access to the cookie storage

Cons:
* no access to Chromes cookie storage and therefore the app can't obtain cookies set in session in the browser
* users need to make a request to the endpoint where cookies are set.

In one hand I understand that some people are using login form on a web page and then are using ARC to test the API but for many other users having cookie storage access is very invasive and potentially risky. I'm not a fan of extending permissions for the app and actually I'm thinking about lowering it. Therefore my best guess is that I will go with option 2.

**Comment by claytonfbell** [comment]
Agreed, would really help to restore ability to share the session cookie with the browser.

Or if there is an easy way to set and retain a session cookie.

**Comment by nganbread** [comment]
Also would love being able to set the cookies via the/a browser. It makes its extremely useful when you have a complex login form or no login api. 

An  interim solution for those of us that absolutely rely on this type of functionality is to release the old app as a new chromecast extension

**Comment by ezeswci** [comment]
The better solution i found was to use othe app DHC is really good

**Comment by jjaimon** [comment]
Same problem here. We have a complex sequence where requests are sent after a login.  Previous implementation used to pass PHPSESSID automatically.  It doesn't happen anymore.  It will be good to have an option (settings) where we can select cookies from the previous response.  This approach will be more flexible if there are multiple cookies returned from the previous request.

**Comment by JohnnyGoods** [comment]
Yeah, unfortunately the move to app fully broken ARC for my usage, which is often to issue api requests against an application leveraging my existing browser login state.

**Comment by jarrodek** [comment]
Right now I'm testing internal cookie storage within the app. It still don't have access to Chrome's cookie storage and because there is no API for that there will be none (see comment no 3).
This will be pushed as a hotfix in coming days.
