### ISSUE TITLE
Prompt to select SSL certificate not working in packaged app version

### ISSUE THREAD

**Issue by zshall** [jarrodek/ChromeRestClient#488]
I'm receiving a `net::ERR_CLIENT_AUTH_CERT_NEEDED` error when trying to run a request that requires a custom SSL certificate, when in the non-packaged app I'd be asked to select one.

## Expected outcome
I attempt to connect to a server that requires custom SSL details and it Chrome prompts me to select a certificate I've installed like so:

![image](https://cloud.githubusercontent.com/assets/175742/14605522/edd1d5e6-0546-11e6-8384-8a725d650b9f.png)

## Actual outcome
I attempt to connect to the server and I get this error without being asked to select my certificate:

![image](https://cloud.githubusercontent.com/assets/175742/14605568/22e40e8e-0547-11e6-80f2-625cb0e9541a.png)

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

## Steps to reproduce
1. Install an SSL certificate on your machine that you need to connect to a server
2. Try a request to that server using `https`

Perhaps [Chrome's page on certificateProviders](https://developer.chrome.com/extensions/certificateProvider) has info that can help.

This worked on the old version, so maybe it's a problem with being a packaged app?

**Comment by jarrodek** [comment]
> Important: This API works only on Chrome OS.

The app do not have access to certificates storage. Either you can install certificate in Chrome (in settings) or - if the certificate is somewhat invalid - you can install valid certificate on your development machine. There are free certificates services like [letsencrypt.org](https://letsencrypt.org/) that provides free and valid certificates.
