### ISSUE TITLE
HTTPS websites with invalid certificates

### ISSUE THREAD

**Issue by to0x97** [jarrodek/ChromeRestClient#489]
Websites with invalid certificates don't work anymore. It's annoying with debug environements...

## Expected outcome
Worked on last version

## Actual outcome
Certificate is invalid for given domain

There's no way of fixing this issue with the app. Certificate presented to the browser has different CN (common name field) than the domain of the request.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

**Comment by jarrodek** [comment]
Invalid certificates won't work. Please, update certificate CN and set proper domain name or install certificate using services like letsencrypt.org

**Comment by to0x97** [comment]
Again, it's a debug env... But it's OK i will not use this chrome extension anymore.
Thank you for such comprehensive reply!
