### ISSUE TITLE
HTTP headers case sensitivity - headers not present on a server

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#491]
I just want to pin this issue so any other issue in related topic can be referenced to it.

For any issues with headers not being read on a server side.

**Headers are case insensitive** and both client and server apps should be able to handle it properly.

That being said. The issue is with JavaScript's [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers). The app is using this object to pass the headers to the request and to report the response. This object transforms the headers to lower case. 
If you have issues with headers case-sensitivity you can start a discussion on W3C specs pages and in Chrome's crbug.com.

**Comment by antidamage** [comment]
Headers are in fact case sensitive in many languages on the receiving end of the request, PHP being one of them:

    $request->GameName

It just makes sense to preserve the header case, as plenty of REST clients do this. Find a new Header object maybe?

**Comment by jarrodek** [comment]
How some languages implement this is irrelevant and if they assume case sensitivity it is architectural problem and should be reported to the maintainers of the language. HTTP spec says how headers are processed. As mentioned in the explanation, the app is using Headers object which is a standard JS object and this object processes headers. The app itself does nothing with case sensitivity. But remember that [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) (a replacement for XHR) uses the same Headers object and the problem persist in any web application, even if ARC would do this differently. 

The best way to walk around the issue is to install ARC desktop client. It uses different transport library that does not relay on Headers object. You can install it from install.advancedrestclient.com. Note that you will have to manually move your data from Chrome client to desktop client. 

Other options are 1) to file an issue report to the Fetch API spec or 2) the same for HTTP protocol spec and explain them that headers has to be case sensitive.

Chrome client currently cannot be updated anyway as it would block installation of the app on all platforms except Chrome OS and I am not ready to do this just yet. So development of Chrome client is postponed. Desktop client is however in active development.
