### ISSUE TITLE
Relative redirects not working when using a custom port 

### ISSUE THREAD

**Issue by zeunknown** [jarrodek/ChromeRestClient#492]
Hello ,
my application use  the port 8080 instead of the default 80 port 
so , inside the request url field i use an url that looks like this : 

`http://localhost:8080/application/service` 

but after the last update , i think that the port number is not taken into account anymore 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Linux (-)

**Comment by jarrodek** [comment]
Stable version is working in this case:
![image](https://cloud.githubusercontent.com/assets/3320020/14609764/1ee166c4-0583-11e6-85c3-ed2749215797.png)

What is happening? Where's the issue?

**Comment by zeunknown** [comment]
![Imgur](http://i.imgur.com/z10qE9N.png)

the link i'm trying to use need authentication to work, so the application redirect me to the login page but when the redirect is happening the port is lost

**Comment by jarrodek** [comment]
I can't reproduce the problem. 

In my test case the request started at `http://localhost:8081/relative-redirect` and has been redirected to:
1. /relative-redirect/step-1 (relative redirection)
2. /relative-redirect/step-2
3. /redirect/dest
where it finally got a response.

![image](https://cloud.githubusercontent.com/assets/3320020/14611014/2776806c-0588-11e6-90ce-c945f70a58d5.png)

As you can see in your screenshot the server is redirecting you to the localhost without port number. Either you can use relative redirects or add port number in your server redirection.
