### ISSUE TITLE
Shortcuts on OSX

### ISSUE THREAD

**Issue by klefevre** [jarrodek/ChromeRestClient#493]
Shortcuts on OS X aren't correctly translated.

## Expected outcome
All shortcuts with "CTRL + " should be translate to "⌘ + ". e.g. "CTRL + F" -> "⌘ + F"

## Actual outcome
Nothing happen 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_11_4)

**Comment by jarrodek** [comment]
⌘ + F is actually working. ⌘+S and ⌘+O are not. I'm gonna fix it.

**Comment by klefevre** [comment]
@jarrodek ⌘+F doesn't work for me...

**Comment by jarrodek** [comment]
Oh, sorry. You are right. I've removed it just before stable release because it caused some other issue. All shortcuts need to be implemented correctly on Mac.

**Comment by jarrodek** [comment]
It was a quick fix. It will be included in next release.
