### ISSUE TITLE
Nothing opens correctly anymore

### ISSUE THREAD

**Issue by balkcivil** [jarrodek/ChromeRestClient#495]
Your description here
Go back to the old way of opening the app in the browser tab. It was a better UI and not all the windows, but also its completely buggy as it is now and nothing opens correctly 
## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Please refer to the blog post http://restforchrome.blogspot.co.uk/2016/04/advanced-rest-client-is-not-in-tab.html for more details.
