### ISSUE TITLE
4xx and 5xx errors not handled properly

### ISSUE THREAD

**Issue by ygamelin** [jarrodek/ChromeRestClient#498]
while testing my app, I notice that the ARC doesn't handle 4xx and 5xx http code properly and shows as if the request never gets back from the sever. I have to press the abort button  to stop waiting.

other client do received  and shows 4xx and 5xx code.

**Comment by jarrodek** [comment]
Hi, 
Thank you for issue report.

I can't reproduce the problem.
On which version of the app you are? Both 4xx and 5xx codes responses are passing the tests. There may be some other issue.

**Comment by jarrodek** [comment]
Hi,

Can you provide more details on the issue? Try debug the app to get more logs: https://github.com/jarrodek/ChromeRestClient/wiki/debugging

Thanks

**Comment by ygamelin** [comment]
umm, I'm not able to reproduce either. Dunno what was the issue. I now got the response 40x as expected with proper body.  

Sorry about that.

**Comment by jarrodek** [comment]
It is possible that it was related to some other issue that has been fixed.

I'm closing this issue.
Thanks
