### ISSUE TITLE
Saved request displayed names are too short, while lots of empty space nearby

### ISSUE THREAD

**Issue by toli-belo** [jarrodek/ChromeRestClient#500]
in Saved list the request names are super short, if anyone used this they would know that with various combinations of request the names tend to get longer. 
this is while here is plenty of real estate between columns. 

## Expected outcome
Better use of space and display preferably full request name.

## Actual outcome
Request names are truncated

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

## Steps to reproduce
1. save a request with name such as "WS3-QA V1 Lead-Expanded" 
2. open saved requests

**Comment by jarrodek** [comment]
Just note to myself:

- columns should have dynamically assigned class with "flex" css property
- by default it should be name / url? Url is more important than the name?
- double click on a column right border will assign flex class to this column and remove it (?) from the other column

Then it will work like in most OS' and programs, will be natural and will not require explanation / tutorial.

Another thing to discuss is to add d'n'd for column width. It require more coding time (which is not available now) and it may be more complicated.

**Comment by jarrodek** [comment]
This will be fixed in v8. It's heading to beta channel right now.
