### ISSUE TITLE
Request search criteria reset when going back to "saved"

### ISSUE THREAD

**Issue by toli-belo** [jarrodek/ChromeRestClient#501]
Ideally the request search criteria should "stick" so that if I go back to "Saved" I still see the applicable requests. I would often need to go back and forth and find the right version of the request, and would rather not re-type the search criteria.
## Expected outcome

Search criteria should stick around until reset by user
## Actual outcome

Search criteria is reset when click "Saved"
## Versions

App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)
## Steps to reproduce
1. save a few requests
2. go to "Saved"
3. Type a search criteria in the top bar
4. select a request - click "Open"
5. go back to "Saved"
6. Search criteria seems to have reset (no longer applied)

**Comment by jarrodek** [comment]
This is fixed already. Will be released soon.
