### ISSUE TITLE
Ability to set-up call timeout including infinity 

### ISSUE THREAD

**Issue by mallalli** [jarrodek/ChromeRestClient#502]
Hey,

Plugin version never had issues with sockets being closed. I use rest client to test or debug my applications where the response times could be very large. With the desktop app I see that if it does not get a response in 30 secs I see a socket closed errors. 

How can I set the infinite socket timeout ?

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Call any url which takes more than 30 secs to respond
2. 
3.

**Comment by jarrodek** [comment]
I've changed issue title to be more recognizable.

**Comment by mallalli** [comment]
Yo.. Thnx

**Comment by erfanimani** [comment]
Yeah, this is a pretty big one.. it's unusable for me now since the API's I work with return large datasets that (unfortunately) take a while to load.

**Comment by fernandopg** [comment]
+1 How to solve it?

**Comment by Mart-Bogdan** [comment]
Hello, @jarrodek, When this fix will be uploaded to Chrome Marketplace?

Current version there is Version: 7.7.26.168-stable

P.S. Thanks for fixing it. New UI is great, except this bug.

**Comment by jarrodek** [comment]
@Mart-Bogdan in coming days. I'm testing and still fixing cookie storage and when it's ready I'' publish an update right away.

**Comment by erfanimani** [comment]
Thanks @jarrodek! New UI does look great.

**Comment by andrea-bologna** [comment]
+1
