### ISSUE TITLE
App update - separate window

### ISSUE THREAD

**Issue by dashawk** [jarrodek/ChromeRestClient#510]
I don't really like the latest update

## Expected outcome
Nothing should happen on update. Why did you separate the window in chrome? Its not an application, its a plugin.

## Actual outcome
Nothing should happen on update. Why did you separate the window in chrome? Its not an application, its a plugin.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Thanks for sharing.

Again, old kind of apps are deprecated and support for them has been removed from the store. Authors needed to upgrade their apps to keep them in store.

New apps can't work in tabs and are intentionally separated from Chrome. You can always file a bug report in Chrome issue tracker about that. 
Please, refer to http://restforchrome.blogspot.co.uk/2016/04/advanced-rest-client-is-not-in-tab.html.

**Comment by AdriVanHoudt** [comment]
@jarrodek The only problem I had with this so far is I lost the ability to search in responses, now I have to copy them  over every time.
Would it be an option to add this as a feature? (sorry if this belongs in seperate issue)

**Comment by jarrodek** [comment]
Not sure what you mean @AdriVanHoudt Do you mean ctrl/command + F?

**Comment by AdriVanHoudt** [comment]
jup, can't do that in the separate window now

**Comment by jarrodek** [comment]
If you are using Mac the command is command+s. Anyway this is implemented. Can't you see a search tab when you press ctrl/command+F?

**Comment by AdriVanHoudt** [comment]
cmd+s highlights Socket tab (I can press space to select it then) 
cmd+f does not show a search bar
even in history it does not select the search

**Comment by jarrodek** [comment]
OK, I got it. :)

Search bar is only implemented for response view and as for now it will stay this way (at least until anyone send a PR with fixing it :)

Generally it is working as intended. In sockets panel there is no search functionality. Saved/history list have only icon to click in a top bar. For usability it might be using ctrl+f shortcut for initializing the search in this panel.

**Comment by jarrodek** [comment]
@AdriVanHoudt  But since it is separated issue and this will be eventually closed win "wont-fix" status can you create new issue referencing this one?

**Comment by kszyntar** [comment]
I guess the lack of an option to change the font size change is also a side effect of that? Is there some clever way to get larger fonts in the separate pluging window?

**Comment by jarrodek** [comment]
@kszyntar not that I'm aware of. Theming is not yet supported but it might be in a future.
