### ISSUE TITLE
History navigation - scroll to see request details.

### ISSUE THREAD

**Issue by timomwa** [jarrodek/ChromeRestClient#513]
User unfriendly navigation on the history section.

## Expected outcome
When Inspecting historical request, I just want to single click to view the details of the request (just like old ARC). Now I have to double click.
The details of a request should be visible no matter how long my history list is.

## Actual outcome
I have to double click on the historical requests to view them.
When I have a long history list, after double clicking on the last record, I have to scroll up again just to view the details of the request. Pretty annoying.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

## Steps to reproduce
1. Open Chrome Rest Client

**Comment by jarrodek** [comment]
So it's basically about the details panel not being scrolled with the view?

**Comment by timomwa** [comment]
Yes.
Also, a single click would be preferable when one wants to view  the
historical request

**Comment by jarrodek** [comment]
Thanks for clarification,

Single click is not the best idea. Single clicks are reserved for actions that are clearly visible - like clicking on a link, button, checkbox - and not for behaviours that are unexpected. Opening a details panel is definitely unexpected from user POV so the action should not be associated with primary action (like click). In this case it would be bad UX. 

However I totally agree on that the panel should be scrollable.

Thanks
Pawel
