### ISSUE TITLE
No icon in chrome

### ISSUE THREAD

**Issue by philwu** [jarrodek/ChromeRestClient#518]
I have installed 7.7.26.168-stable and I can see it in the extension page but I can not see it icon button in chrome. 
Is there any setting I should make?

**Comment by jarrodek** [comment]
Please refer to Chrome help: https://support.google.com/chrome_webstore/answer/3060053?hl=en-GB
You also have an tutorial about that in settings.

**Comment by philwu** [comment]
Yes, I can launch it from bookmarks bar and chrome://apps/ 
but what I meant is "Chrome App Launcher on Chromebooks" which is located on the right side of address bar and left side of setting button. Can you guys see it there?

**Comment by jarrodek** [comment]
Thanks for clarification.
Apps can't be opened as extension - from the icon reserved for extensions. This is how the platform works.
