### ISSUE TITLE
Using the OData Filters

### ISSUE THREAD

**Issue by shaungrech** [jarrodek/ChromeRestClient#520]
I have used the ARC to query my OData endpoints in the past. With the latest update the 'Filter' OData method always returns a Bad Request. On other REST Clients, my OData endpoint still works.

http://myodataapi.azurewebsites.net/People?$filter=Name eq 'Shaun'

Thanks
Shaun

**Comment by jarrodek** [comment]
Can you check if encoding the URL helps? Encode options is available in the context menu on left of the URL field.

**Comment by shaungrech** [comment]
That worked thanks 👍
