### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Bharath014** [jarrodek/ChromeRestClient#523]
Hi Team

Am getting 401 unauthorized . Please help with the issue and telll me where to give the credentials. 

Thanks & Regards,
Bharath Govidnaraju

**Comment by puffluna** [comment]
I am getting the same.  I was fine until I took the upgrade yesterday.

**Comment by jarrodek** [comment]
@Bharath014 is this a duplicate of the #517?

**Comment by Bharath014** [comment]
Yes this is the same as 517
