### ISSUE TITLE
Raw response (plain text) '\n' is ignored - no newline occurs

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#529]
Raw response (plain text) '\n' is ignored - no newline occurs

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

**Comment by jarrodek** [comment]
Is this a duplicate of #527?

**Comment by RanGold** [comment]
Not really. New line occurs when wrapping should occur and not when '\n' is present
