### ISSUE TITLE
URL panel do not refresh data when switching requests

### ISSUE THREAD

**Issue by meytal-cs** [jarrodek/ChromeRestClient#532]
I was forced to use the new REST Client version.
The old one worked fine.
Besides one bug of not being able to send JSON headers.
But I dealt with it (used only url-encoded and changed my code accordingly).
But now every time I switch between a saved request, the old request parameters appear and not the saved one.
I have no other choice but move to some other service instead.
Version: 7.7.26.168

**Comment by jarrodek** [comment]
So the issue is basically about URL parameters form is not updating values after switching between requests?

**Comment by meytal-cs** [comment]
Yes, it seems to remember the previous request parameters and the one I'm at and already saved its' parameters before. Maybe it is related to the version upgrade.

**Comment by jarrodek** [comment]
Thanks for clarification.
I took a liberty of changing the subject so it corresponds to the issue.

**Comment by jarrodek** [comment]
This is actually a duplicate of #532
