### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by bcapalbo** [jarrodek/ChromeRestClient#537]
I need to use a lot of proxy configs... Because of that, I frequently use the Proxy SwitchySharp.
On the new version of ARC, I can't use both to work.
When Proxy SwitchySharp is enabled, the Chrome proxy configuration is disabled.

## Expected outcome
The app still working with proxy configured on Proxy SwitchySharp.

## Actual outcome
Connection timed out or ERR_NAME_NOT_RESOLVED.

# Versions
App: 7.7.26.168
Chrome: 49.0.2623.112 (64-bits)

# Steps to reproduce
1. Do a get to remote url behind a proxy configured by Proxy SwitchySharp.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

Proxy settings are available in **Chrome settings**. Apps do not have access to any network settings and relays on Chrome / system's settings.

As per this I'll close it as WAI.
