### ISSUE TITLE
simple get command produces abort / timeout message

### ISSUE THREAD

**Issue by DDoyle022** [jarrodek/ChromeRestClient#540]
I have no clue what it happening.  The simple get command I used to run before this was a desktop app stops working and only returns abort / timeout.

I can go to any browser and copy/paste the command and it runs just fine and runs quickly.  So, nothing is malformed like the help message suggests. It does return a fair amount of data, but like I said, the response is quick.

**Comment by slouc** [comment]
I have the same problem. Request that used to work with old ARC and that works in, say, Postman doesn't work in new ARC. Request is a simple GET with one key-value pair in the header and the response is immediate and very small (one tiny JSON).

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

The request is canceled after 20 secs of no response.
This is duplicate of the #502

**Comment by slouc** [comment]
I wouldn't bet on it being the timeout issue. My request receives an immediate response using other REST clients, and it was the same situation with old ARC.

**Comment by jarrodek** [comment]
@slouc please, do that. And add app logs in when the response is made. It will help debug it. See [debuging section](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) for more details.

**Comment by slouc** [comment]
Found the cause and opened an [issue](https://github.com/jarrodek/ChromeRestClient/issues/560). Please check if it's duplicate, I didn't find anything. Thanks.
