### ISSUE TITLE
Did not like teh new UI... too bad..cant open multiple windows and test 

### ISSUE THREAD

**Issue by nsubramanian84** [jarrodek/ChromeRestClient#543]
Did not like teh new UI... too bad..cant open multiple windows and test 

## Expected outcome
No good UI design... bad..cant open multiple windows and test 

## Actual outcome
.cant open multiple windows and test 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
New window open button is in left nav panel: 
![image](https://cloud.githubusercontent.com/assets/3320020/14673121/ded945f2-06f3-11e6-8395-107432e4e23d.png)

I'll close this issue as WAI.
