### ISSUE TITLE
lost the ability to preview/glance through the history requests

### ISSUE THREAD

**Issue by lsreddy** [jarrodek/ChromeRestClient#544]
prior version has the ability to preview the request xml/json without opening it completely.  This feature was lost with the new update

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

I'm not sure if I understand correctly. What do you mean by that? It works exactly as it was:
![image](https://cloud.githubusercontent.com/assets/3320020/14673171/3a2eeeb6-06f4-11e6-90e6-349a676f4bfb.png)

Can you clarify a bit?

**Comment by jarrodek** [comment]
Hi,

Can you provide more info about the issue as per previous comment?

**Comment by jarrodek** [comment]
I'm closing this issue because of lack of response.
