### ISSUE TITLE
Rest client seems to edit the HTTP header field names

### ISSUE THREAD

**Issue by pubudu91** [jarrodek/ChromeRestClient#549]
When I send a request using the client, it seems to change the names of the HTTP header fields to lower case automatically.

## Expected outcome
The client should not be editing the header fields. For example, if I set a header field as "Content-Type", the request should be received at the server as "Content-Type"

## Actual outcome
After the new update, the client seems to be sending headers which were set as "Content-Type" to "content-type"

## Versions
App: 7.7.26.168-stable
Chrome: 47.0.2526.111
Platform: Linux (-)

## Steps to reproduce
1. Create a message with a payload and use POST as the method
2. Set the header "Content-Type: application/json" 
3. Send the message and observe the request received at the server

**Comment by rajnandan1** [comment]
Facing the same issue. Please fix this +1

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report. Please refer to the duplicate issue #517 for the discussion.
I'm closing it as WAI.
