### ISSUE TITLE
No more search functionality

### ISSUE THREAD

**Issue by AdriVanHoudt** [jarrodek/ChromeRestClient#551]
Continuation from https://github.com/jarrodek/ChromeRestClient/issues/510#issuecomment-211823979

I can only see a search option in history and cmd+f does not open up the default chrome search

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
Chrome apps do not have Chrome's search bar.
It is working in request screen so you can search for a string in the response. 
I'm not sure if you refer to any other search functionality in the app.

**Comment by AdriVanHoudt** [comment]
hmm not seeing it, where should that search be?

**Comment by jarrodek** [comment]
As in previous version it is working under ctrl/command + F shortcut. Is it what you mean?

**Comment by AdriVanHoudt** [comment]
Ok this is what I see after a request and pressing command + f 
http://puu.sh/ow9k8/22844250b8.png

**Comment by jarrodek** [comment]
@AdriVanHoudt is it working now? There was several fixes in this matter.

**Comment by AdriVanHoudt** [comment]
@jarrodek this seems fixed now thanks!
