### ISSUE TITLE
Http headers Authorization getting converted to lowercase.

### ISSUE THREAD

**Issue by rajnandan1** [jarrodek/ChromeRestClient#552]
Hi, I am using the new desktop app. When i send a request to the server with Authorization header set, the server cannot find the header as it gets converted from capital "A" to small "a". 

This was not happening on chrome extension.

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report. Please refer to the duplicate issue #517 for the discussion.
I'm closing it as WAI.
