### ISSUE TITLE
Unformatted output error (stuck loading).

### ISSUE THREAD

**Issue by FelipeSulser** [jarrodek/ChromeRestClient#554]
Whenever I expect my API to return something that is not HTML or JSON, for example a print_r of a PHP array for debug purposes, the petition gets stuck.

## Expected outcome
In the previous versions of the ChromeRestClient it would return the petition, and you were able to see the result in the Raw tab.

## Actual outcome
The petition gets stuck loading and never ends nor returns an error.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. Write php code that writes the contents of an array for example  `print_r($list); `
2. Use rest client and GET 
3. Petition gets stuck loading

**Comment by jarrodek** [comment]
Hi,

There is an uncaught error when the response body is requested from the Response object and in case of JSON there is an error thrown when it's not actually a JSON string.
It will be fixed.

**Comment by FelipeSulser** [comment]
Thanks!
Great to have such a quick feedback from the developers.
