### ISSUE TITLE
Certificate authenticaion

### ISSUE THREAD

**Issue by vkorecky** [jarrodek/ChromeRestClient#555]
New version cannot call REST services which require SSL Certificate Authentication.
Previous version allows call REST with a certificate authentication when I open REST URL in a chrome and select certificate before I use Chrome Rest Client.

In new version I still receive this error:
**There was an error during the request
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED**

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report. Please refer to the duplicate issue #432 for the discussion.
I'm closing it as WAI.

**Comment by el-schalo** [comment]
Sorry, but SSL seems not to work with the BETA as well... see https://github.com/jarrodek/ChromeRestClient/issues/730
