### ISSUE TITLE
Missing json tab

### ISSUE THREAD

**Issue by ajay-a3logics** [jarrodek/ChromeRestClient#556]
There is no json tab in the new update.Totally time waste to copy and paste into parser to see the output.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
It looks like your server is missing JSON content-type header (e.g. `application/json`). Therefore the app can't open the JSON tab because the server told the app that there is some different type of the response.

Per my response I'm closing this as WAI.
