### ISSUE TITLE
Null parameter concatenate to url

### ISSUE THREAD

**Issue by pierrelouisd4j** [jarrodek/ChromeRestClient#558]
On the request panel :
When I click on encode / decode parameters option a null parameter is concatenate to the url

## Expected outcome
[http://127.0.0.1:3000?query=Montreuil, IDF 93100](http://127.0.0.1:3000?query=Montreuil, IDF 93100)
Click on "encode parameters" option
http://127.0.0.1:3000?query=Montreuil%2C+IDF+93100

## Actual outcome
[http://127.0.0.1:3000?query=Montreuil, IDF 93100](http://127.0.0.1:3000?query=Montreuil, IDF 93100)
Click on "encode parameters" option
[http://127.0.0.1:3000**null**?query=Montreuil%2C+IDF+93100](http://127.0.0.1:3000?query=Montreuil%2C+IDF+93100)

## Versions
App: 7.7.26.168-stable
Chrome: 48.0.2564.116
Platform: Linux (-)

## Steps to reproduce
1.  Use any url without the "/" at the end of the domain
2. Encode or decode the url

In my opinion the problem comes from the missing "/" at the end of the domain of my request.

**Comment by jarrodek** [comment]
Thanks for an issue report.
It's definitely a bug. It will be fixed.
