### ISSUE TITLE
No message about invalid header

### ISSUE THREAD

**Issue by slouc** [jarrodek/ChromeRestClient#560]
Issuing a GET request with a header which contains whitespace should inform the user about the invalid header. Instead, the client just keeps retrying endlessly until the request is aborted.

## Expected outcome
Message about invalid header.

## Actual outcome
Client appears to be either retrying the request in an endless loop or waiting for a server (the progress bar keeps filling up). Press on abort button is needed.

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1.  Issue a GET request to an arbitrary GET REST endpoint with header key set to "white space" (note the space between). Header value is arbitrary.

**Comment by jarrodek** [comment]
Thank you for issue report.

What is the header? Not sure why it is causing an error.

**Comment by slouc** [comment]
I updated the issue.

**Comment by jarrodek** [comment]
This might be a different issue. When no headers are passed (whitespaces doesn't count since parse function will trim them) then no headers are set in the request. Can you add an log from the app when you making a request? See [debugging](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) for more details.

**Comment by slouc** [comment]
All that's needed to reproduce is to issue a GET request to any endpoint (e.g. https://httpbin.org/get) and include a header which has a whitespace in the key. So, this header won't work:

> white space:a

but this one will:
> nowhitespace:a

Here's an extract from the log:

```
elements.js:60639 
Uncaught TypeError: Failed to execute 'append' on 'Headers': Invalid name
headers.forEach @ elements.js:60639
Polymer.run @ elements.js:60639
async @ elements.js:55780
(anonymous function) @ elements.js:4099
Polymer.Async._atEndOfMicrotask @ elements.js:2716
window.MutationObserver.observe.characterData @ elements.js:2731
```

**Comment by jarrodek** [comment]
Now I get it. So you just pu invalid name in the headers list. That can be fixed with error report.

**Comment by slouc** [comment]
Exactly. Endless progress bar doesn't really indicate that the problem is actually something trivial such as invalid header. :)
