### ISSUE TITLE
Search functionality not working after upgrade

### ISSUE THREAD

**Issue by subhban01** [jarrodek/ChromeRestClient#563]
Your description here
This used to work perfectly fine in the older app.

## Expected outcome
What should happen?
Search-text entered in search-text-box should highlight the same text in the HTTP response/app.

## Actual outcome
What happened?
Doesn't highlight

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Entered URL with access token (cannot divulge exact organization-internal URL)
2. After the response was received, searched for some particular text
3. It says 0 text found, whereas text is present in response

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
I can't reproduce it though: 
![image](https://cloud.githubusercontent.com/assets/3320020/14679023/133f42bc-0710-11e6-87ad-0d064bb48175.png)

Can you provide more details? Like what text string did you searched for and part of the response (raw response) that contain this text?

**Comment by jarrodek** [comment]
Hi,

Can you provide more information as per my previous comment?

**Comment by subhban01** [comment]
![arc](https://cloud.githubusercontent.com/assets/7497992/14943167/95b52ae4-0fef-11e6-9ce9-af7d99b0bae3.png)
