### ISSUE TITLE
Please provide an option to reuse requests from history

### ISSUE THREAD

**Issue by subhban01** [jarrodek/ChromeRestClient#564]
Your description here
Need an option to reuse requests from history. At least let me copy URL from history.

## Expected outcome
What should happen?
Should be able to use requests in history, to create a new request again.

## Actual outcome
What happened?
Can only view request details.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Send HTTP request.
2. Go to History
3. Select the last request.

Can only view request details. Need an option to reuse requests from history.

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.

What about "Open" button? Is it works for you?
![image](https://cloud.githubusercontent.com/assets/3320020/14679183/ba1f02b6-0710-11e6-9ab5-32f51caee0ff.png)

**Comment by jarrodek** [comment]
(previous image was for different issue).

**Comment by jarrodek** [comment]
Hi,

Can you please clarify the issue?

Thanks

**Comment by subhban01** [comment]
Yes, an open button would definitely help

**Comment by jarrodek** [comment]
@subhban01 What's wrong with the button that is already there?

**Comment by subhban01** [comment]
That button was not available before. In fact no button was available to re-use requests from history.
The Open button works for me now. Closing this issue.
