### ISSUE TITLE
Search is infinitely slow after the upgrade.

### ISSUE THREAD

**Issue by subhban01** [jarrodek/ChromeRestClient#566]
Core functionalities like search should not be affected by upgrades. While fancy UI does help the app look cool, it is of no use if the core functionality itself is broken. The app has become very unstable after the upgrade.

My HTTP responses usually are quite big (for example: 267716 characters). After the upgrade, just typing in the search box starts hanging the app. The previous version used to work just fine.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.

Unfortunately Chromium team did not gaved search bar to the apps. Instead authors must come up with own ideas. It will be slower than native search in C (Chrome) and nothing can do about it. However there's always a room for improvements. Possibly the search function can be optimized and at some point I'll get back to it. 
Can't however promise that it will be done very quickly.

**Comment by jarrodek** [comment]
This is now fixed and will be released with v8.
