### ISSUE TITLE
After update, can no longer use custom methods

### ISSUE THREAD

**Issue by ultrapingu** [jarrodek/ChromeRestClient#568]
I use the client to send requests to a custom webserver which supports non standard methods (e.g. 'Create', 'Begin', etc).  In the older version you could select 'Other' from the method radios and type the method name, but after the update it appears as 'Other methods' has become a preset drop down?

Has the ability to use custom methods been removed?

**Comment by jarrodek** [comment]
Hi,

Thanks for a report.
It will possibly come back to the app in some time. It now contains most used list of methods. I'll put it on a requests list.

**Comment by jarrodek** [comment]
It is now available in stable channel.
