### ISSUE TITLE
Add a JSON view

### ISSUE THREAD

**Issue by nicolasgelly** [jarrodek/ChromeRestClient#570]
In previous versions json data be read in a structured view.

Is it possible to add this feature in current version ?

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
Not sure what you mean. Is there where it was:

![image](https://cloud.githubusercontent.com/assets/3320020/14681541/7128bcc4-0719-11e6-8e9d-7d2da4f24db6.png)

Is the server returned proper content-type?

**Comment by southpawlife** [comment]
+1 this was great functionality. I believe before you could click view as JSON when the content-type header was not set on the response explicitly.

**Comment by jarrodek** [comment]
Thanks @southpawlife for joining the discussion.
I'm struggling with this one.
Basically you are right about it and I remember putting this option in old version of the app. On the other hand the philosophy of the app is to give accurate debugging tool for developers and testers. By accuracy I understand that the app should interpret the response as clients would do. So it basically follows many HTTP spec to send, receive and interpret data. This is important from testing POV. If somethings works in the app and won't work in production this will defeat the purpose of the app. It actually gives developers an opportunity to recognise the issue with the server and fix it when is a time for that.

Any thoughts on that?

**Comment by peterrecore** [comment]
@jarrodek , your point that following the spec by default will help developers recognize a problem is valid.  But not all of us are lucky enough to consume API's that follow current specs faithfully.  Having the default behavior follow the spec, as you have, is great, but having an *option* to view as JSON regardless of content-type header could also be useful.

**Comment by philmagr** [comment]
In practice, if the client is expecting JSON it's not going to care about the content-type and read it as JSON anyway, so I agree with having all view options available at all times. You can certainly pick a default one based on the content-type though.

**Comment by southpawlife** [comment]
I would second @philmagr, and @peterrecore's statements.

**Comment by jarrodek** [comment]
Content type check based on the response payload is very expensive for the app and not 100% accurate. 
In current release the app have a button to force open the response in JSON panel. I believe it's the best solution here. Users can open the response in the dedicated preview panel but also will be notified that the response has wrong content type and it should be corrected.
