### ISSUE TITLE
Cannot fill URL when reopen URL from history 

### ISSUE THREAD

**Issue by mantisvn** [jarrodek/ChromeRestClient#578]
Cannot fill URL when reopen URL from history 

## Expected outcome
What should happen?
Should fill URL to Host field

## Actual outcome
What happened?
It's loaded body form BUT did not fill Url to HOST field

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.87
Platform: Linux (-)

## Steps to reproduce
1. Open History list 
2. Click Open an old Url
3. It's load body form BUT Host-URL did not fill

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.
It is already fixed in a hotfix branch and after some tests it will be released as hotfix.
As per this I'll close this issue.
