### ISSUE TITLE
Response with null body status cannot have body

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#580]
Your description here

## Expected outcome
get patch successfully result

## Actual outcome
got patch failed response

## Versions
App: 7.7.26.168-stable
Chrome: 47.0.2526.106
Platform: Linux (-)

## Steps to reproduce
1. patch
2. get error: 
"There was an error during the request
Failed to construct 'Response': Response with null body status cannot have body"
then can not patch again until change the submit data

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.
It is already fixed in a hotfix branch and after some tests it will be released as hotfix.
As per this I'll close this issue.
