### ISSUE TITLE
Getting net::ERR_CONNECTION_TIMED_OUT error for any HTTP request in new Advanced REST client

### ISSUE THREAD

**Issue by DeepakGsd** [jarrodek/ChromeRestClient#582]
Your description here

## Expected outcome
When used the new Advanced Rest Client, (when I mean by new, the application is opening in a new window rather than being a part of the Chrome browser tab, which was the case earlier), any http requests I should get the proposer response

## Actual outcome
With the new chrome advanced rest client, I get always "net::ERR_CONNECTION_TIMED_OUT" error

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. In the new advanced rest client, make any http request, you will face net::ERR_CONNECTION_TIMED_OUT error

**Comment by btreinders** [comment]
I am having the same issue.  I don't understand, isn't making http requests the primary purpose of a rest client?

**Comment by jarrodek** [comment]
Hi,


Thank you for issue report.
I can't reproduce the problem. Can you put more detailed description of the error? Maybe you can try to debug the app (https://github.com/jarrodek/ChromeRestClient/wiki/debugging)? 
Are you behind a proxy? Then setting up proxy in Chrome settings may help. 
As for now I don't have all the information.

**Comment by btreinders** [comment]
This used to work fine in the browser app, now that I have to use the app itself this is what I get.
      
Date: Mon, 25 Apr 2016 17:46:11 -0700

**Comment by jarrodek** [comment]
I'm not sure if I got all your message. Can you check on a web page that it's all here? Did you attached some file in your response?

**Comment by btreinders** [comment]
Sorry, I put it inline instead of attaching.  Attached now. That is the error I get that used to work just fine from the web browser app.

Thanks

Date: Thu, 28 Apr 2016 04:41:03 -0700

**Comment by yoichi** [comment]
I have the same problem. I'm behind a proxy. The proxy setting in Chrome is working fine.
I can connect to servers in local network with ARC. It seems Chrome proxy setting is not used by ARC. 

Google Chrome	51.0.2704.103 (Official Build) m （32 bit）
Advanced REST client 7.29.44.223-stable
Windows 7 (64bit)

**Comment by jarrodek** [comment]
Hi,

Have you tried turn on "Use XHR" option in the main view? It requires additional extension but it send the request thought Chrome network stack and therefore respecting proxy settings.
I've found an issue for Chrome socket API (used by ARC) https://bugs.chromium.org/p/chromium/issues/detail?id=414378 and sockets can't connect via proxy. I can't do much about it until Chrome add ability to connect on socket via proxy.

**Comment by yoichi** [comment]
Hello jarrodek,
Now I've installed ARC cookie extension and turned on "Use XHR", the problem has gone!
Thanks.

**Comment by DeepakGsd** [comment]
Hi,
Sorry for the delayed response. Enabling (switching ON) Use XHR solved the problem for me.

Thanks for your responses
-Deepak
