### ISSUE TITLE
Unable to edit saved request body

### ISSUE THREAD

**Issue by bobhall106** [jarrodek/ChromeRestClient#583]
Your description here
The ARC client used to work perfectly. Bring back the old version so we can still use that please?
First you bring it on line with missing functionality like searching on titles. Then I can't edit a saved message body.
User inface is all lovely an mobile but much harder to use on desktop. I have to click a lot more times to attempt what used to be easy.
## Expected outcome

What should happen?
I should be able to edit a saved message.
An upgrade should make things better, not worse.
## Actual outcome

What happened?
Exactly what has happened to ARC?
User experience drives me to use another app.
## Versions

App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)
## Steps to reproduce
1. Open ARC
2. Open saved message (post) 
3. try to edit body but it is readonly!
4. Start migrating my work to Postman as you obviously do not give a care about your existing user base.

**Comment by jarrodek** [comment]
The release with fix has been published today.
Thanks for reporting the bug.
