### ISSUE TITLE
Loading from history broken

### ISSUE THREAD

**Issue by saganas** [jarrodek/ChromeRestClient#588]
The loading from history doesn't work.

## Expected outcome
A full URL should appear for POST

## Actual outcome
Just http:// appears

## Versions
App: 7.7.26.168-stable
Chrome: 48.0.2564.116
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1.  From history I select POST command (with URL, from previous version)
2.  Click on it
3.  It load headers, but in URL only http://

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.
Is this happening only if you have detailed URL panel opened?

**Comment by saganas** [comment]
Whenever I try to click on history from the list.

**Comment by jarrodek** [comment]
Can you please paste here a logs after you open a request? Logs are in left nav panel on the bottom in "more" dropdown list.

**Comment by jarrodek** [comment]
There was an issue when restoring the request while detailed URL panel is opened. The form wasn't refreshed.
It's already fixed
