### ISSUE TITLE
Unable to select from history

### ISSUE THREAD

**Issue by saganas** [jarrodek/ChromeRestClient#589]
When open a command from history the url is in Label field instead of text, hence unable to select the text

## Expected outcome
I should be able to select the text
## Actual outcome
Text is a label, so can't select anything, just headers and payload.

## Versions
App: 7.7.26.168-stable
Chrome: 48.0.2564.116
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. I click on history
2. select with checkbox a previous command
3.  The right hand rail appears
4. I try to select the URL and can't

P.S. Don't know if you aware, but on google store very bad reviews for popup feature and this new release, my colleagues are also highly disappointed with pop-up screen.

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
As for popup window issues, please, refer to the issue #510 for detailed discussion and explanation.

As per your issue, do you mean that you can't select text in the saved list panel?

Thanks.

**Comment by jarrodek** [comment]
I'm closing this issue because of lack of response.
