### ISSUE TITLE
Bug After running WS

### ISSUE THREAD

**Issue by vcajes** [jarrodek/ChromeRestClient#590]
After I get a OK return from a POST call, I try to change to another web service from the list on the same project. After I click on another we service, the parameters does not change, and remain the same parameters of the previous web service. :(

## Expected outcome
Update the parameters after change the web service from the list I already have. (from the preeeevious version of the REST client test)

## Actual outcome
The parameters are not beign updated (and I need to restart the application to run one web service at a time)

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.

Is this happening only when detailed URL panel is enabled (with host, path and params)?

Thanks.

**Comment by vcajes** [comment]
I do not know that you mean by "only". Is there another form of calling web services? I always pass host, path and params to call web services. @jarrodek

**Comment by jarrodek** [comment]
@vcajes  The URL panel can be either in simple view (only one text input) or detailed (form with many inputs). I recognized already that there is similar issue when you have detailed view opened. So I want just to confirm if this is the case.

**Comment by vcajes** [comment]
Yes. This is the case. With mutiple forms. Thanks

On Monday, 25 April 2016, Paweł Psztyć <notifications@github.com> wrote:

> @vcajes <https://github.com/vcajes> The URL panel can be either in simple
> view (only one text input) or detailed (form with many inputs). I
> recognized already that there is similar issue when you have detailed view
> opened. So I want just to confirm if this is the case.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jarrodek/ChromeRestClient/issues/590#issuecomment-214521127>
>


-- 
Sent from my iPhone

**Comment by jarrodek** [comment]
Thanks for clarification @vcajes 
I already have fixed this issue. After I test the update I'll publish it. Should be done in coming days.

**Comment by jarrodek** [comment]
It was released in stable channel.
