### ISSUE TITLE
Requests from new "desktop app" version aren't part of web session

### ISSUE THREAD

**Issue by swimbikerun** [jarrodek/ChromeRestClient#591]
Due to my particular use of ARC, I think I'll have to abandon the new implementation. I need to first authenticate with a site and get an active session, then I jump over to ARC and make REST calls. (I know this isn't very standard practice.) The new implementation makes requests that aren't part of the same session (I'm guessing it just doesn't send the cookies that the browser has for the given URL.) So, all of my REST requests are getting a 403 back from the services.

The general picture for the services I'm calling is...

browser (or ARC) ---> service proxy that handles OAuth wrapping the call ---> REST endpoints

So, the browser request is to a stateful, session-based service proxy. The service proxy makes an OAuth secured call to the REST endpoint and returns the response to the browser (or ARC). So I normally pop open a Chrome window and login to the site, which tells the service proxy to get an OAuth token for me and store it in session. Then my calls to the proxy are turned into OAuth-secured REST calls to the backend. Since the new ARC doesn't send cookies to the server, I'm not in the same session, so no OAuth token is found for my new session. All of the REST calls return HTTP 403 in that case.

**Comment by irufus** [comment]
Yeah same problem here. Could have given us a heads up to those who don't follow the project this closely. I have to authenticate as well and for some strange reason I can't even call the login site as it gets 410'd. This is probably do to my departments attempt at a defense against bots from scouting out the admin back page.

**Comment by richardgirges** [comment]
Same problem for me. I even tried to setup a local session within ARC by hitting the "user signin" endpoint of my app, but for some reason, the cookies don't get retained in ARC and I'm unable to test any endpoint that requires an authenticated session. Real bummer, ARC was my go-to for this type of thing.

**Comment by jarrodek** [comment]
Hi,

Thanks for an issue report.
Right now I'm testing own cookie session management in the app. It is basically implementation of the HTTP spec session management. So it will mimic browser's functionality.
It won't however have an option to synchronise cookies between Chrome browser and the app because there is no API available for apps to do it.

The update will be released in coming days.

**Comment by ardanika** [comment]
I've run into the same issue with java sessions. Now I have to manually add a "Cookie:" request header with JSESSIONID to each request.

**Comment by jarrodek** [comment]
Hi,

Today's morning (London's time) I've released an update. This update contains a session management inside the app (a cookie storage with cookie logic described in the spec).
There is no, however, cookie synchronization between Chrome and the app. There's no API for that in Chrome. So all cookies received by the app will be used as usual but they need to be physically received by the app.
Please, let me know if you find an issue in this new session management. I'll be happy to fix it. However it algorithms has been implemented as described in the spec.

More info here: https://restforchrome.blogspot.co.uk/2016/04/session-management-aka-cookies-in.html
