### ISSUE TITLE
Can't use form auth in new version of app?

### ISSUE THREAD

**Issue by TRmcochrane** [jarrodek/ChromeRestClient#593]
I've been using the legacy ARC happily for months and primarily for work with Rational Team Concert.

The thing is, I have no control over the authorization requirements of the server, but I know that Basic auth doesn't pass. All I ever get back is HTML describing that Javascript is disabled or not available in my browser.

With the legacy app, I could log in in another tab and then the session would provide authorization. With the new ARC app, I can't figure out how to authorize my REST calls to an RTC server. I've tried manually adding a cookie header with info I've copied from an authenticated browser cookie, but can't get that to work.

Does the separation of ARC from the Chrome browser session make form auth impossible, or am I missing something?

**Comment by iGanja** [comment]
I am having the same issue. I am hitting a Windows IIS server using Negotiate; NTLM authentication. This worked flawlessly with the old version. It does not work at all with this new version, or I cannot find how to do it. Where do I provide NTLM authentication credentials now?

**Comment by TRmcochrane** [comment]
Thank you for the explanation and honesty. I look forward to the enhancement and will find another way to experiment with REST on this particular server in the meantime.

**Comment by DPCServices** [comment]
Thank you for detailed response, it saved me creating an unnecessary bug report. I use ARC mainly for debugging SharePoint API calls. Of course, because of this issue, the capability to do this has gone. It's only when you lose something that you realise just how useful it was - hope you can come up with a fix soon
