### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by pradeepsappa** [jarrodek/ChromeRestClient#594]
Your description here
I tried to test the rest service, 
its was able to hit the debug point but during debugging it showing error occurred in the remote server but there is no error in the code and still debugging in process.

## Expected outcome
What should happen?
json data
## Actual outcome
What happened?
error
## Versions
App: 7.7.26.168-stable
Chrome: 47.0.2526.106
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Is the issue report still valid? @pradeepsappa

**Comment by jarrodek** [comment]
Closing due lack of response and clarification.
