### ISSUE TITLE
No longer able to view response in web browser

### ISSUE THREAD

**Issue by oceanapplications** [jarrodek/ChromeRestClient#598]
Since the update I can't view the response as a rendered web page which is very annoying since in development I use laravel's dump function which outputs a lot of javascript and makes it impossible to find the data I'm looking for without being able to run that script.

Thanks

**Comment by jdavidbakr** [comment]
Agreed, same issue here. This was a critical part of my development and I miss it terribly!

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I'm testing hotfix update and this is fixed there. Update will be published in coming days.

Thanks

**Comment by jarrodek** [comment]
It was released in stable channel.
