### ISSUE TITLE
Unable to get the certificate

### ISSUE THREAD

**Issue by anilkumarsagar3001** [jarrodek/ChromeRestClient#599]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Please, provide issue details or the issue will be closed as invalid.
