### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by JawadHyder** [jarrodek/ChromeRestClient#601]
When application is in debug mode and stops at a breakpoint, the new ARC immediately gives a timeout error where as in the old version it was not giving such error. 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Linux (-)

## Steps to reproduce
1. Start application in debug mode
2. hold an app at some breakpoint (5-6 seconds)
3. Notice ARC will give timeout error

**Comment by geeprime** [comment]
I'd like to know how to adjust the timeout as well.

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
Timeout can be adjusted in settings. It's not yet released and currently tested but it will be fixed in coming days.

Thanks.

**Comment by jarrodek** [comment]
It was released in stable channel. You can adjust timeout in settings.
