### ISSUE TITLE
The request has been aborted manually or because of the connection timeout

### ISSUE THREAD

**Issue by Harish27-GitHub** [jarrodek/ChromeRestClient#605]
In previous version when we make REST API call in debug mode were able to debug and  come back to see the output in ChromeRestClient but after latest update 7.7.26.168 we get aborted message and even though the server completed processing and returned back response we are not able to view it.

## Expected outcome
What should happen?
Option of accepting timeout value or previous versions behavior, both are fine.

## Actual outcome
What happened?
Connection got aborted.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. Make REST API call.
2. Have you server code in debug mode, do not proceed past break point for some seconds.
3. Then hit run, API completes processing however ChromeRestClient  shows Aborted/Time Out Description.

**Comment by dennislysenko** [comment]
+1, having to use a different REST client because of this

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
In coming days there will be update where you can adjust timeout settings (including turning it off).
By default it is 30 seconds (after update).

Thanks.

**Comment by jarrodek** [comment]
It was released in stable channel. You can adjust timeout in settings.
