### ISSUE TITLE
Cannot load saved REST requests

### ISSUE THREAD

**Issue by ricsierics** [jarrodek/ChromeRestClient#606]
Your description here

## Expected outcome
Upon selecting dropdown on top which specifies what REST request I want to use, request parameters on the main pane should load accordingly

## Actual outcome
Doesn't load my saved REST request even selecting other items from the dropdown located on top center of the window

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. 
2. 
3.

**Comment by TRmcochrane** [comment]
I've noticed this is reproducable when the URL is broken apart into its Host, Path, and Query parameters. However, when I collapse that into one line, I am able to load saved requests from Projects.

Is that what's happening for you?

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
I already fixed it and now I'm testing the update. You'll receive the update in coming days.

Thanks.
