### ISSUE TITLE
What the fuck new version are improving?

### ISSUE THREAD

**Issue by haodc123** [jarrodek/ChromeRestClient#607]
New version is terrible, old version are better

## Expected outcome
You should try get a jSon response and the way it has been displayed.

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.87
Platform: Windows (8.1)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Can you please clarify? I can't see an issue here.
