### ISSUE TITLE
Can't mark text for copy-paste

### ISSUE THREAD

**Issue by guysmoilov** [jarrodek/ChromeRestClient#608]
Can't select text using the mouse for copying.
This seems to happen anywhere that isn't inside an editable text area, e.g. all labels.

## Expected outcome
I can mark text just like anywhere else in my PC using the mouse.

## Actual outcome
Marking text is impossible, can't copy it.

# Versions
App: 7.7.26.168
Chrome: 49.0.2623.112 m
OS: Windows 7

# Steps to reproduce
1. Open ARC
2. Go to Socket
3. Open a websocket to some server
4. Send a message
5. Receive a message
6. Attempt to mark and copy either message

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I'll try to fix it in next update.
