### ISSUE TITLE
corporate proxy

### ISSUE THREAD

**Issue by amitmaimon** [jarrodek/ChromeRestClient#609]
I cannot use ARC from a corporate network since the application does not use the corporate proxy server

## Expected outcome
application should identify corporate proxy automatically from browser settings

## Actual outcome
timeout connections

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. open RCA from a corporate network that uses proxy
2. run any external API
3. connection timeout

**Comment by jarrodek** [comment]
Hi,
Thank you for your issue report.


As much as I'd like to give you in-app proxy settings as much I can't do it.
Please, refer to the issue #602 for detailed explanation.

I'm closing this as a duplicate.

Thanks.
