### ISSUE TITLE
Parameter list not automatically updating

### ISSUE THREAD

**Issue by mclijauco** [jarrodek/ChromeRestClient#611]
Your description here
## Expected outcome

Parameters for the selected endpoint should be shown.
## Actual outcome

Parameters for the previously selected endpoint are shown.
## Versions

App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)
## Steps to reproduce
1. Select an end-point that has parameters.
2. Select another end-point that also has parameters.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
It is happening only when detailed panel is opened? If yest it is fixed in the develop branch and currently tested. Expect an update in coming days.

**Comment by mclijauco** [comment]
Hi *Pawel*,
Which one is the detailed panel again?

Thanks and Regards,
*Marc Carlo Lijauco*
+639175241091 / +639988614524
<http://www.snipe.ph> l  <http://www.facebook.com/SnipePH>
<http://www.instagram.com/snipeph/>
