### ISSUE TITLE
How can I dock the floating window into a tab again in the chrome browser

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#612]
I was forced to upgrade to new version

The new version have a lot of nice features. 

I used have ARC open in several tabs, because i have a sequence of 4 REST calls that is needed to be called in order.
But I have problem with the floating windows.
How can I dock the floating window into a tab again in the chrome browser?

**Comment by mmcreavy** [comment]
I agree, this needs to be changed back. I want it to be in a tab again.

**Comment by pgier** [comment]
I was just looking for the same feature.  Sometimes I like to have multiple rest clients open in separate tabs.  Having them in separate windows makes it harder for me to switch between them.

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
As for popup window issues, please, refer to the issue #510 for detailed discussion end explanation.

I'm closing this as a duplicate.

Thanks.
