### ISSUE TITLE
After 20-30 seconds I get a Abort / timeout

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#613]
I was forced to upgrade to new version

The new version have a lot of nice features. 

When I do a call with large content I get a time out, this usally takes 2 minutes to get the data.

After 20-30 seconds I get a Abort / timeout. This was not any problem with the old version.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
In coming days there will be update where you can adjust timeout settings (including turning it off).
By default it is 30 seconds (after update).

Thanks.

**Comment by jarrodek** [comment]
It was released in stable channel. You can adjust timeout in settings.
