### ISSUE TITLE
No answer from ARC, ARC waits forever.

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#614]
I was forced to upgrade to new version

The new version have a lot of nice features.

When I do a call with large content I get a time out, this usally takes 2 minutes to get the data.
After 20-30 seconds I get a Abort / timeout. This was not any problem with the old version.

After a while I do the same call again.
 I can see in the loggs that the call took about 1,5 sec (was fetched from the cache).
 I seems that the new ARC can't handle big data, my guess a few MB. This was not any problem with the old version.
 And ARC waits forever.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Can you paste debug logs here to clarify what's happening? 
You can read how to debug the app here: https://github.com/jarrodek/ChromeRestClient/wiki/debugging

**Comment by peterivarsson** [comment]
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,700' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
_requestChanged RequestLocalObject
Database already populated
The database has been populated with data.
Database already populated
The database has been populated with data.
Database already populated
The database has been populated with data.
Cleared: 4197 logs
_requestChanged RequestLocalObject
_requestChanged RequestLocalObject
_requestChanged RequestLocalObject
History URL has been saved.
Created socket 1
Connecting to sfbm-test.cybercomhosting.com:443
Connected to socked for host:  sfbm-test.cybercomhosting.com  and port  443
Generated message to send
 GET /services/5/movies/SE  HTTP/1.1
HOST: sfbm-test.cybercomhosting.com
x-sf-android-version: 530
accept: application/json
authorization: Basic U0ZiaW9BUEk6YlNGNVBGSGNSNFoz


Sending message.
Written message. Bytes sent: 180
Has socket data
Processing status
Processing headers
Received headers list Date: Tue, 26 Apr 2016 05:17:48 GMT
Server: WildFly/8
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Cache-Control: no-transform, max-age=600
X-Powered-By: Undertow/1
Pragma: no-cache
Content-Type: application/json
Via: 1.1 sfbm-test.cybercomhosting.com
LBPATH: (null)
Transfer-Encoding: chunked Object
Processing body
Chunk size:  8192
Part size:  0
Creating new body
Body size is:  0  and chunk size is left is:  8192
No more data here. Waiting for new chunk
Has socket data
Processing body
Part size:  4096
Appending to the body
Body size is:  4096  and chunk size is left is:  4096
No more data here. Waiting for new chunk
Has socket data
Processing body
Part size:  4096
Appending to the body
Body size is:  8192  and chunk size is left is:  0
No more data here. Waiting for new chunk
Has socket data
Processing body
Chunk size:  NaN
Disconnect
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
fileLoggerSave e
fileLoggerSave e
Window error event, ErrorEvent
Uncaught TypeError: this._mainPromise.reject is not a function
History URL has been saved.
Created socket 2
Connecting to sfbm-test.cybercomhosting.com:443
Connected to socked for host:  sfbm-test.cybercomhosting.com  and port  443
Generated message to send
 GET /services/5/movies/SE  HTTP/1.1
HOST: sfbm-test.cybercomhosting.com
x-sf-android-version: 530
accept: application/json
authorization: Basic U0ZiaW9BUEk6YlNGNVBGSGNSNFoz


Sending message.
Written message. Bytes sent: 180
Has socket data
Processing status
Processing headers
Received headers list Date: Tue, 26 Apr 2016 05:22:01 GMT
Server: WildFly/8
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Cache-Control: no-transform, max-age=600
X-Powered-By: Undertow/1
Pragma: no-cache
Content-Type: application/json
Via: 1.1 sfbm-test.cybercomhosting.com
LBPATH: (null)
Transfer-Encoding: chunked Object {Date: "Tue, 26 Apr 2016 05:22:01 GMT", Server: "WildFly/8", Expires: "0", Cache-Control: "no-cache, no-store, must-revalidate; no-transform, max-age=600", X-Powered-By: "Undertow/1"…}
Processing body
Chunk size:  8192
Part size:  0
Creating new body
Body size is:  0  and chunk size is left is:  8192
No more data here. Waiting for new chunk
Has socket data
Processing body
Part size:  4096
Appending to the body
Body size is:  4096  and chunk size is left is:  4096
No more data here. Waiting for new chunk
Has socket data
Processing body
Part size:  4096
Appending to the body
Body size is:  8192  and chunk size is left is:  0
No more data here. Waiting for new chunk
Has socket data
Processing body
Chunk size:  NaN
Disconnect
Uncaught (in promise) SyntaxError: Unexpected end of JSON input

**Comment by jarrodek** [comment]
Issues with the transport library and the chunk size read was resolved earlier.
