### ISSUE TITLE
Now possible to search anymore in new version

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#615]
I was forced to upgrade to new version

The new version have a lot of nice features. 

When the ARC was in the tab I could use the Chromes find function. When you have a big response this is convenient to find data and errors. I have servers that return large response contents like 2 MB.
These feature did exist in the now floating window version.

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.
Can't you open a search bar in the request view? Similar to this:
![image](https://cloud.githubusercontent.com/assets/3320020/14799114/e1b4966c-0b32-11e6-9f90-a798a9a9c84e.png)

**Comment by peterivarsson** [comment]
No I can't.
On my Mac I use 'Command F' in the Chrome browser,
This command don't work in the ARC rest client.
Is there an other way to do this?

**Comment by jarrodek** [comment]
This has been tested and works as intended. Possibly it was fixed earlier.
