### ISSUE TITLE
Custom HTTP headers are sent as lowercase

### ISSUE THREAD

**Issue by philmagr** [jarrodek/ChromeRestClient#617]
When executing a request with a non-standard header, the header is lowercased before sending to the server.

Technically this shouldn't matter, because HTTP headers are supposed to be case sensitive, but not everything behaves according to the spec.

I would expect the request to be sent EXACTLY as typed.

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491for detailed discussion and explanation. I'm closing this as a duplicate. 

Thanks.
