### ISSUE TITLE
Export of an response omits the carriage return

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#620]
Export of an response omits the carriage return.
It is difficult to read the file in editor it is only one big row.

{"shows":[{"auditoriumName":"Scandinavia 9","auditoriumsys99Code":"KI","buyable":true,"id":"2016-04-26_1800_KI_SE","loyaltyMaxTickets":0,"loyaltyOnlyForGoldMembers":false,"loyaltyPointsNeeded":0,"membershipRequired":false,  .......

![skarmavbild 2016-04-26 kl 12 13 21](https://cloud.githubusercontent.com/assets/13362021/14814876/84823d66-0ba8-11e6-8acb-629d401626eb.png)

![skarmavbild 2016-04-26 kl 12 16 10](https://cloud.githubusercontent.com/assets/13362021/14814928/c6297b3a-0ba8-11e6-9058-98e34d484ef4.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Basically the file is not meant to be read by human. It's a backup / export-import file to share and so on. It's just an option to share data between app's instances.

On the other hand text editors usually have beautifiers for JSON and it's shouldn't be a problem anyway.

Right now I'd like to close it as WAI.
But I'm open for discussion. Or for PR.
