### ISSUE TITLE
No option to supply client ssl cert

### ISSUE THREAD

**Issue by dmccann-fo** [jarrodek/ChromeRestClient#621]
I am debugging an application that requires the client to provide an SSL cert, this doesn't appear to be an option with the new ARC (in the old version, it seems to have used the same cert that I chose when browsing to the site normally as I had no problems doing this).

## Expected outcome
The site should load as normal

## Actual outcome
Failed with net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
In the log:
[ 7:07:23 AM ] Error during fetch {"message":"net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED"}
at connection.fetch.then.catch (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:60665:15)

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.86
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Find a site that requires client-side ssl certs
2. Issue a GET request to said site

**Comment by petermnilsson** [comment]
You get the same result if you try to access a site that wants, but doesn't require a client to authenticate with a client certificate. i.e. in Java an SSLSocket is configured with `setWantClientAuth(true)` but not `setNeedClientAuth(true)`.

**Comment by jarrodek** [comment]
Please, select "Use XHR" in the request panel to fix this issue.
