### ISSUE TITLE
Abort/ timeout

### ISSUE THREAD

**Issue by DuaaZahi92** [jarrodek/ChromeRestClient#622]
The request aborts after 20 seconds. 

![2016-04-26_1512](https://cloud.githubusercontent.com/assets/7118779/14816534/8e98d07a-0bc2-11e6-8498-52bdec7b6d8d.png)

## Expected outcome
I except the request to be alive as long as the response doesn't reach the client. In the old RestfulClient, the connection used to stay longer until the response comes back.   

## Actual outcome
However, in the newly updated RestfulClient, the connection is only alive for 20 seconds which is very annoying while debugging. If this was something that was added on purpose, can you at least make it optional to choose if a connection should be alive as long as the request takes. 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Run a restful application in debug mode. 
2. Add a break point.
3. Fire Http request and wait 20 seconds. 

Note: I tried adding the header parameter "Connection:close" but it did nothing.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Today's update increased default timeout to 30 seconds and gives you option to set the timeout in settings.

It is fixed already.
