### ISSUE TITLE
The plugin is very slow

### ISSUE THREAD

**Issue by Puneetvijay** [jarrodek/ChromeRestClient#624]
After the change where it pops up in new window. The plugin has become very slow. Even scroll up and down of response takes for ever. 

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.9.29.179-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Thank you for issue report.
I agree that in some cases (like really big request) it can take some time to scroll down/up. But it's a natural behavior and it works as intended.
