### ISSUE TITLE
Unable to view saved REST call list

### ISSUE THREAD

**Issue by undyingshadow** [jarrodek/ChromeRestClient#626]
Steps:
1) Click to load a project from the side
2) Under Project Endpoints, click the down arrow

Result:
The text that loads is extremely cutoff

See screenshot

![screen shot 2016-04-26 at 12 39 15 pm](https://cloud.githubusercontent.com/assets/18685491/14828736/daa8eeb0-0bad-11e6-915d-5dd0df5723fd.jpg)

**Comment by jarrodek** [comment]
Hi, 

Thank you for issue report. 
I'm testing the fix right now. I should release it very soon.
