### ISSUE TITLE
New version Timeout

### ISSUE THREAD

**Issue by NatasaVaritimou** [jarrodek/ChromeRestClient#627]
How can we change the timeout ?

**Comment by jarrodek** [comment]
Hi,

In settings you have a section for request settings. There is an option to change timeout. Is this works for you?

**Comment by NatasaVaritimou** [comment]
Yes thank you

On Tue, Apr 26, 2016 at 8:37 PM, Paweł Psztyć <notifications@github.com>
wrote:

> Hi,
>
> In settings you have a section for request settings. There is an option to
> change timeout. Is this works for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jarrodek/ChromeRestClient/issues/627#issuecomment-214861846>
>



-- 
Cheers

Natasa
