### ISSUE TITLE
cookies not being sent back in the request

### ISSUE THREAD

**Issue by maror6** [jarrodek/ChromeRestClient#628]
While I am firing one of the request, I am getting the successful response back from the server (localhost). my app server is returning me the JSESSIONID cookie with a valid value.

The problem is that while I am making a second call (2nd api) the JSESSIONID cookie is not being sent back and hence my server is creating a new session. As a work around I have to manually set the header with Cookie: JSESSIONID=some value to make it work.

App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
You are using the version that didn't had a session management in it. It's a new thing from version 7.9.*. It should works now.
Please, let me know.

**Comment by maror6** [comment]
I am still facing the same issue. the JSESSIONID is not being sent in the subsequent request. the request header is empty. I am using  7.9.29.179-stable version now.
Please see the screenshot, where I have fired two request just seconds apart and JSESSIONID changed.

![arc_issue](https://cloud.githubusercontent.com/assets/17703842/14860225/6c43000a-0cc5-11e6-9ba7-71222f5c4cce.png)

**Comment by Kapilsharma1991** [comment]
hi,

I am also facing same issue, JSessionId doesn't maintain for subsequent request .

**Comment by rsahota-26** [comment]
hi, 

I am facing the same issue, due to different session getting created, I am not able to change my session scope properties in the very next call.

**Comment by jarrodek** [comment]
Thank you very much for the details. I'll dig into it.

**Comment by caizixingit** [comment]
Hi, 
I also have the same question, it makes my job harder.
I want to know how to solve it

**Comment by jarrodek** [comment]
@caizixingit it is tested right now and it was fixed in referenced commit.
There was an issue in path-match algorithm and cookies in this case was stored in the database but not restored because of not matching path.
Anyway, it will work now.
You can test it as well in the beta channel: http://restforchrome.blogspot.com/2016/03/join-advanced-rest-client-beta-program.html
