### ISSUE TITLE
Unable to use copied JSON response

### ISSUE THREAD

**Issue by dcheath60** [jarrodek/ChromeRestClient#629]
When copying the response in the JSON tab, I am not able to use the copied JSON as a request payload because the JSON lacks commas between the fields.

## Expected outcome
JSON fields separated by commas

## Actual outcome
{
"deliveryMarketID": "UDEN"
"postalCode": "80478"
"transitTime": 41.9
}

## Versions
App: 7.9.29.179-stable
Chrome: 49.0.2623.87
Platform: Windows (7)

## Steps to reproduce
1. Send a GET request to a REST service
2. Copy the JSON response
3. Paste the JSON response as a PUT request payload.
4. REST service not able to parse request payload

**Comment by Izuzusama** [comment]
I think you are seeing the parsed json view. That has no commas. 
Click on the Raw and you can see the commas

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Besides the raw panel as mentioned by @Izuzusama you also have copy icon just above the content (first icon on left). You can use it to copy the response.
JSON tab is mean to read/analyse the response. I haven't thought to actually use it somehow. 

I also don't think that the change is required giving you other options you have to copy text.
I'd be inclined to close this issue as WAI.
