### ISSUE TITLE
TimeOut Response

### ISSUE THREAD

**Issue by VijayaRekhaAluri** [jarrodek/ChromeRestClient#632]
Getting continuous timed out response for all the requests.Is there any settings to change this?? or help me how to degrade to old version.
2) I am using URL with Domain Name having SSL certificate.I am getting 
[chrome socket error]: An SSL protocol error occurred
it was working fine with previous version

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
1) You can adjust timeout in settings
2) Refer to one of https://github.com/jarrodek/ChromeRestClient/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cert

I'd be inclined to close this as 1) WAI 2) duplicate

Thanks.
