### ISSUE TITLE
History Request Detail have no Scroll Bar

### ISSUE THREAD

**Issue by Izuzusama** [jarrodek/ChromeRestClient#633]
History request detail does not have a scroll bar when it gets too long.

![too long](https://cloud.githubusercontent.com/assets/9895213/14846153/cd86e038-0c94-11e6-8630-d3cfd8253719.png)

## Expected outcome
Should have a scroll bar if content is too long

## Actual outcome
No scroll bar. Content is croped

# Versions
App: 7.9.28.179
Chrome:  49.0.2623.112 m

# Steps to reproduce
1. Goto request
2. Send a long content / header
3. Goto history
4. Double click on the request sent on 1

**Comment by jarrodek** [comment]
Hi, 
thank you for issue report.
I'll fix it when I have chance to do it. 

If you know how to code in JS it would be faster if you send a PR for this :)

Thanks

**Comment by Izuzusama** [comment]
Ill try and take a look. Im new to polymer

**Comment by jarrodek** [comment]
It's just styling issue :)

**Comment by jarrodek** [comment]
I've fixed it in the repo. You can test it in beta.
