### ISSUE TITLE
The response is not shown in a way (Carriage return is missing)

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#634]
The response is not shown in a way (Carriage return is missing)

This makes it difficult to see what the response is containing.

{"movies":[{"id":"44001603","titleId":"About-Ray","parentId":"","movieName":"About Ray","genreName":"Drama","formattedLength":"0 minuter ","shortDescription":"About ....

![skarmavbild 2016-04-27 kl 11 41 51](https://cloud.githubusercontent.com/assets/13362021/14848246/1ec329fc-0c6d-11e6-83c0-d69116e5c0ca.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. The "parsed" tab name may be confusing. It should be "Highlighted". It is not changing response structure. It only highlights it.
As I can see it is a JSON response that is opened in a "parsed" panel. It means that the server did not send a content type correctly. If the content type is set to "application/json" (or any other */x-json) it will display the response in JSON viewer.

As tor now the parsed panel works as intended.

Thanks
