### ISSUE TITLE
Nothing can be copy from preview response

### ISSUE THREAD

**Issue by glaiseam** [jarrodek/ChromeRestClient#636]
Nothing can be copy from preview response

## Expected outcome
What should happen?
should be able to copy all data from preview
## Actual outcome
What happened?
cannot copy content using mouse pointer
## Versions
App: 7.9.29.179-stable
Chrome: 49.0.2623.110
Platform: Linux (-)

## Steps to reproduce
1. get a html response 
2. take response preview 
3.  try to copy some lines from that

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I can't reproduce the problem. Each response panel (raw, parsed, json and xml) supports text selection. 
If there is a text selection you can copy text using you'r system's commands.
It's a system operation - not app's. So I don't think I can be help here.

**Comment by jarrodek** [comment]
Previous release basically allows all text in the response panel to be copied.
