### ISSUE TITLE
Doesn't recover saved payload request

### ISSUE THREAD

**Issue by GroGz** [jarrodek/ChromeRestClient#643]
Data form payload is not refreshed

## Expected outcome
When you select a  saved request from Data form view, its payload data should be refreshed, as it happens OK with raw payload view .

## Actual outcome
When you fill a Data form payload and select an other saved request, old form data remains.

## Versions
App: 7.12.30.183-stable
Chrome: 50.0.2661.75
Platform: Windows (10)

## Steps to reproduce
1. Select request
2. Select data form payload view
3. Select another request
4. Data form payload is not updated

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I can confirm the behaviour.

Thanks.

**Comment by GroGz** [comment]
Thank you for your application!
