### ISSUE TITLE
local proxy settings not used, nor are there any options to set a proxy

### ISSUE THREAD

**Issue by SorenKlars** [jarrodek/ChromeRestClient#644]
Hi there,
thanks for a big overhaul, the tool looks good. 
The issue for me is that I can't set a proxy.

## Expected outcome
The tool should either apply the same proxy settings which were set in the browser/system, or allow to set a proxy manually.
Reason for me is to be able to record sessions in a ZAP Proxy or similar, but I'm sure there are other usecases.

## Actual outcome
no proxy is used, ARC is connecting directly to the target URL

## Versions
App: 7.12.30.183-stable
Chrome: 50.0.2661.87
Platform: Windows (7)

## Steps to reproduce
1. set up a proxy in Chrome, maybe even use the OWASP ZAP proxy port 8080
2. try to fire of your request, it is not showing up in the proxy
3. even if a not existing proxy port is set ARC is still working

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
As for proxy settings issues, please, refer to the issue #602 for detailed explanation.

I'm closing this as a duplicate.

Thanks.
