### ISSUE TITLE
Support content for GET requests

### ISSUE THREAD

**Issue by rtezli** [jarrodek/ChromeRestClient#647]
Some products (i.e. [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-filter-context.html) support/require a content body for GET requests)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I've discussed this topic here some time ago. The discussion ended up that according to HTTP spec the GET requests do not carry a payload and therefore it will not going to be added to the app. 
See the discussion here: http://stackoverflow.com/a/983458/1127848
I'm also against adding features that supports bad practices when building and testing APIs.
