### ISSUE TITLE
PUT operations returning 204 now crashes pop-out ARC

### ISSUE THREAD

**Issue by MikeHurleySurescripts** [jarrodek/ChromeRestClient#656]
Ever since my ARC upgraded itself to a newer/the latest version (that pops out to its own Chrome window), it is unable to handle PUT operations returning a 204 No Content status with an empty body.

An example screenshot:
![image](https://cloud.githubusercontent.com/assets/19266272/15113501/4b936f40-15ba-11e6-97fb-cae1a171352f.png)

## Versions
App: 7.12.30.183-stable
Chrome: 47.0.2526.111
Platform: Windows (7)

**Comment by jarrodek** [comment]
It was fixed couple of versions ago. When the app update itself it will work. As I can see you are using old version of the app (4 numbers behind).
