### ISSUE TITLE
JSON copy to clipboard is no longer being pretty-formatted

### ISSUE THREAD

**Issue by MikeHurleySurescripts** [jarrodek/ChromeRestClient#657]
The way JSON is being handled has changed with the recent ARC version(s) that pop out of Chrome instead of being in a Chrome tab.

## Expected outcome
After copying JSON to the clipboard with the copy button, pasting it should paste formatted JSON. It should not all be a single line even if that's what the raw value was.

## Actual outcome
JSON is copied to the clipboard as-is with no formatting done.

## Versions
App: 7.12.30.183-stable
Chrome: 47.0.2526.111
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I'm not sure what you means by it isn't working in new version. It is always using "raw" value to copy data to clipboard. It is actually an only source of the response message in the app. "Parsed" json is not actually a JSON object. It's a formatted HTML. And it isn't changed between upgrades.

As per this I'd be inclined to close this as WAI.

**Comment by MikeHurleySurescripts** [comment]
I think the way the Raw tab gets populated has maybe changed. A co-worker who still has the in-tab version gets formatted JSON in his Raw tab whereas in the standalone window newer version, my Raw tab shows unformatted JSON. This is result data from the same webservice, same REST endpoints.

**Comment by jarrodek** [comment]
I'm sorry. You are right. Previously the app took data from parsed and not raw data. It can be fixed.
