### ISSUE TITLE
Feature Request: add setting to allow running in a Chrome tab like previous versions

### ISSUE THREAD

**Issue by MikeHurleySurescripts** [jarrodek/ChromeRestClient#658]
I really liked running ARC in a Chrome tab. It's one of the reasons I kept using it instead of switching to Postman. I assume it was made to use a pop-out window because most people prefer that. Would it be possible to add a setting to ARC that tells it to use tabs instead of windows?

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
As for popup window issues, please, refer to the issue #510 for detailed discussion end explanation.

I'm closing this as a duplicate.

Thanks.
