### ISSUE TITLE
Can delete saved queries

### ISSUE THREAD

**Issue by barrybecker4** [jarrodek/ChromeRestClient#660]
I cannot seem to delete projects or queries within projects once created.

## Expected outcome
There should be a way to mange/delete projects and queries that they contain.

## Actual outcome
I don't see a way to do it.

## Versions
App: 7.16.33.191-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1.  create a query
2. save it in a project
3. try to delete it.

**Comment by philmagr** [comment]
Try clicking on the pencil that appears when you hover over a project on the left menu.

**Comment by jarrodek** [comment]
When you hover over the project name you'll see an edit icon:
![image](https://cloud.githubusercontent.com/assets/3320020/15162239/b7f19c32-16b6-11e6-8617-fb7171b0bec4.png)

There you can manage project and it endpoints: 
![image](https://cloud.githubusercontent.com/assets/3320020/15162262/db439a50-16b6-11e6-9c9b-db386a93aa86.png)

**Comment by barrybecker4** [comment]
Thanks. I was able to delete projects.
