### ISSUE TITLE
Feature request: Save vs Save As

### ISSUE THREAD

**Issue by philmagr** [jarrodek/ChromeRestClient#661]
Right now the app always assumes you are doing a save as, meaning that there is a pop-up window that I have to click through every time. Most of my saves are updating existing calls, new fields, db info, fixing things, etc.

Aside: The copy in the current dialog is a bit weird, particularly the way to save over an existing file. "Override" should probably be "Overwrite" - There is always a bit of hesitation when saving because override feels wrong, so I'm constantly double-checking to make sure I'm hitting the right button.
That's entirely possible to be just me, though. 

Edit: Removed comments about ctrl+S, because it appears to work. Not sure what I was doing when I determined it didn't.

**Comment by jarrodek** [comment]
Hi,

Thank for issue report.
I'm not sure if I understand you correctly. 
"Override" option will change the data you have restored from the database (saved request / project data). So basically it is changing restored data. I'm not a native speaker but it sounds right in terms of intention. If it's wrong word I can change it ;)

I don't understand rest of the message. When you press ctrl/cmd + S the save dialog will pop up. Depending on the initial state it will show you different modes:
* simple save - if current request wasn't restored from the database
* save or override - if current request was previously restored from the database

Save option (in first case) will save data as a new object.
Override (second case) will change currently saved object. Save as new (the same case) will create a new object in the database. 
It is exactly the same dialog an behavior as previously and I don't see issue here. Can you be more specific about it?

**Comment by philmagr** [comment]
"Override" is typically used to refer to something that you are bypassing.
Overriding security measures, so that you may take an action, for example.
If the context of the dialog was some sort of warning, you already have this file, Override might be appropriate.
I think that in this case, "Overwrite" is probably better text for that dialog.

The primary focus of the request:
Currently, the save option is similar to the "Save As" option in most editors (Take Microsoft Word as an example). It allows you to save as a different name, or under a different project.
I am requesting something similar to the plain "Save" feature from Microsoft Word, where it automatically saves the document to the location that you opened it.

This isn't how it worked before, and it bothered me then too, I was just too lazy to create an issue about it then. That's why I titled it Feature Request.

**Comment by jarrodek** [comment]
This was introduced in ARC v 8. You can save with "ctrl+s" to save current state to existing saved request or "ctrl+shift+s" to bring the "Save ad" dialog.
