### ISSUE TITLE
ARC seems NOT to use SSL Client Certificate

### ISSUE THREAD

**Issue by glfp** [jarrodek/ChromeRestClient#663]
I have a client certificate to access a server via SSL (a simple GET), but now (all works with all version) I receive a 

[chrome socket error]: An SSL protocol error occurred

## Versions
App: 7.16.33.191-stable
Chrome: 50.0.2661.87
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I think it is a duplicate of #466. Can you confirm that?

**Comment by glfp** [comment]
Yes, it's the same bug. Sorry for duplicate.
