### ISSUE TITLE
Dead zone on project sidebar menu

### ISSUE THREAD

**Issue by philmagr** [jarrodek/ChromeRestClient#666]
Clicking on the edges of the highlighted box does not open the project - it highlights the project in the sidebar, but I need to click on the same horizontal plane as the text in order to actually open the project's calls in the main window.

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report. I can't reproduce the problem. When I try to click project name it opens the project in the main window. It maybe some issue with [paper-menu](https://github.com/PolymerElements/paper-menu) instead?

**Comment by philmagr** [comment]
![image](https://cloud.githubusercontent.com/assets/17277967/15223864/327d5028-183c-11e6-82d8-62314c0fe246.png)

If you click on the red dot on the image, the project is highlighted, but the actual project doesn't open up.

**Comment by jarrodek** [comment]
OK, I get it. Thanks for an issue report.
