### ISSUE TITLE
No connection behind proxy possible since version 7.16.33.191

### ISSUE THREAD

**Issue by Bollerd** [jarrodek/ChromeRestClient#667]
Hi,

after the upgrade to the version 7.16.33.191 im unable to connect to any server that must be connected by a HTTP proxy

Before it worked.

A Socket connection is not available. The connection must be done by a normal HTTP proxy.

**Comment by JaredHatfield** [comment]
It is not working behind a proxy server for me as well.  I'm running version 7.16.33.191-stable

**Comment by jarrodek** [comment]
This is fixed by https://github.com/jarrodek/ChromeRestClient/commit/89973b258fe80f0bcc33814111917d6ef272617c

**Comment by WebDevJL** [comment]
Hello,

In which version is this fixed? I'm using v7.20.37.203 and I have the problem.
