### ISSUE TITLE
"The Response was empty" is returned when the response is 0

### ISSUE THREAD

**Issue by jguerra** [jarrodek/ChromeRestClient#670]
I have a web service that only returns numbers. If the number returned is 0 then the client says the response is empty. Other numbers show up as expected

## Expected outcome
I expect to the response to look like:
0

## Actual outcome
The actual response is "The Response Was Empty"

## Versions
App: 7.12.30.183-stable
Chrome: 50.0.2661.86
Platform: Mac OS X (10_9_5)

## Steps to reproduce
1. Make a GET request on a url that returns the number (not string) 0
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thanks for an issue report.
Can you paste the response headers returned by the server? And would be great if you can provide logs from request execution time.

**Comment by jguerra** [comment]
Hey,

The response headers look like

Date:
Thu, 12 May 2016 20:23:00 GMT
Access-Control-Allow-Origin:
*
Access-Control-Allow-Methods:
GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD
Access-Control-Allow-Headers:
Origin, Content-Type, Accept, Authorization, X-Requested-With,
Cache-Control, If-Modified-Since, Pragma
Access-Control-Expose-Headers:
Pragma, Location, Content-Type, Content-Length
Access-Control-Max-Age:
3600
X-Content-Type-Options:
nosniff
X-Xss-Protection:
1; mode=block
Cache-Control:
no-cache, no-store, max-age=0, must-revalidate
Pragma:
no-cache
Expires:
0
X-Frame-Options:
DENY
X-Application-Context:
application
Content-Type:
application/hal+json; charset=UTF-8
Transfer-Encoding:
chunked
Server:
Jetty(9.2.13.v20150730)

**Comment by jarrodek** [comment]
OK, so we moving forward.
There's no loop because there is no redirection. It means that there is some issue with the app itself (like parser error).
Can you see any error message in log viewer?

**Comment by jguerra** [comment]
I'm not seeing any new entries in the logs caused by this request

**Comment by philmagr** [comment]
Oops, this is probably the same as the bug I just posted - https://github.com/jarrodek/ChromeRestClient/issues/705 
I think somewhere is just looking for javascript "falsy" values and interpreting them as an empty response.

**Comment by jarrodek** [comment]
This issue has been fixed with #705
