### ISSUE TITLE
Slash added to end of URL

### ISSUE THREAD

**Issue by Kelmar** [jarrodek/ChromeRestClient#671]
ARC is adding a slash at the end of URLs if it thinks one should be added.

For example, if the user puts in:
http://localhost/myEndPoint

ARC is sending the following URL to the server:
http://localhost/myEndPoint/

ARC should not assume that slashes should be added at the end of any URL.

## Versions
App: 7.16.33.191-stable
Chrome: 50.0.2661.94
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I can't however reproduce an issue. I tried just a moment ago a request to randomly selected endpoint: `http://httpbin.org/cookies` (no slash at the end).
Debug from console:

> Created socket 4
> Connecting to httpbin.org:80
> Connected to socked for host:  httpbin.org  and port  80
> Generated message to send
> GET /cookies HTTP/1.1
> HOST: httpbin.org
> 
> Sending message.
> Written message. Bytes sent: 44

As you can see in the line `GET /cookies HTTP/1.1` the request path is `/cookies` and not `/cookies/` so it WAI. In this case I'd close this issue with this status.

**Comment by Kelmar** [comment]
I unfortunately cannot add a screen shot.

However, in the request HOST field I have:
http://localhost/HydraService/OnlineBanking.ashx/LogonUserWithCookiesUuxJs

(With no trailing slash)

With some post data.

My server is very clearly receiving this URL with the / added at the end.  This did not happen previously until the client was updated today.  (Other rest clients do not have this problem.)

Further the history section shows the trailing slash in my attempts.

**Comment by Kelmar** [comment]
Figured out how to do a screen shot:

Request:
![request](https://cloud.githubusercontent.com/assets/2845582/15230257/61321818-185a-11e6-9b6d-d5a0f340459c.png)

History:
![history](https://cloud.githubusercontent.com/assets/2845582/15230263/6d6cf864-185a-11e6-9e86-1ed9d72b863c.png)

**Comment by jarrodek** [comment]
Hi again.

Please, paste full URL into the regular form. You pasted the URL into HOST value of the url in the detailed form. So it treats it as a host value instead of URL. Just click on the dropdown on the left from the field.
