### ISSUE TITLE
net::ERR_CONNECTION_REFUSED message wording

### ISSUE THREAD

**Issue by meharg** [jarrodek/ChromeRestClient#674]
Error message when URL can't be reached needs correction.

## Expected outcome
Error should say "The requested URL **can't** be reached"

## Actual outcome
Error message is incomplete.  Says "The requested URL be reached"

## Versions
App: 7.18.36.199-stable
Chrome: 50.0.2661.102
Platform: Windows (7)

## Steps to reproduce
1. Make GET call to http://localhost:8080/nonexistent
2. Observe error message

**Comment by jarrodek** [comment]
Thanks for pointing this out.I'll fix this.
