### ISSUE TITLE
cant preview html response

### ISSUE THREAD

**Issue by davidkarn** [jarrodek/ChromeRestClient#676]
Your description here

View parsed html is useless now. I can only see a small strip with the actual content

## Expected outcome
What should happen?

Allow me to scroll the entire page

## Actual outcome
What happened?

Page shows up in a one-line-height scrollable view

![screen shot 2016-05-17 at 10 02 25 am copy](https://cloud.githubusercontent.com/assets/3698908/15331601/eebf8d54-1c16-11e6-93e6-6280b5f29842.png)

## Versions
App: 7.18.36.199-stable
Chrome: 50.0.2661.102
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 
Will it be able to send me a HTML you want to display? With changed data but I need something to test it because I can't reproduce a problem here.

**Comment by dfgrumpy** [comment]
I see the same thing when going from an parsed html response then clicking on the preview button.  The display collapses to a tiny windows that is barely scrollable. It appears to only happen if the html is just a snippet.
