### ISSUE TITLE
can not whit cookie

### ISSUE THREAD

**Issue by DoHello** [jarrodek/ChromeRestClient#678]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.18.36.199-stable
Chrome: 47.0.2526.106
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I'm not sire what it is about. Can you clarify?

**Comment by DoHello** [comment]
Hi
I find this http request did not carry sessionID . now I think i find the problems about arc , i did not use xhr. thinks

发自我的 iPhone
