### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by samuel-phan** [jarrodek/ChromeRestClient#680]
It would be great if we had some keyboard shortcuts!

At least, to **Send** the request. I was thinking naturally to `Ctrl-R` or `F5` for that. Maybe `Ctrl-Enter` as well.

Thanks!

**Comment by jarrodek** [comment]
Hi,

Thank you for feature request.
I agree with you, it could be helpful. 
Any chance you'd be able to code it and send PR?

**Comment by samuel-phan** [comment]
That'd be a pleasure, but unfortunately, I'm a backend dev, and my skills with JS are non-existent :laughing:

**Comment by jarrodek** [comment]
I see :) I'll try to fit it in next update release.
