### ISSUE TITLE
History updates request instead of adding new ones

### ISSUE THREAD

**Issue by pafuent** [jarrodek/ChromeRestClient#681]
In the previous version of ARC, when you sent a request, that request were automatically saved in the History. If I modified some part of it (URL, GET parameters, Body, Headers, HTTP verb etc), the new request were added to the History as a new entry. In the current version, the record in the History is updated. After some debugging, I found that the key that you use to add new entries to the History is URL, instead of some kind of hash of the internal Request object that ARC manages. I really loved the way in which ARC behaves before the new version.
There is a way to get that behaviour again as default or as a configuration option?

**Comment by pafuent** [comment]
#683 Seems to be the same issue

**Comment by jarrodek** [comment]
See my response for #682
