### ISSUE TITLE
History not maintained

### ISSUE THREAD

**Issue by ishant-barnwal** [jarrodek/ChromeRestClient#682]
If there are several requests sent at the same end point continually, the ARC only preserves the last one.
## Expected outcome

I would expect all my requests to be in the history section.
## Actual outcome

Only the last request for that end point was there.
## Versions

App: 7.20.37.203-stable
Chrome: 50.0.2661.102
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Requests are recognizable as http method and the URL but not by headers or payload.
In fact all the requests are there but there is no UI to show it (it would take some time to code it and right now I don't have this time). 
I'm redesigning some things in the app so I guess it could be included in future release.

**Comment by ishant-barnwal** [comment]
Could you give an EDA for this?

**Comment by jarrodek** [comment]
I don't want to declare any deadline as just yet. Really soon I'll complete the roadmap for the app and I'll publish it. Then you'll be able to see what feature / change will come to the app.
I'm planing to update roadmap next week.

**Comment by ishant-barnwal** [comment]
Thanks..

**Comment by jarrodek** [comment]
History has changed and now it records every hit.
