### ISSUE TITLE
can not modify the textarea of RawPlayload 

### ISSUE THREAD

**Issue by Jackcu** [jarrodek/ChromeRestClient#685]
![image](https://cloud.githubusercontent.com/assets/6947638/15598726/a50478e0-240f-11e6-985d-71089ae72508.png)

I can not modify the textarea of RawPlayload when I come it from saved list.

## Versions
App: 7.18.36.199-stable
Chrome: 50.0.2661.102
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report. Not sure if I understand correctly. If the content of it is not changing when you opening the request from saved?

**Comment by Jackcu** [comment]
Yhat's exactly what I mean

**Comment by Jackcu** [comment]
Yes,that's exactly what I mean

**Comment by jarrodek** [comment]
I can't reproduce the problem on current version (7.20...). Your version is outdated. Please, update the app and try again.
