### ISSUE TITLE
On 303 Redirect method wrong

### ISSUE THREAD

**Issue by silversmurf** [jarrodek/ChromeRestClient#688]
Hi, great job on a great tool!

When doing a POST for example and the response is **303 See Other**, it makes a redirect to the "location" provided in headers, but you have to use the method GET for redirection URI, not POST again.
[https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.4](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.4)

## Expected outcome
Redirect with a GET to new location

## Actual outcome
Redirect with a POST to new location

# Versions
App: 7.20.37.203
Chrome: Stable 51.0.2704.63 m

# Steps to reproduce
Prepare: Server with 2 APIs (e.g.):
1. addCustomer [allowed: POST or PUT]
2. getCustomer [allowed: GET]

Execute
1. Send a POST with json content to `addCustomer`
2. Receive `303 See Other` with new `location` parameter in header (`getCustomer`)

**Comment by jarrodek** [comment]
Hi,

Thanks for the issue report.
I've created an issue in the transport library: https://github.com/jarrodek/socket-fetch/issues/13
It will be addressed and included in next release.
