### ISSUE TITLE
Why is ARC putting all headers in lower case?

### ISSUE THREAD

**Issue by comettrouble** [jarrodek/ChromeRestClient#693]
I've been using ARC for about a year. there was an update to in a couple of weeks ago and i noticed that i could not log in any more to our webapi. did a little checking a figured out that the headers are being put into lower case which is why it stopped working. Is there  a way to turn this off? and why did you guy or guys (what ever) change this?

**Comment by jarrodek** [comment]
This is duplicate of #491
