### ISSUE TITLE
Why is ARC putting all headers in lower case?

### ISSUE THREAD

**Issue by comettrouble** [jarrodek/ChromeRestClient#694]
Your description here
headers are being lower cased
## Expected outcome
What should happen?
reverse this change or some way to turn this off.
## Actual outcome
What happened?

## Versions
App: 7.20.37.203-stable
Chrome: 50.0.2661.102
Platform: Windows (7)

## Steps to reproduce
1. call a webapi that checks headers for authentication in which it checking for headers with capital letters in it.
2. 
3.

**Comment by jarrodek** [comment]
This is a duplicate of #491
