### ISSUE TITLE
I hate that this is it's own window ... I like when it was just another browser window

### ISSUE THREAD

**Issue by MichaelGreco** [jarrodek/ChromeRestClient#697]
Your description here
I hate that this is it's own window ... I like when it was just another browser window

## Expected outcome
What should happen?
When i start restclient it just starts in a new browser tab ...

## Actual outcome
What happened?
Another window that then gets lost among the other 10 i have open become a pain to find. If it stays a browser tab then it's much easier to locate.

## Versions
App: 7.20.37.203-stable
Chrome: 50.0.2661.102
Platform: Mac OS X (10_9_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.
As for popup window issues, please, refer to the issue #510 for detailed discussion end explanation.

I'm closing this as a duplicate.

Thanks.
