### ISSUE TITLE
Cookies are not destroyed

### ISSUE THREAD

**Issue by hadriengerard** [jarrodek/ChromeRestClient#701]
Cookies - like session ID cookies - are not destroyed when asked by the server.

## Example

After sending a 'log out' request, the server response contains the following header:
  `Set-Cookie: session=; Max-Age=-86400; Expires=Wed, 08 Jun 2016 09:50:30 GMT; Path=/; HTTPOnly`

### Expected outcome

The 'session' cookie should be destroyed and not be sent with the next requests.

### Actual outcome

Following requests contain the 'session' cookie.

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.84
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
It looks like the cookie store do not remove cookies when the time expired. It should be fixed.

**Comment by darkennight** [comment]
This issue seems to be in the latest version again.
Set-Cookie header with expire date some when in the past are not destroyed and resend with the next request.

App: 9.14.64.305-stable
Chrome: 59.0.3071.115
Platform: Windows (10)
