### ISSUE TITLE
Recover user data (question) 

### ISSUE THREAD

**Issue by jerrygb** [jarrodek/ChromeRestClient#708]
Hi,

Any directions on retrieving old session data? 

I had uninsulated the extension and reinstalled the later version. :(

Thanks

**Comment by jarrodek** [comment]
Hi,

If you uninstalled the app, locally stored data was removed with it. The app is not storing data remotely so there's no backup. If you saved your requests to Google Drive you can open them from it. But besides it there's nothing I can do.

As per your description and my answer I'd be inclined to close this issue and WAI.
