### ISSUE TITLE
WebSocket Reconnect handling should be a setting

### ISSUE THREAD

**Issue by Timothy-Budzinski** [jarrodek/ChromeRestClient#711]
If a WebSocket is disconnected, automatically reconnecting should be a setting controlled by the User.  I have cases where I'd like to test to make sure that the Web Socket connection is rejected using tokens passed in messages/timeout logic.

What should happen?
Either on the screen or in the settings, there should be a way to control this so I can set it to just allow it to be disconnected, I can either then reconnect myself by clicking the connect button or move on my merry way.

## Actual outcome
When the Server force closes the web socket connection, the client freaks out and immediately tries to reconnect and immediately gets into this disconnected/reconnect/get disconnected/reconnect cycle hell.  Killing the App is the only way to stop it

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.84
Platform: Windows (7)

## Steps to reproduce
1.  Create a Web Socket Server that onConnect closes the client
2.  Use the client to connect to said Web Socket in 1
3.  Watch the application freak out

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report. It seems to be a valid idea and solve this use case. I'm working on major changes in the app so it may take some time to implement the change. You can send a PR if you're able to code the change.
