### ISSUE TITLE
Chrome rest client changes headers to lowercase

### ISSUE THREAD

**Issue by amazurok** [jarrodek/ChromeRestClient#713]
I use ChromeRestClient and for some application it doesn't work. I found that it internally change headers to lowercase.
Example:
I set header
Authorization: fc0d81a4585d4970e6f8d5afbf518d335afcb226
at the end app I saw:
authorization: fc0d81a4585d4970e6f8d5afbf518d335afcb226
i.e first letter of "Authorization" was lowercased

## Expected outcome
ChromeRestClient should not change header

## Actual outcome
"Authorization" was lowercased

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.103
Platform: Windows (7)

## Steps to reproduce
1. Set header Authorization: _any_text_
2. Use TCP/IP monitor or any other proxy 
3. View that headers sent to aplication is lowercased

**Comment by jcpowermac** [comment]
I am experiencing the same issue.

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.103
Platform: Mac OS X (10_11_4)

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491for detailed discussion and explanation. I'm closing this as a duplicate. 

Thanks.
