### ISSUE TITLE
Content-type header is being changed during request.

### ISSUE THREAD

**Issue by SimpleCold** [jarrodek/ChromeRestClient#714]
Please, make a setting if someone wants to have his content-type overriden.
## Expected outcome

When I send file contents with content type: application/octet-stream, it should be sent as octet-stream.
## Actual outcome

It gets sent as multipart/form-data
## Versions

App: 7.20.37.203-stable
Chrome: 53.0.2764.0
Platform: Windows (7)
## Steps to reproduce
1. Set content-type
2. Select a file
3. Send

**Comment by klinki** [comment]
:+1: I have the same problem.

**Comment by jarrodek** [comment]
Hi,

Right now the app do not allow sending files this way. It only uses form style to send files. It is however in the roadmap to send binary data. I can't provide specific timing for this right now because I'm working on different parts of the app.

**Comment by jarrodek** [comment]
This is now delivered in the app
