### ISSUE TITLE
Allow me to turn off pointless menu/button animations

### ISSUE THREAD

**Issue by LegalizeAdulthood** [jarrodek/ChromeRestClient#718]
These animations serve no purpose and just slow down interaction with the application and distract me from what I am trying to do.  Just let me click on the buttons and have the menus popup immediately.  Give me an option to turn this useless stuff off.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
The UI is part of the material design and [paper-* elements](https://github.com/PolymerElements). I have no direct impact to its development and how elements works. You can file an issue report in paper elements repository. Therefore there will be no change in the app's behaviour and it works as intended.
