### ISSUE TITLE
Cql is cut when I choose ENCODE PAYLOAD

### ISSUE THREAD

**Issue by SaraIsraeli** [jarrodek/ChromeRestClient#727]
Hi,

When I choose ENCODE PAYLOAD, my cql is cut.

My cql:
tq=select convert(char(4),year) as year
, month , sum(items_published) as total_items
, count(distinct creator) as total_creators , sum(case when publisher_ind = 0 and pb_author_ind = 0 then items_published end) as community_items
, sum(case when publisher_ind = 0 and pb_author_ind = 0 then 1 else 0 end) as community_creators , sum(case when publisher_ind = 1 then items_published end) as publisher_items
, sum(case when publisher_ind = 1 then 1 else 0 end) as publisher_creators , sum(case when pb_author_ind = 1 then items_published end) as pb_author_items
, sum(case when pb_author_ind = 1 then 1 else 0 end) as pb_author_creators , (sum(items_published))*1.00/(count(distinct creator)) as total_avg
, (sum(case when publisher_ind = 0 and pb_author_ind = 0 then items_published end))*1.00/(sum(case when publisher_ind = 0 and pb_author_ind = 0 then 1 else 0 end)) as commuity_avg
, (sum(case when publisher_ind = 1 then items_published end))*1.00/(sum(case when publisher_ind = 1 then 1 else 0 end)) as publisher_avg
, (sum(case when pb_author_ind = 1 then items_published end))*1.00/(sum(case when pb_author_ind = 1 then 1 else 0 end)) as pb_avg 
from (
select c.year as year
, c.month as month
, c.[Nickname] as creator
, c.publisher_ind as publisher_ind
, case when d.[realName] is not null then 1 else 0 end as pb_author_ind
, c.items_published as items_published 
from (
select a.year as year
, a.month as month
, a.[Nickname] as [Nickname]
, case when b.[articleCreatorName] is not null then 1 else 0 end as publisher_ind
, a.items_published as items_published 
from (
select datepart(yyyy, convert(Date,[originalPublishDate])) as year
, datepart(mm, convert(Date,[originalPublishDate])) as month
, [Nickname]
, count(*) as items_published
from external.playbuzzBI.view_GamesJoinPermissions
where (ReviewStatus = 'unblocked' or ReviewStatus is NULL)
and [GameName] not like '%preview%'
and Published = 'true' AND [PatternId] NOT IN ('OpenList','AbstractFormat') group by datepart(yyyy, convert(Date,[originalPublishDate])), datepart(mm, convert(Date,[originalPublishDate])), [Nickname]
) as a left join (
select [sessionParentHostDomain] , [articleCreatorName] 
from external.playbuzzBI.PartnerCreators
) as b on a.[Nickname] = b.[articleCreatorName] 
where a.year = 2016
) as c left join (
select [nickname]
, [realName]
, [userType]
from external.playbuzzBI.PlaybuzzAuthors
) as d on c.[Nickname] = d.[nickname]
) as e group by year, month
order by year, month 

can you help me to understand the issue  please?

![image](https://cloud.githubusercontent.com/assets/20552877/16978253/b398a1c8-4e63-11e6-88f1-2b9b294670db.png)

Thanks, Sara.

**Comment by jarrodek** [comment]
Hi,

I'm not sure what may happening in your case but I can't reproduce the problem. Wherever I try to encode the payload in the raw field or in the form editor it succeed and the payload is encoded properly.
I used text that you have added to the issue report. Is there anything else that may help me reproduce the problem?


Thanks

**Comment by SaraIsraeli** [comment]
sorry, but all details appear in picture that I attached.
The problem reproduces also in other computers.
please add your picture of reproduces experience.
thanks, sara.

**Comment by jarrodek** [comment]
Oh, I'm sorry. I tested it on the beta app which has issue with `x-www-form-urlencoded` params fixed already. In stable app (the one you are using) it's still not fixed. The update is on the way and will be published in coming days.
