### ISSUE TITLE
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED when pinging a HTTPS BasicAuth WebService

### ISSUE THREAD

**Issue by el-schalo** [jarrodek/ChromeRestClient#730]
Advanced REST client (BETA from 2016/07/26!) brings up 

> The requested URL can't be reached
> The service might be temporarily down or it may have moved permanently to a new web address.
> net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED

when GET or HEAD to an webservice endpoint which works(!), when entered to the chrome address bar directly.

Neither prefixing "username:password@" to the URL nor adding a authorization header field ("Basic TXlVc2VyTmFtZTpNeVBhc3NXb3Jk") helps. Best would be just to ask for user authentication.

**Comment by jarrodek** [comment]
Hi,

Thanks you for issue report.
Can you try switch to "use XHR" in the request view and check if this helps? 
According to your description this is not app's issue but Chrome's. You can try report it to the Chrome team referencing this bug.  
In this case i'd be inclined to close it as wontfix.

**Comment by Shagrat2** [comment]
Hello
I get ERR_SSL_CLIENT_AUTH_CERT_NEEDED
Hrome Get this page normaly, but ARC show error,
if switch On XHR - request ok

**Comment by jarrodek** [comment]
That was the point of putting this button in the request panel @Shagrat2 . Normally Chrome apps can't pass chrome security if there's a certificate error. It's only allowed for websites (and therefore for extensions).
