### ISSUE TITLE
Parsed output is not really parsed

### ISSUE THREAD

**Issue by DasJott** [jarrodek/ChromeRestClient#731]
It is the same as in Raw view, just green colored.
Shouldn't it be more readable?

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. It means that the app didn't recognised the response as a JSON response. This means that there were no proper Content-Type header set for the response. I can guess it's something like `text/html` and this is what the app is trying to highlight (markup source). If the server returns correct content type then you'll have full support for syntax highlighting.

I'm inclined to close this issue as WAI.

**Comment by DasJott** [comment]
Will test it tomorrow and provide response.

**Comment by jarrodek** [comment]
Thank you.

**Comment by DasJott** [comment]
Sorry for being late!
You were right. If content-type is correct, it is beautifully parsed!

So a well known, big company does not send correct headers... :D

**Comment by DasJott** [comment]
...and thank you for the app!

**Comment by jarrodek** [comment]
No problem.

Every kind of company can make a mistake ;)

And thanks for using it :)
