### ISSUE TITLE
Received data is a binary file

### ISSUE THREAD

**Issue by goodnewzevery1** [jarrodek/ChromeRestClient#735]
We have many requests that return text files. 

In previous versions of ARC the contents of the file would be displayed in the response window, but now it prompts to save the file and open in order to view.

Viewing in the window is more convenient when quickly testing several requests. 

Is there a setting to switch back so it can be viewed directly in the window? 

If no, is it possible to restore the previous functionality as an option?

**Comment by jarrodek** [comment]
Hi,

Can you please tell me what's the content type of the response? The binary view is only visible when the file is actually a binary file and therefore there's nothing to see in it. It shouldn't treat text files as a binary files though.  What is the content type of the response?

**Comment by goodnewzevery1** [comment]
Upon reviewing the server code I need to revise my statement regarding the return type of this call. 
Our client app converts the response into a text file, but the server is actually returning "application / octet-stream". The server is Java based and produces a file containing SQL statements , which is read into a byte array. The byte array is then returned as the response. 

Currently, ARC prompts for the save which makes a log file containing the SQL statements.

I believe that in this past the Response view showed the SQL statements without needing to export to the log file.

**Comment by jarrodek** [comment]
So there is an update almost ready (currently [beta channel](https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel) has it) where the "raw" view is always displayed regardless the response content type. I guess it will fix this issue.

**Comment by goodnewzevery1** [comment]
That is good news! Thank you
