### ISSUE TITLE
Need to have chrome session in Rest client as well similar to older version

### ISSUE THREAD

**Issue by kvnaveen7** [jarrodek/ChromeRestClient#737]
Your description here
Need to test my post request after logging in. I logged in to google chrome and i tried my api request in Rest client but it showing user not logged in. Is there any way to file my post request after loggin in.
## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.26.44.220-stable
Chrome: 51.0.2704.103
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Please, Use the "Use XHR" switch above the request panel (requires installation of additional extension) to proxy the request through Chrome. Then it should work as in old version.
