### ISSUE TITLE
HEAD after POST with body

### ISSUE THREAD

**Issue by ikenfin** [jarrodek/ChromeRestClient#746]
Hello!
If i use POST query with filled body, and then switch to HEAD and trying send request, arc trying to send this body, so i getting this `Request with GET/HEAD method cannot have body.`

Thanks!

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
The component that creates a request object is not checking if the request can have a body but the library that is making a request is checking for it. So it the form contains the body it sends it anyway even if the form controls are hidden and shouldn't be used.
I'll fix it soon.

**Comment by jarrodek** [comment]
This issue was fixed by https://github.com/jarrodek/ChromeRestClient/commit/f8e794289bb947526796b333d002b00bb7c609c4

**Comment by ikenfin** [comment]
Awesome! Thanks!
