### ISSUE TITLE
OSX PUT not sending params

### ISSUE THREAD

**Issue by sabbaka** [jarrodek/ChromeRestClient#747]
## Expected outcome
What should happen?
Server should received PUT params from ARC
## Actual outcome
What happened?
Server not received any params
## Versions
App: 7.29.44.223-stable
Chrome: 52.0.2743.116
Platform: Mac OS X (10_11_6)

## Steps to reproduce
1. Open ARC
2. Send PUT request to any API which will print input from request - I have used Laravel, PHP.
3. Print input from request - and it's empty

I have done the same thing using CURL from console - and it works fine, server receive's params. It worth me a day to find out.

**Comment by sabbaka** [comment]
The problem was because of file field with image which I have not noticed was active

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
There is a counter for attached files in the UI. It may be less visible but that's the point since it's not very important status message on daily basis. 
I do, however, recognise an issue here and I'll address it by adding a visual indication that there are some files attached with the request.

**Comment by sabbaka** [comment]
Hello, thanks for reply, yes, I just have no recognized that I also had the
file attached - I thought it would be removed automatic - like params if
you switch GET to POST - so probably if PUT is not sending files it's
better to clean this part if you switch to PUT from POST - because,
obviously, I have used files in POST while testing register.
Thanks a lot for this super cool plugin, we are using it a lot everyday.

2016-08-22 14:35 GMT+03:00 Paweł Psztyć <notifications@github.com>:
