### ISSUE TITLE
Spelling of Method is wrong in Helptext

### ISSUE THREAD

**Issue by thecooltester** [jarrodek/ChromeRestClient#764]
The spelling of Method is wrong in the Method Name helptext. Please find attached screenshot.
![arc_method](https://cloud.githubusercontent.com/assets/5021118/17925899/6e80f8a0-6a0c-11e6-9281-1a4d8860e1a9.png)

**Comment by jarrodek** [comment]
If was fixed in https://github.com/jarrodek/ChromeRestClient/pull/745
The app will be updated soon.
