### ISSUE TITLE
HelpText mixup in Method name field

### ISSUE THREAD

**Issue by thecooltester** [jarrodek/ChromeRestClient#765]
A helptext mix-up happens in the Method name field after processing a request. Please find attached screenshot.
![arc_text mixup](https://cloud.githubusercontent.com/assets/5021118/17925948/aa1d9328-6a0c-11e6-9c0a-8d3e5286da76.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for the report. I can't reproduce the problem. It is working as intended on my test machines. What's your Chrome version?

**Comment by thecooltester** [comment]
Hi,

My Chrome version is 52.0.2743.116 m (64-bit).

Thanks,
Ritesh

**Comment by jarrodek** [comment]
I've updated polymer elements. It looks like an issue with it. New version (on its way) will contain updated version of this component.
