### ISSUE TITLE
Plan for deprecation of Chrome Apps?

### ISSUE THREAD

**Issue by pioto** [jarrodek/ChromeRestClient#767]
It seems that Google has shifted strategies on Chrome Apps:

http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

As I understand it, Advanced Rest Client is now packaged as an App (IIRC, it used to be an extension).

Are there any plans to accommodate Google's shift in the platform?

**Comment by jarrodek** [comment]
Hi,

I read it and I'm working on it right now.
I've already started project re-modulation so it will be easier to move different parts of the app to other tools / platforms. 
I was considering Electron and going native some time ago and  I'm preparing to this step. Legacy apps removal from CWS delayed work on that issue.
I still have at least a year to update an app so I don't feel pressure right now. However the change is planned.

**Comment by jarrodek** [comment]
Electron app is now created. But because the code is not yet signed I'm not going to publish installation URL as for now. I'll publish this information very soon here, on the blog and in the application.
