### ISSUE TITLE
Make "Clear All" icon more obvious

### ISSUE THREAD

**Issue by DanielLanger** [jarrodek/ChromeRestClient#769]
It would be great if the clear all icon was replaced with one that better indicates the button is a clear button. 

It isn't immediately obvious and i've accidentally clicked it more than once and lost all of my work. I

If this can't be changed, at least allow for the clear to be undone using cmd-z

Thanks!

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. The icon is quite obvious for Android users ;) But I understand it. 
I rather won't change the icon but I guess `cmd+z` + tooltip do the work.
