### ISSUE TITLE
ctrl+f opens find dialog on mac

### ISSUE THREAD

**Issue by davidkarn** [jarrodek/ChromeRestClient#770]
## Expected outcome
What should happen?
hitting ctrl-f on mac is the keyboard shortcut for moving the cursor forward one character. command+f is the shortcut for opening a find dialog. it should move the cursor forward

## Actual outcome
What happened?
the default behavior is stolen and it  opens a find dialog

## Versions
App: 7.29.44.223-stable
Chrome: 52.0.2743.116
Platform: Mac OS X (10_11_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Both commands are enabled all the time in all platforms. I guess it could be more platform specific to not confuse anyone.
