### ISSUE TITLE
411 on POST

### ISSUE THREAD

**Issue by firelizzard18** [jarrodek/ChromeRestClient#777]
I can't get POST requests to work. I'm trying to test an ASP.NET MVC application. I am using Negotiate with a fallback to NTLM.

## Expected outcome
I post to <some URL> and I get a 200 with JSON

## Actual outcome
I post to <some URL> and I get a 411

## Versions
App: 7.31.45.225-stable
Chrome: 53.0.2785.89
Platform: Windows (10)

## Steps to reproduce
1. Create new request
2. Enter in URL
3. Select POST
4. Select application/json
5. Enter Content-Length: 0
6. Send
7. (On first request) Enter username and password for NTLM

**Comment by codepb** [comment]
I have the same issue. It makes the application completely unusable when working with an api which requires NTLM auth. This is a shame, because this is the only tool I've found so far that supports NTLM auth for testing APIs

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
The app is supporting NTLM. However you hound a bug in the transport library. It clears request body when negotiating with server and final request do not have body part.
It's a bug and it needs a fix.
