### ISSUE TITLE
Double response on any requested endpoint.

### ISSUE THREAD

**Issue by weizhonglai** [jarrodek/ChromeRestClient#778]
I found this when I troubleshooting my local api. The expected output from ARC should be X(in plain text) and I saw XX. Then I try with external working url like GET https://www.airbnb.com, I am also seeing double response on the html. It only happen on the first trial, second request will be OK(no double).

If the response in JSON, then it will be fine.

## Expected outcome
It should not show double response.

## Actual outcome
It show double response on the first request.

## Versions
App: 7.31.45.225-stable
Chrome: 52.0.2743.116
Platform: Windows (8.1)

## Steps to reproduce
1.  GET https://www.airbnb.com
2.  Check on the response in Raw/Parsed tab on the bottom.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. I can confirm this behaviour and it's a bug. Later I'll schedule it for the fix.
