### ISSUE TITLE
ARC is converting headers to lower-case text

### ISSUE THREAD

**Issue by j6mes** [jarrodek/ChromeRestClient#780]
ARC converts some headers to lower-case. Have verified that it is only ARC causing this by comparing results to CURL

## Expected outcome
Authorization header should be posted with an upper-case A.

## Actual outcome
Authorization header has a lower case header

# Versions
7.31.45.225-stable

# Steps to reproduce
1. Posting Authorization header to a simple php web page with print_r(apache_request_headers());

![image](https://cloud.githubusercontent.com/assets/7656957/18226614/b1e5bac6-7205-11e6-8b66-3f561c33b048.png)

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491 for detailed discussion and explanation. I'm closing this as a duplicate. 

Thanks.
