### ISSUE TITLE
Automatically playing music on website

### ISSUE THREAD

**Issue by veeti** [jarrodek/ChromeRestClient#781]
Please don't do this.

**Comment by frederikb** [comment]
Completely unexpected and undesired behavior! 

It also makes the website unusable for mobile usage, unless you like the idea of annoying people all around the poor sob scrambling to find out why his phone is blasting out music.

**Comment by jarrodek** [comment]
Not sure I understand. Are you on right repository? The app has nothing to do with playing a music..

**Comment by frederikb** [comment]
https://advancedrestclient.com/ is playing music.

![arc_tab_screenshot](https://cloud.githubusercontent.com/assets/232148/18270126/afcd3e94-742b-11e6-9c11-ad9d63f278d8.PNG)

To be exact: The following video file which automatically plays when visiting the website mentioned above includes very loud music: https://advancedrestclient.com/images/hero-video.mp4

**Comment by jarrodek** [comment]
Hmmm. The video is muted on the website and should not be played. Can you actually hear the music?

**Comment by frederikb** [comment]
Yes, I can confirm the audio playing on both Firefox Mobile on Android 49.0 and Firefox for Windows 48.0.2. 
I recommend simply removing the unnecessary audio track from the file itself.

**Comment by jarrodek** [comment]
Definitely I'll do this. 
Thanks for the issue report.

**Comment by jarrodek** [comment]
This is fixed now. 
You need to clear cache first.
