### ISSUE TITLE
Broken Roadmap link on advancedrestclient.com

### ISSUE THREAD

**Issue by vassyz** [jarrodek/ChromeRestClient#782]
The roadmap link points to https://github.com/jarrodek/ChromeRestClient/ROADMAP.md, which returns a 404 page. The actual ROADMAP.md file can be found on the develop branch: https://github.com/jarrodek/ChromeRestClient/blob/develop/ROADMAP.md

**Comment by jarrodek** [comment]
Thanks for reporting this!

**Comment by jarrodek** [comment]
This is fixed now.
