### ISSUE TITLE
Add Google Drive folder selection

### ISSUE THREAD

**Issue by zakharsk** [jarrodek/ChromeRestClient#784]
If possible it will be cool to save files not to GDrive root but to:
`gdrive_root/ChromeRestClient/ProjectName/RequestName.arc`
folder.
## Versions

App: 7.31.45.225-stable
Chrome: 53.0.2785.89
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi,
In previous version it was possible to select folder where the file was saved. However, after many users complains about extended permissions to Drive files I decided to remove this option and reduce number of permission required by the app when authorizing it with Drive.

I'll take a look at the new Drive API (v3) and see if there's anything I can do about it without extending permissions. If not I don't want to change permission for the app.
