### ISSUE TITLE
Parsed response is displaying the raw response doubled

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#800]
For example, the following raw response:
+------------------------------------------------------------------------------------------------------------------------------+
| name                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------+
| "×××× 120x180 ×¡"×, 4A4"                                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------+
1 rows

**Comment by jarrodek** [comment]
Hi,

Which version of the app are you using right now? It was fixed and released yesterday.

**Comment by jarrodek** [comment]
Duplicate of the #778
