### ISSUE TITLE
New History list popup does not go away

### ISSUE THREAD

**Issue by vamsiannem** [jarrodek/ChromeRestClient#803]
On the history tab, the pop-up "New history list" does not go away when i click the close button. 

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.36.47.237-stable
Chrome: 52.0.2743.116
Platform: Windows (10)

## Steps to reproduce
1. Go to history tab
2. Click "Close" button on the pop up shown.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
Can you see any error log in the output console? You can try [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app or use Logs viewer in the dropdown menu in left panel.

I can't reproduce the problem and it seems to work fine.

**Comment by vamsiannem** [comment]
When i closed the Advanced rest client and open again, it seems working fine. Not sure why there was a problem earlier.
