### ISSUE TITLE
Parsed JSON view should display commas

### ISSUE THREAD

**Issue by apapsch** [jarrodek/ChromeRestClient#805]
Viewing a JSON response within ChromeRestClient is fine. It's nicely formatted. I'd like to be able to copy portion of JSON object (e.g. an embedded object) from that view. There's no problem with copying itself, however the nicely formatted view does not display commas, thus producing invalid JSON.

I could copy the whole raw JSON and paste it e.g. to jsonformatter.com and then copy the part I want. But that is inconvenient. It would be great if I could just copy valid JSON from the parsed view.

**Comment by jarrodek** [comment]
I think that this makes sense. Thanks for issue report.
