### ISSUE TITLE
Selecting a history item breaks request view

### ISSUE THREAD

**Issue by apapsch** [jarrodek/ChromeRestClient#806]
When I select "OPEN" in history view, view is switched to request view. It randomly happens that after I opened a request, request view is broken. I'll attach a screen once it happens again.

Request screen is rendered useless by this issue. No control reacts to input. It doesn't help opening another request. Only until I restart ChromeRestClient is this issue gone.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Until you don't provide detailed description or - as you mentioned - a screenshot, I can't do much about it because I don't know what's wrong.

**Comment by jarrodek** [comment]
OK,

Finally I got this one. Sometimes request panel was broken after going back to it from other panels. I managed to update the view in the v8 (will be released in coming days) where this issue is fixed.

I'm closing this issue but please, notify me if it bug you again.
