### ISSUE TITLE
New history list window can't be dismissed

### ISSUE THREAD

**Issue by irot** [jarrodek/ChromeRestClient#807]
![screen shot 2016-09-27 at 2 57 17 pm](https://cloud.githubusercontent.com/assets/1768155/18863200/ba50d04a-84c2-11e6-8e8e-a8fbbb737dbd.png)

It suddenly popped up. I've maximised the window and clicked the Close button but nothing happens. The blue enable XHR screen pops out of the corner some times.
## Expected outcome

Clicking close should close/dismiss the window.
## Actual outcome

Doesn't close. Frustration clicking triggers the blue enable XHR screen.
## Versions

App: 7.39.48.260-stable
Chrome: 53.0.2785.116
Platform: Mac OS X (10_11_6)
## Steps to reproduce
1. Click History, window appears
2. Click Close, or
3. Randomly click anywhere to try and get rid of it

**Comment by jarrodek** [comment]
This is fixed already
