### ISSUE TITLE
Overflow menu doesn't go away once clicked

### ISSUE THREAD

**Issue by ishaanbahal** [jarrodek/ChromeRestClient#811]
The hamburger type menu at the bottom-left doesn't go away, once clicked on. 
## Expected outcome

If clicked outside the overflow/dropdown menu, it should close
## Actual outcome

It doesn't
## Versions

App: 7.39.48.260-stable
Chrome: 53.0.2785.101
Platform: Linux (Ubuntu 16.04/Gnome 3.18)
![screenshot from 2016-09-30 11-56-42](https://cloud.githubusercontent.com/assets/2863124/18988017/56f8ec50-8722-11e6-825f-cacf51a83ad8.png)
## Steps to reproduce
1. Click the hamburger menu in the bottom left.
2. Try clicking anywhere outside it to close it, it wont.

**Comment by jarrodek** [comment]
Hil,

Thank you for issue report. 
It closes itself when you click on the request panel. When you click on the menu panel it will consume click / focus / whatever event and the menu is not closing. Although it's not app issue (it's an issue with polymer elements) I'll keep it as a bug report so maybe I'll find a way to fix it and send PR to them.

**Comment by jarrodek** [comment]
This is redesigned in next release.
