### ISSUE TITLE
Number in tabs is not alligned

### ISSUE THREAD

**Issue by riyanka30** [jarrodek/ChromeRestClient#812]
The number in the 'request headers' tab and other tabs is not alligned properly after the API completes the execution.

## Versions
App: 7.39.48.260-stable
Chrome: 52.0.2743.116
Platform: Mac OS X (10_11_6)

<img width="1299" alt="screen shot 2016-10-04 at 3 57 06 pm" src="https://cloud.githubusercontent.com/assets/22613970/19071292/f0fe833c-8a4c-11e6-8df4-1b15e3cd2662.png">

**Comment by jarrodek** [comment]
Hi, 
Thank you for issue report.
I've seen it once but I cant reproduce it anymore. I'll try to fix it when it happens to me again.
