### ISSUE TITLE
How do I start the extension?

### ISSUE THREAD

**Issue by machineghost** [jarrodek/ChromeRestClient#815]
Many major Chrome plug-ins (eg. Lazarus, SessionBuddy, React Developer Tools) have icons that appear next to the URL bar and make it possible to easily start them.  But ChromeRestClient doesn't have such an icon, and I couldn't find anywhere on the Chrome store, the extension's webpage, or the GitHub page that says how to start it up.

Could you please consider documenting this very basic bit of info somewhere, or better yet add an icon to make the extension easy to access?  I know this must seem incredibly obvious to you, but to someone using the extension for the first time it's not, and right now I'm having to open the extensions page every time I want to us the rest client :(

Thanks.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

I can't do much about this. It's a Chrome team issue. Apps are not extensions and do not have icon in the browser. You can run it from the new tab page clicking first "App" button:
![image](https://cloud.githubusercontent.com/assets/3320020/19326040/bbd16600-90c0-11e6-94a7-9865974fcd3e.png)
An then selecting the app:
![image](https://cloud.githubusercontent.com/assets/3320020/19326072/f069ebc6-90c0-11e6-9040-94c873f25ecb.png)

Clicking right button on the app icon there will brings a context menu. There's an option to create a shortcut to the app. Options there depends on your OS.

Nothing much I can do more. I'll add proper description to the store's description.

**Comment by machineghost** [comment]
> Nothing much I can do more.

Man, Google really screwed the pooch with their plug-in overhaul huh?

> I'll add proper description to the store's description.

Thanks for at least doing that much!

**Comment by jarrodek** [comment]
I'm guessing that's why they are removing support for Chrome Apps next year...
