### ISSUE TITLE
Very Minor Blemish in informational message when no payload returned (head)

### ISSUE THREAD

**Issue by jaaadrian** [jarrodek/ChromeRestClient#824]
Your description here

## Expected outcome
What should happen?
Informational message should say:
This response do not carry a payload.

## Actual outcome
What happened?
Informational message says:
This response does not carry a payload.

## Versions
App: 7.39.48.260-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_12_1)

## Steps to reproduce
1. Send head request where no payload is returned
2. Informational message says: This response do not carry a payload, should say: This response does not carry a payload.

**Comment by jarrodek** [comment]
Thanks for correction in translation :)
It's update it right now.

**Comment by jaaadrian** [comment]
Wow! Thanks for the quick turnaround. 
James

**Comment by jarrodek** [comment]
I was actually finishing new release so you've been at the right place and time :)

**Comment by jaaadrian** [comment]
Sweet, thanks again. It was a very humble bug, and a tip of the hat to those who unlike me can speak and write more than one language!
