### ISSUE TITLE
Cannot manage project

### ISSUE THREAD

**Issue by lyrau** [jarrodek/ChromeRestClient#826]
When the project name is too long, we can not see the pencil that should appear when you hover over a project on the left menu.

<img width="261" alt="capture d ecran 2016-10-27 a 13 07 02" src="https://cloud.githubusercontent.com/assets/754307/19765030/8550f3ca-9c46-11e6-8ec6-506bebd5b66f.png">

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. It will be fixed in next planned release.

**Comment by jarrodek** [comment]
This fix was published in the web sore and it should work now.
