### ISSUE TITLE
Send button not visible

### ISSUE THREAD

**Issue by randyberndt** [jarrodek/ChromeRestClient#837]
When entering long XML text, prior to attempting to send, scrolling downward to the end does not show the entire send button, only a small sliver at the top. It appears the screen display logic is not considering the space used by the menu bar at the bottom and is assuming it can display all the way to the end of the window

## Expected outcome
Entire send button should be visible

## Actual outcome
Only tiny sliver of button visible (see attached screenshot)

## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Windows (7)

## Steps to reproduce
1. Enter long XML text
2. Using scroll bar on right, scroll to bottom of screen

![send_button](https://cloud.githubusercontent.com/assets/23324496/20080519/c35a6b7a-a50f-11e6-974d-4f03b3268886.png)

**Comment by jarrodek** [comment]
Expect fix really soon.

**Comment by jarrodek** [comment]
Thanks for the report.

**Comment by jarrodek** [comment]
It is fixed not and beginning rollout.

**Comment by randyberndt** [comment]
Wow, great response time – thank you.

Randy Berndt
Lead Developer
HD Supply Facilities Maintenance
Phone:  713-988-5808
Cell:      832-746-8193

One Team Driving Customer Success and Value Creation

CONFIDENTIALITY NOTICE: This message is for intended addressee(s) only and may contain information that is confidential, proprietary or exempt from disclosure, and subject to terms at: http://www.hdsupply.com/email.

**Comment by randyberndt** [comment]
Sorry, but I am not familiar with “github” – how do I obtain the new version?

Randy Berndt
Lead Developer
HD Supply Facilities Maintenance
Phone:  713-988-5808
Cell:      832-746-8193

One Team Driving Customer Success and Value Creation

CONFIDENTIALITY NOTICE: This message is for intended addressee(s) only and may contain information that is confidential, proprietary or exempt from disclosure, and subject to terms at: http://www.hdsupply.com/email.

**Comment by jarrodek** [comment]
It's not on github :)
I've published the update literally 10 minutes ago. Chrome should update the app in next hour or so. You can also go to the chrome://extensions page, check "developer mode" and the "Update extensions now". Be sure to uncheck "developer mode before exit. It can influence performance.
