### ISSUE TITLE
Can't save request to current project !

### ISSUE THREAD

**Issue by quocthinh212** [jarrodek/ChromeRestClient#841]
I create new request. but i can't save this to current project. (only save to new project opiton !!)

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
I'll check it right away. Thanks.
