### ISSUE TITLE
send button is not visible 

### ISSUE THREAD

**Issue by rajesh94** [jarrodek/ChromeRestClient#855]
Your description here
send button is not visible if we have multiple parameters

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Thank you for the issue report. It's a duplicate of #837 so I'm closing it. 
I do however already fixed it. Expect update very soon.
