### ISSUE TITLE
Application crashes after opening

### ISSUE THREAD

**Issue by ducky92** [jarrodek/ChromeRestClient#864]
ARC after the update this morning crashes after opening every time.  Using it doesn't seem to affect this, (no using ARC until it crashes or preforming 'GET' requests) 

steps to recreate:
1. open ARC in windows 7 SP1 (using it outside of the browser)
2. wait < 5 minutes
3. popup pops up saying that ARC has crashed and needs to be restarted.

**Comment by jarrodek** [comment]
I can guess that it may be related to #830 where the arc is trying to process a lot of data. But in this case it is trying to process history data (not the same as on the history list). I'm fixing it right now.

**Comment by jarrodek** [comment]
So, I fixed it by limiting number of history records that the app can process during a request recall. It should not cause crashes.
