### ISSUE TITLE
Footer Overlayed of Submit button

### ISSUE THREAD

**Issue by wjpin84** [jarrodek/ChromeRestClient#869]
Footer is overlayed the SEND button for a large JSON payload for a POST request.

## Expected outcome
I should be able to view and click the send button based on ui design.

## Actual outcome
The footer is overlayed the SEND button for a large JSON payload for a POST request.

## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. Choose POST for request type
2. Insert large payload (approx 205 lines)
3. Footer is ovelaying the send button

**Comment by jarrodek** [comment]
This has been fixed literally 10 minutes ago. The update is already on CWS.

**Comment by wjpin84** [comment]
Thank you!
