### ISSUE TITLE
ARC upgrade error

### ISSUE THREAD

**Issue by lucienLopez** [jarrodek/ChromeRestClient#870]
The app errored during latest upgrade.

## Logs

```
Initializing upgrade
[1016] Checking if upgrade is required.
[1016] Deleting new databases if exists.
Maximum IPC message size exceeded.
UnknownError: Maximum IPC message size exceeded.
```
## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_12_1)

**Comment by jarrodek** [comment]
This has been fixed literally 10 minutes ago. The update is already on CWS.
