### ISSUE TITLE
Unable to edit Project

### ISSUE THREAD

**Issue by himanshushekhar002** [jarrodek/ChromeRestClient#879]
ON MAC : --- 

If project name is too big then its not wrapping and edit option is not appearing in front of it.

## Expected outcome
Edit option should appear.

## Actual outcome
I was unable to edit my project since edit option was not appearing.

## Versions
App: 7.39.48.260-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Create a project with name larger than the width of left PAN of ARC.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. It was fixed with #826
You have old version. Current version is 8.9. Soon you should receive an update from Chrome Web Store.
