### ISSUE TITLE
Autosuggest

### ISSUE THREAD

**Issue by ameissnersofi** [jarrodek/ChromeRestClient#880]
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_12_1)

After the new update, everytime I type a url in the bar, the autosuggest window pops up.  That's fine and all, except it covers the bar where i'm typing, so I can't see at all what I'm doing.  I have to press `esc` on every keystroke just to see what I'm typing.  Can the suggestion box be moved out of the way?

**Comment by jarrodek** [comment]
Hi,

Thank you for tracking this issue. As you can see I already fixed it. I'll update the app in next planned release or with hotfix release (if any occur).
