### ISSUE TITLE
Saving Requests Into Projects Results in Duplicate Projects Being Created

### ISSUE THREAD

**Issue by StephenCasella** [jarrodek/ChromeRestClient#886]
Whenever I save a request I like to save it into a project. The project name doesn't populate or autocomplete for me, so I just type in the name of the existing project I want to save into when I save the request. Whenever I do that I end up with a new project of the same name with just that new request saved into it. I end up with as many duplicate projects as times I've saved requests.

## Expected outcome
What should happen?
What used to happen before the latest update I applied. New requests could be saved into existing projects without the creation of duplicate projects.

## Actual outcome
What happened? A new project was created for the request with the same name as the existing one.

## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Windows (7)

## Steps to reproduce
1. Have an existing project
2. Save a new request into that project
3. Observe the creation of a duplicate project with the same name but only the one request in it

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
If the drop down with projects list isn't populated it means that there is an issue with the database. It may be connected to issue #887 where I discovered problem with the database library I used in the app in new version. If I'm correct then the fix might be released very soon (I may have found a workaround). 
I'll keep you posted.
