### ISSUE TITLE
The app does not send second request

### ISSUE THREAD

**Issue by Hamulus** [jarrodek/ChromeRestClient#887]
The app does not send second request after I send the first request.
When I run the app and fill some fields for GET or POST requests and click "Send" the first request are sent normally.
When I click send another time (with or without fields changing), the request does not work. Progress bar and Abort button are showed infinitely.
The only one method to stop it: close the app.
After I close the app and run it again, the first request also can be sent successfully, but the second shows the similar issue

## Expected outcome
Send request as more as I want.

## Actual outcome
Only the first request after app run can be sent

## Versions
App: 8.9.53.279-stable
Chrome: 51.0.2704.106
Platform: Windows (8.1)

## Steps to reproduce
1. Run the app
2. Fill some fields
3. Send a request
4. Change or do not change fields
5. Try to send another request

**Comment by SubutaDan** [comment]
Having the same problem. Also noticed that History hangs.

**Comment by zawsx** [comment]
Same here.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
I was able to isolate the issue to the database wrapper library (as you can see I've referenced an issue above). However I need an advice from the author of the library because I'm not sure how to proceed. 
I'm working on it and I'll let you know if I find a way to fix it.

**Comment by jarrodek** [comment]
OK, I was faster than I thought it would be. I think I've found a fix but I have to consult it with author of the library. I'll update the app in coming hours to fix it.

**Comment by SubutaDan** [comment]
Hi Jarrodek,

I ran some quick tests and the problem appears to be gone.

Thanks so much for the fix and the communication.

-Dan

> OK, I was faster than I thought it would be. I think I've found a fix but
> I have to consult it with author of the library. I'll update the app in
> coming hours to fix it.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jarrodek/ChromeRestClient/issues/887#issuecomment-260362607


-- 
Dan Stone
Scalable Application Strategies Ltd.
dan.stone@scapps.co.uk
+44 7875 599 430

**Comment by jarrodek** [comment]
Great. So I'm closing this issue :)
