### ISSUE TITLE
Save as new request feature been dissappeared after last update

### ISSUE THREAD

**Issue by thushan85** [jarrodek/ChromeRestClient#890]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 8.9.53.279-stable
Chrome: 50.0.2661.102
Platform: Linux (-)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
When you ctrl or command + s you'll see a toast message informing that you have to user ctrl/command + shift + S to bring the save dialog on already saved request.
The change is for the app to behave like other apps that are using shortcuts. Ctrl + S is always to save the request or to "save as.." if it wasn't already saved. Ctrl + Shift + S is always "save as...".

The change was necessary to become consistent with native apps.
I'm closing this as WAI.
