### ISSUE TITLE
Renaming script in SAVED appears to save without the Project as no longer displays in Projects folder

### ISSUE THREAD

**Issue by dkeith7** [jarrodek/ChromeRestClient#898]
When renaming a script in the SAVED folder (by clicking on name and changing name), it appears to save the script without an association to the project it was previously tied to.   The script then no longer displays in the PROJECTS folder that it was associated with.

NOTE:  The only way to get the script associated with the project again is to do a 'save as', which now means you have multiple copies of the script.

CHROME:
Version 54.0.2840.99 m (64-bit)

Advanced REST Client:
Version:  8.14.55.288-stable

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
I'm on it.

**Comment by jarrodek** [comment]
It is merged already with the main branch but now it is tested in test channels. Soon it will be released to public.

**Comment by dkeith7** [comment]
Thank you.  Appreciate the updated.

**Comment by dkeith7** [comment]
Thank you.  Appreciate the update.
