### ISSUE TITLE
Encode URL button producing incorrect results

### ISSUE THREAD

**Issue by MysteriousAges** [jarrodek/ChromeRestClient#900]
Attempting to URL Encode a Query using the built-in button is producing incorrect results in version 8.14.55.288, Chrome Version 54.0.2840.99 m

Input: 
http://192.168.2.252/service/board/1/edit?description=We'll keep your precious pup fed, watered, walked and socialized during their stay.

Expected result:
http://192.168.2.252/service/board/1/edit?description=We%27ll+keep+your+precious+pup+fed%2C+watered%2C+walked+and+socialized+during+their+stay.

Actual result:
http://192.168.2.252/service/board/1/edit?description=We%27ll%2Bkeep%2Byour%2Bprecious%2Bpup%2Bfed%252C%2Bwatered%252C%2Bwalked%2Band%2Bsocialized%2Bduring%2Btheir%2Bstay.

It looks like the conversion is occuring twice with one button click.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I'll fix it soon.

**Comment by jarrodek** [comment]
It is merged already with the main branch but now it is tested in test channels. Soon it will be released to public.
