### ISSUE TITLE
Searching History is not returning results

### ISSUE THREAD

**Issue by timothydonato** [jarrodek/ChromeRestClient#904]
The Searching History not returning results

## Expected outcome
I expect the criteria I enter into the Search window to return results that match that criteria

## Actual outcome
No results upon hitting enter (search).  I receive a message saying "History is empty".

# Versions
App: Version: 8.14.55.288-stable
Chrome: Version 54.0.2840.99 m (64-bit)

# Steps to reproduce
1. Click on History
2. Click on magnifying glass on top right 
3. Enter search criteria
4. hit enter

See attached screen shots
![arc screenshot](https://cloud.githubusercontent.com/assets/7225885/20573071/1bbf781e-b17c-11e6-8511-6953251d8ba6.PNG)

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
I've noticed it already and the fix is on it's way.
Soon it will be released.

**Comment by timothydonato** [comment]
Great!  Thanks for the response.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
