### ISSUE TITLE
Continue with self sign and bad certificates

### ISSUE THREAD

**Issue by dortibi** [jarrodek/ChromeRestClient#906]
Cannot send requests in https if it getting bad certificate

I'm using this app for developing and the certificate isn't from known ca or without a valid common name because I'm using a virtual environment, the common name valid for the inner LAN and not from outside the environment.

I would like to enable or disable the https certificate verification when I'm using it for developing

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.98
Platform: Mac OS X (10_12_1)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Please, use "Use XHR" switch on the main toolbar or install proper certificate (free, automated certs are provided by [let's encrypt](https://letsencrypt.org/)).

I'm closing as duplicate and WAI.
