### ISSUE TITLE
Converts HTTP headers to lower case

### ISSUE THREAD

**Issue by pdrhound** [jarrodek/ChromeRestClient#908]
The client is converting HTTP header names to all lower case.  This causes some servers to reject/ignore the header.

## Expected outcome
HTTP headers are case sensitive so the case should be preserved

## Actual outcome
I got error 403 from a server I'm connecting to

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.98
Platform: Mac OS X (10_12_0)

## Steps to reproduce
1. Make a POST request using header HTTP_X_STORE_NAME = "some value"
2. Use Wireshark to view the request
3. Note that header name has changed to "http_x_store_name"

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491 for detailed discussion and explanation. I'm closing this as a duplicate. 

Thanks.
