### ISSUE TITLE
Add, edit, delete request elements in side project error

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#909]
Go to left nav bar > choose edit project > edit associated request or delete.

NOT WORK AS NORMAL.

## Expected outcome
Edit success
Delete success

## Actual outcome
After editing success, the elements is missing
Delete got success but no deletions occurred

## Versions
App: 8.14.55.288-stable
Chrome: 53.0.2785.143
Platform: Linux (-)

## Steps to reproduce
1. Go to left nav bar
2. choose edit project
3. edit associated request or delete

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
I can reproduce the problem. It's not the database mapping and when you restart the app requests are properly associated with the request again. The problem is with state of the project during run time. 
I'll fix it now.
