### ISSUE TITLE
URL Encoding problem !!!

### ISSUE THREAD

**Issue by razzul** [jarrodek/ChromeRestClient#910]
Hi, I was trying to encode the URL containing 'SPACE' but it is converting into '%2B' instead of '%20'  

## Expected outcome
URL should contain '%20' (decode from = 'SPACE')

## Actual outcome
URL having '%2B' (decode from = '+')

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.99
Platform: Windows (7)

## Steps to reproduce
1. Put this in the request URL 'http://google.com/?q=Rajul Mondal' 
2. Encode the URL from the Encode option
3. URL will be converted into 'http://google.com/?q=Rajul%2BMondal'

**Comment by jarrodek** [comment]
Hi,

The bug is already patched and it will be released in next 2 days (have to test it first on real live APIs). 
For some reason (my fault of course) the app encodes the URL twice when you click on the menu button.
Sorry about that.

**Comment by razzul** [comment]
Yes, I have tested in real live APIs which I don't want to share in public. 

Thanks for you support.
