### ISSUE TITLE
Data import error: This file is no longer supported

### ISSUE THREAD

**Issue by ganacharyas** [jarrodek/ChromeRestClient#911]
While importing my previously working json file, gettign above error message.
 Please help.

Data import error:  This file is no longer supported.

HTMLElement._handleLog (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:151877:18)
    at HTMLDocument.handler (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:3386:17)
    at HTMLElement.fire (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4152:6)
    at arc.app.importer.saveFileData.then.catch (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:86762:12)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Can you please paste here the JSON structure of your file? I mean only few first keys. Without request / project / history values.

It can be something like:
```
{
  "kind":"ARC#requestsDataExport",
  "createdAt":"2016-10-06T10:54:43.940Z",
  "version":"5.0.5-test",
  "requests":[{]]
  ...
}
```
It will help me find a problem here.

**Comment by ganacharyas** [comment]
{"projects":[{"id":26, "name":"xxx 2.1", "time":1395869388134}], "requests":[{"id":537, "encoding":"application/x-www-form-urlencoded", "headers":"Content-Type: application/json", "method":"POST", "name":"01 Create SMS Application", "payload":"{\n\"applicationName\":\"{appName}\",\n\"applicationShortName\":\"{appName}\",\n\"applicationTag\":\"xxx\",\n\"description\":\"A sample xxx application\"\n}", "project":26, "skipHeaders":false, "skipHistory":false, "skipMethod":false, "skipParams":false, "skipPath":false, "skipPayload":false, "skipProtocol":false, "skipServer":false, "time":1400021533239, "url":"https://www.mysite.com/registration/v2/{accountID}/applications?apiKey={accountApiKey}", 
   "driveId":""}]
}

**Comment by jarrodek** [comment]
The code that supports this data structure has been removed from the application. I'll look into restoring it.

**Comment by ankur-bhardwaj** [comment]
still getting same issue.. plz check.

**Comment by jarrodek** [comment]
Hi,

It's because it's still in beta. For some time now I'm finding another bugs and I don't want to release a version that have some nasty issues.

**Comment by pardvm** [comment]
@jarrodek, any estimate to release?
I have lost all my saved projects :-(
