### ISSUE TITLE
Constant app crashes. makes ARC unusable

### ISSUE THREAD

**Issue by ducky92** [jarrodek/ChromeRestClient#916]
I had an issue before where the application would crash < 5 minutes after opening and I was notified that it was resolved. Either I'm not getting the updated version when i re-download it from chrome or the error still exists.

I have removed this app from chrome and re-downloaded and installed it several times with no changes, thinking that it was an installation issue.

## Expected outcome
the application should not crash

## Actual outcome
crashes every time i open it. a balloon pops up and says that Advanced REST Client has crashed. Click this balloon to restart it. (clicking the balloon doesn't restart the application either)

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.99
Platform: Windows (7)

## Steps to reproduce
1. Open Chrome
2. click the button to launch ARC
3. wait

**Comment by jarrodek** [comment]
Hi,

I remember the issue. I worked on it a week or two ago. I though it was caused by memory consumption but maybe I'm wrong. I need to investigate this further. Unfortunately I can't cause the same behavior on any of my computers so it's quire difficult to catch the problem. Well, I'll continue investigating.

**Comment by ducky92** [comment]
this may be an issue with how the app interacts with that version of chrome. I upgraded to Chrome Version 55.0.2883.75 from 54.0.2840.99 and I have successfully been using it for more than an hour (this is a drastic change compared to the previous version). Other devs on my team don't seem to be having this issue. I couldn't find any logs or any error messages that might lead to the cause.

**Comment by jarrodek** [comment]
Thank you for additional info. I'll check Chrome change log for v55. Maybe they have changed something there.

**Comment by m4mukulgarg** [comment]
I'm having the same issue. ARC crashes after minutes of launching without doing anything. It keeps on occupying more and more memory and crashes eventually.
ARC version: 10.0.12-stable
OS: Windows 10 64bit version: 1709
Chrome: 64bit version: 63.0.3239.84

**Comment by jarrodek** [comment]
Please try new ARC native application. It is very similar application but it's more stable than Chrome application.
Install it from https://install.advancedrestclient.com/
