### ISSUE TITLE
Can't import from json.  Can't open from google drive

### ISSUE THREAD

**Issue by roncyrier** [jarrodek/ChromeRestClient#919]
I am trying to transfer from one computer to the next.  I've tried this.
1.  Export from old computer
- Export creates JSON file
- Import in new computer
- Error "Unable to parse theFile"
2. Open file from GoogleDrive
- Login with same account 
- I see a list of saved calls
- click on the one I want and hit "Select"
- screen on new computer does not populate the screen

Old computer is Win 8.1 - New computer is Win 10

**Comment by chaseadam** [comment]
I am seeing similar behavior on Fedora 24 chrome. When debugging, I see the message every time I try to load a .arc from my google drive.
elements.js:118349 What to do???

**Comment by chaseadam** [comment]
looks to be dup of #925 

I am unable to load a .arc file via drive UI "open with" nor the "select" interface in ARC. The "open with" results in the following errors in the console:

window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
elements.js:12652 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
measureHeaderHeight @ elements.js:12652
main.js:585 Uncaught TypeError: Cannot set property 'opened' of null
    at HTMLTemplateElement.app._mainPageSelected (main.js:585)
    at HTMLElement.handler (elements.js:3386)
    at HTMLElement.fire (elements.js:4152)
    at HTMLElement._applySelection (elements.js:8726)
    at Polymer.IronSelection.setItemSelected (elements.js:8368)
    at Polymer.IronSelection.select (elements.js:8387)
    at HTMLElement._selectSelected (elements.js:8674)
    at HTMLElement._updateSelected (elements.js:8670)
    at HTMLElement._complexObserverEffect (elements.js:4479)
    at HTMLElement._effectEffects (elements.js:4314)

**Comment by jarrodek** [comment]
Hi,
thank you for the issue report.

Can you please check the exported file format? It should be something like this:
```
{
  "createdAt: String,
  "version": String,
  "kind": "ARC#SavedHistoryDataExport",
  "requests": [{
    "name": String,
    "method": String,
    "url": String,
    "type": String,q
    "headers": String,
    "payload": String,
    "created": String,
    "kind": "ARC#RequestData"
  }],
  "projects": [...]
}
```
Also, where have you exported the data? Is it was the import / export page, history or saved list?


Over the time the file export structure has changed. However, the latest version of the app should accept almost all older versions. Almost because I think it doesn't recognise the oldest format but it is not used for years now.

I'll be glad for checking this up.
Thanks

**Comment by davideakes** [comment]
I was about to submit a new bug but decided to check to see if others had the same issue and they have. I will provide my would-be bug report as a comment here to hopefully help you get some new insight.

I'm having to migrate from Windows 7 to Windows 10. The export on Windows 7 produces verifiable correct json; however, the import fails with the error message: "Unable to parse the file." I tested this on the same box as well and the json generated by the Windows 7 installation cannot be imported to the same installation. This also occurs exporting the data from the settings menu with the same error messages. The vanilla installation on Windows 10 with no history generating the following complete json also failed to be parsed on the same installation:
{"createdAt":"2017-01-13T15:40:52.168Z","version":"8.19.60.296","kind":"ARC#SavedHistoryDataExport"}

## Expected outcome
What should happen?
History should be imported.

## Actual outcome
What happened?
Error message: "Unable to parse the file."

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (10)

App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (7)

## Steps to reproduce
1. Export history of ARC to a json file.
2. Attempt to import that same history, get "Unable to parse the file."
