### ISSUE TITLE
No long able to see traffic in Fiddler (Proxy) when I turn on "Use XHR"

### ISSUE THREAD

**Issue by ajpetebyu** [jarrodek/ChromeRestClient#923]
Your description here

I admit this may not qualify as a bug but it is new behavior that I feel like must have changed recently.  I often use Advanced Rest Client in conjunction with Fiddler proxy to view the REST call as well as the rest of the traffic through the Proxy.  However ARC traffic no longer appears in my Fiddler Proxy traffic after I turn on "Use XHR"

## Expected outcome
What should happen?

Ideally I'd love to be able to continue to see proxied HTTPS traffic through my proxy when I select "Use XHR"

## Actual outcome
What happened?

I know longer see the request/responses in my proxy.

## Versions
App: 8.18.60.295-beta
Chrome: 54.0.2840.99
Platform: Windows (8.1)

## Steps to reproduce
1.  Select "Use XHR"
2.  Submit a REST Request
3.  Check to see if the traffic is visible in Fiddler proxy.

**Comment by jarrodek** [comment]
When you are using "Use XHR" option the request is made by the background page of the proxy extension and not in context of any web page. That is why you can't see it and you won't see it. 

I'm closing it as WAI but feel free to comment
