### ISSUE TITLE
No history or saving for Socket calls

### ISSUE THREAD

**Issue by kabbottcc** [jarrodek/ChromeRestClient#924]
It appears that the save function and history information only pertains to Request activity and not Socket activity.  Why is that?  I use ARC more for wss testing than for http testing.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report and sorry about that. It was already requested in one of the issues and I'm aware of it. I will finally do it and I want to do it. But for the most of my time available to work on the app I'm fixing issues that are critical. 
I hope you understand and I will definitely make a history for the WS soon. Just can't tell right now when.

Thanks

**Comment by kabbottcc** [comment]
Thanks for the note ☺

Kim
