### ISSUE TITLE
not able to execute apis stored in google drive

### ISSUE THREAD

**Issue by ramachandrab** [jarrodek/ChromeRestClient#925]
Not able to execute apis stored in google drive

## Expected outcome
should populate with selected api from google drive
What should happen?
Should able to execute the apis which are stored in drive earlier

## Actual outcome
Nothing happening. Its showing previously executed api.

## Versions
App: 8.19.60.296-stable
Chrome: 54.0.2840.99
Platform: Windows (7)

## Steps to reproduce
1. Goto saved
2.  try to select one api from the drive(not local one)
3.  its not getting selected to execute.

**Comment by jarrodek** [comment]
HI,

Thank you for the issue report.
There is a bug I found in the code. The file is actually downloaded and parsed but the request content is never actually replaced. I'm sorry for that because I haven't tested it before the latest update. I'll try to fix it in coming days.

**Comment by jarrodek** [comment]
It is fixed in the develop test branch (so the issue was closed automatically) but it will take few days until it will be released.
