### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by aggarwalneeraj** [jarrodek/ChromeRestClient#932]
Environment: WIN 10/Chrome
**Steps to Reproduce:**

**1.** Look for Advanced REST Client extension. 
https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo
**2.** Read text on the right side of the window that appeared in step 1
**3.** In "What's new:" section, look at 3rd bullet point.

**Actual Result:** Third bullet point reads as:
- New header sets - define own headers sets and use them **you yor** requests. Refer to attached screenshot.

**Expected Results:** Correct language should be in place for this bullet point.

![image](https://cloud.githubusercontent.com/assets/24943271/21693182/ceb5415e-d334-11e6-97cf-9a9d7781940f.png)

![image](https://cloud.githubusercontent.com/assets/24943271/21694018/17254242-d338-11e6-8230-bc653e0c856a.png)

**Comment by aggarwalneeraj** [comment]
While using ARC, found other spelling issue. Refer second screenshot

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. Definitely, I should be more careful about this. Usually, I'm already tired when I'm publishing the app and finishing changelog, tutorials etc. I'm alone here on this project and have no one to check spelling errors for me :)

I'll update it soon.

**Comment by aggarwalneeraj** [comment]
Thanks for your response. I understand your occupancies and can volunteer
in this. I am a seasoned QA professional with experience of more than 12
years. Besides cosmetic issues I can be of help as functional tester as
well. I am based in Vancouver, Canada

Please let me know the next steps.



On Jan 6, 2017 9:49 AM, "Paweł Psztyć" <notifications@github.com> wrote:

Hi,
Thank you for the issue report. Definitely, I should be more careful about
this. Usually, I'm already tired when I'm publishing the app and finishing
changelog, tutorials etc. I'm alone here on this project and have no one to
check spelling errors for me :)

I'll update it soon.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jarrodek/ChromeRestClient/issues/932#issuecomment-270961001>,
or mute the thread

**Comment by jarrodek** [comment]
Actually, I've prepared a beta channel for that :) 
You can join the beta testers group:

https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel

and then you'll be able to install the beta version of the app: 

https://chrome.google.com/webstore/detail/advanced-rest-client-beta/epgngalmiadbjnoompchcohonhidjanm

Usually, updates to this version are sent about 2 weeks before planned release. 
Don't forget to enable desktop notifications during the onboarding. Then you'll receive a notification when the app is updated.

Thanks :)

P.S.
There's a dev and canary channel as well if you are interested in more often updates.
