### ISSUE TITLE
Opening saved file from google drive results to empty window

### ISSUE THREAD

**Issue by VitMosin** [jarrodek/ChromeRestClient#935]
Your description here
I saved request to google drive as *.arc file. Then i try to open it from google drive, google drive asks me how to open this file normally proposing to open by rest client. I click ok and...
## Expected outcome
What should happen?
I want to see at least filled request url
## Actual outcome
What happened?
But request url is empty
![image](https://cloud.githubusercontent.com/assets/8428137/21800684/cd6abbc2-d72f-11e6-9b09-3fa691ef0c48.png)

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,
This issue has been resolved recently but the update is not on the store. It will be updated in coming days.
