### ISSUE TITLE
Am I just an idiot?

### ISSUE THREAD

**Issue by evanspa** [jarrodek/ChromeRestClient#940]
I love this tool, but for the life of me, I cannot figure out how to create a new project, or how to add a new endpoint to an existing project.  What is wrong with me?

**Comment by kabbottcc** [comment]
There is no save button on the Socket tab, only on the Request tab....this is when using the Beta version, but I can't pull down your new code that might be having it - will it be pushed to the beta version soon?

**Comment by jarrodek** [comment]
On the socket tab I'm not planning to put a "save" button. You'll see a a list of previously made connections below the socket URL filed. From there you'll be able to choose one of the URLs. 
Also URL autocomplete function has been added to the websockets.

As per saving the request with a project, it's in the "save" menu. Projects are abstract in ARC and generally are just a name for a group of requests. So they don't actually have special treatment. Just check the "save in a project" checkbox in the save dialog.
