### ISSUE TITLE
Allow user to customize UI and collapse response headers

### ISSUE THREAD

**Issue by jcrben** [jarrodek/ChromeRestClient#941]
I'm finding that the way the view is set up, I have to scroll past the headers to see my response? For example:

![image](https://cloud.githubusercontent.com/assets/5614134/22269514/85cb3b72-e240-11e6-892c-f7a526a197ea.png)

You can just see the hint of the response body through the Raw and Parsed headers... scrolling every time I request gets old pretty quickly. How are people handling this?

**Comment by jarrodek** [comment]
A change related to this is right now tested in beta channel of the app. Headers will be hidden by default and only status code and the response will be visible. Naturally you'll be able to see headers when you open the pane.

New version will be released soon.

**Comment by jarrodek** [comment]
This will be the default view after making a request:

![image](https://cloud.githubusercontent.com/assets/3320020/22374009/27706f44-e49c-11e6-9f63-b0cb7038a128.png)

(note that some UI elements in the picture are under development right now)
