### ISSUE TITLE
It is impossible to import project exported in the same app from another comp

### ISSUE THREAD

**Issue by lioralla** [jarrodek/ChromeRestClient#946]
Your description here

## Expected outcome
What should happen?
Exported file should be imported 

## Actual outcome
What happened?
Unable to parse the file message

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi thank you for issue report.

Import / export issues most probably have been fixed recently.
Can you test it in beta version? To do so you need to join beta tester group (https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel) to be able to install ARC beta  (https://chrome.google.com/webstore/detail/advanced-rest-client-beta/epgngalmiadbjnoompchcohonhidjanm)

It should work there but I'd be grateful for confirmation.

**Comment by jarrodek** [comment]
This issue is fixed in the stable release (updated today). Should not be more problems with data import.
