### ISSUE TITLE
Dont load from google drive

### ISSUE THREAD

**Issue by gandb** [jarrodek/ChromeRestClient#949]
Your description here

## Expected outcome
Save in google drive and load in another computer.

## Actual outcome
What happened?
Dont load

## Versions
App: 8.19.60.296-stable
Chrome: 54.0.2840.59
Platform: Windows (7)

## Steps to reproduce
1. Save in mac ios chrome
2. Load in windows chrome

**Comment by jarrodek** [comment]
Hi thank you for issue report.

This most probably has been fixed recently.
Can you test it in beta version? To do so you need to join beta tester group (https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel) to be able to install beta version (https://chrome.google.com/webstore/detail/advanced-rest-client-beta/epgngalmiadbjnoompchcohonhidjanm)

It should work there but I'd be grateful for confirmation.

**Comment by gandb** [comment]
My version is 8.19.60.

The beta version isant acessifull

**Comment by jarrodek** [comment]
The release with fix has been published today.
Thanks for reporting the bug.
