### ISSUE TITLE
The requested URL can't be reached

### ISSUE THREAD

**Issue by gilibarak280** [jarrodek/ChromeRestClient#951]
Hi
I am trying to post a request in ARC and there's a problem with the request body.
When putting the json in Raw Headers I get "Header Value should not be empty" and "Content-Type header not defined".
And When I am removing the "{}" marks from the json object, and adding custom content type, I am getting :
The requested URL can't be reached
The service might be temporarily down or it may have moved permanently to a new web address.
The request object could not be initialized
(GET requests work perfectly)
Thanks,
Gili

**Comment by jarrodek** [comment]
You must provide both content type and body at the same time. The it will not show error.
