### ISSUE TITLE
Multipart/form-data filename always "blob"

### ISSUE THREAD

**Issue by Holmstedt** [jarrodek/ChromeRestClient#956]
I am using version 8.19.60.296 
When sending files as multipart/form-data the filename in the multipart is always named blob

Host: testnode.local
Connection: keep-alive
Content-Length: 20687632
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Origin: chrome-extension://apcedakaoficjlofohhcmkkljehnmebp
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary9UQP8BwOAfxuf2Yy
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4
------WebKitFormBoundary9UQP8BwOAfxuf2Yy
Content-Disposition: form-data; name="fileUpload3"; filename="blob"
Content-Type: video/mp4

I would like to have the real name as filename.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I'm rebuilding this module right now because of other issue with file sending. It will be fixed with the release containing the other fix.

**Comment by jarrodek** [comment]
Please refer to #945 for more information.

I am closing this as a duplicate.
