### ISSUE TITLE
Allow headers in uppercase.

### ISSUE THREAD

**Issue by geynen** [jarrodek/ChromeRestClient#958]
I am writing the headers in capital letters but apparently the program sends it in lowercase, which means that the web service to which I connect does not detect it.

## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.87
Platform: Windows (10)

**Comment by jarrodek** [comment]
Hi, 

Thank you for your issue report.
As for header case-insensitive, please, refer to the issue #491for detailed discussion and explanation. I'm closing this as a duplicate. 

Thanks.
