### ISSUE TITLE
Typo in timeout error message

### ISSUE THREAD

**Issue by ledux** [jarrodek/ChromeRestClient#962]
The request has been aborted manually or because of the **conection** timeout.

Should be **connection**

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (7)

## Steps to reproduce
1. Send a request 
2. Press abort button

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.

I'll fix it in coming days.
