### ISSUE TITLE
Click to insert url field not working

### ISSUE THREAD

**Issue by yosvanyllr** [jarrodek/ChromeRestClient#963]
Hi
By clicking on any link inside response body, the request url does not changes at all. We have to copy / paste it manually. What is wrong?

## Expected outcome
The clicked link should be copied to request field

## Actual outcome
Nothing happens!

## Versions
App: 8.19.60.296-stable
Chrome: 57.0.2987.54
Platform: Linux (-)

## Steps to reproduce
1. Call API service
2. Clink on response link

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
This issue was already fixed and the update is waiting in the beta channel.
Very soon I'll release updated version.
