### ISSUE TITLE
Advanced REST client file upload issue

### ISSUE THREAD

**Issue by balaji448** [jarrodek/ChromeRestClient#965]
File data is not posting to the server from the latest update, this bug is not there in old version.

## Expected outcome
File should be posted to the server url like as form submit.

## Actual outcome
File data is not posting to the server in Content-Type: multipart/form-data 

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (7)

## Steps to reproduce
1. Use post while submitting form.
2. Use enctype="multipart/form-data"

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
It is not issue with the app but with Chrome.
Please refer to #945 for more information.

I am closing this as a duplicate.
