### ISSUE TITLE
Spelling mistake in UI of Advanced Rest Client

### ISSUE THREAD

**Issue by sumitsonawane** [jarrodek/ChromeRestClient#966]
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 9.14.64.305-stable
Chrome: 57.0.2987.74
Platform: Linux (-)

## Steps to reproduce
1. go to Advanced rest client
2. click on saved menu
3. check spelling of Open google drive button
![screenshot from 2017-02-28 15 37 53](https://cloud.githubusercontent.com/assets/26084899/23401146/a7166368-fdcc-11e6-8924-550935740664.png)

**Comment by kfrancis** [comment]
![advanced rest client 2017-03-01 12 01 12](https://cloud.githubusercontent.com/assets/67574/23471268/c350aca0-fe76-11e6-8a92-a6dfcda53eb0.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. I should read everything twice before commit to git :]

I'll update it with the next release.

**Comment by jarrodek** [comment]
This is fixed already
