### ISSUE TITLE
no response headers shown

### ISSUE THREAD

**Issue by FBak** [jarrodek/ChromeRestClient#967]
when I try to call an oData service in xhr mode i can't get any response header, only a big red dot is shown

## Expected outcome
It should show me response headers

## Actual outcome
I can only see a big red dot

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (7)

## Steps to reproduce
1. call a service in xhr mode
2. wait for response
3. search for response headers

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. The headers are there but not visible by default. You have to open the headers panel by clicking on the "details" button on the right hand side of the status code.
And then you'll see headers as usual.

I'm closing this WAI.

**Comment by thardy** [comment]
The headers are not there.  Clicking the "details" button causes "Response Headers" to appear with a big red dot next to it, only there ARE NO RESPONSE HEADERS.

**Comment by FBak** [comment]
![big red dot](https://cloud.githubusercontent.com/assets/14869827/24158798/9cacd730-0e5d-11e7-8991-40bce430b4fb.png)

I hope this time image is attached correctly...
when I'm NOT in xhr mode headers are shown properly, when I turn xhr mode on only a big red dot is shown.

**Comment by jarrodek** [comment]
this is fixed already
