### ISSUE TITLE
Cannot edit socket connection

### ISSUE THREAD

**Issue by kabbottcc** [jarrodek/ChromeRestClient#970]
Your description here

After launching ARC Beta, selected Socket for request type. Socket URL was prepopulated with the value used in last session.  When I click on the url, it is uneditable, so I cannot change to another socket (see screenshot).  Behavior is inconsistent.  Actions such as clicking outside of ARC then back in or clicking on the connect/disconnect then selecting the url (only) sometimes allowed me to edit the socket value, but usually not.

Also, when clicking on the (uneditable) url in the url pop-up it would automatically connect even though I had not clicked on the Connect button.

This was in the beta version.

## Expected outcome
What should happen?
I should be able to edit the url by clicking on it at any time it is disconnected.

## Actual outcome
What happened?

## Versions
App: 9.13.64.304-beta
Chrome: 56.0.2924.87
Platform: Windows (7)

## Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/12358109/23479840/01d362ae-fe83-11e6-89f7-8157c6cac458.png)

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
It looks like the autocomplete list is above the URL input instead of under it.

Quick workaround is to press `ESC` key to make the suggestions list disappear.

I'll update it with next release.

**Comment by jarrodek** [comment]
This is fixed already
