### ISSUE TITLE
Suddenly stopped recieving data from ARC

### ISSUE THREAD

**Issue by bonuskek** [jarrodek/ChromeRestClient#979]
My app was working fine and was getting json from ARC and today before i finalize my app and create a realease version i run it for last time from android studio and everything  seems OK.  But when i tried send post from ARC as data for notification, nothing happened(also no error from ARC console) and there was nothing in logcat about it. Also i m still getting notifications via Firebase console.

## Expected outcome
Getting data from ARC

## Actual outcome
Nothing happened without any errors

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (8.1)

PS
When i search in google for it i saw a solution about to recreate server key from api console but since it is linked with cloud and firebase i didn't apply it yet. link:
http://stackoverflow.com/questions/42222132/fcm-notification-is-not-working-if-i-send-it-by-using-arc-advanced-rest-api

**Comment by bonuskek** [comment]
#Update 
I got one of the datas i sent after 4 hours. So i m not sure to recreate server key but not sure why does it take too long.

**Comment by jarrodek** [comment]
Hi,

It is an issue with firebase (my guess) and not with the ARC. You may contact their customer support. I can't give you advices about their services.

Thanks.
