### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by brainlet-ali** [jarrodek/ChromeRestClient#980]
Just a typo

## Expected outcome
It should say: "OPEN FROM GOOGLE DRIVE"

## Actual outcome
It sayS: "OPEB FROM GOOGLE DRIVE"

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I will update this very soon.

**Comment by jarrodek** [comment]
This has been fixed already
