### ISSUE TITLE
No response headers!!

### ISSUE THREAD

**Issue by thardy** [jarrodek/ChromeRestClient#982]
When I click on the Details button to the right of the status code that is returned for my request.  I see a "Response Headers" show up with a big red dot next to it.  No response headers are shown.

If I make the exact same request in Postman, all the headers show up just fine.  What happened to the response headers?????  What's with the big red dot?  How did you guys miss this?

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

I can't reproduce the problem. Is this happening for a particular endpoint or always? Also, is there's an error in the log viewer?

**Comment by r-pluss** [comment]
Experiencing the same issue, all endpoints, but with only xhr-mode enabled. 
No associated errors in logs, no response headers displayed, just a red dot.

![arc_issue](https://user-images.githubusercontent.com/12532565/27351430-53b1e5ce-55cb-11e7-9069-92220b21fabf.PNG)


#967 seems to indicate the same issue, relating to xhr, but I see it was closed with a WAI label, so are response headers not intended to be displayed when using xhr requests?

**Comment by jarrodek** [comment]
Thank you for clarification. I'' take care of it.

**Comment by HilmarDemant** [comment]
same issue for me

**Comment by jarrodek** [comment]
Thanks for the update. I'm aware of the issue and am on it in current development cycle.

**Comment by jarrodek** [comment]
This is fixed already.
