### ISSUE TITLE
POST call with image file as a part of form data has 'Content Length' inaccurate

### ISSUE THREAD

**Issue by mayankbhagya** [jarrodek/ChromeRestClient#985]
POST call with image file as a part of form data has 'Content Length' inaccurate

## Expected outcome
Content Length header should be set based on image file size

## Actual outcome
When I made a post call with an image as a part of the form data, the server doesn't receive any image and Content Length is set to 0

## Versions
App: 9.14.64.305-stable
Chrome: 57.0.2987.110
Platform: Linux (-)

## Steps to reproduce
1. Select POST
2. Enter URL
3. Select multipart/form-data from content type list
4. Click on Files
5. Browser for image file and select correct image
6. Hit send
7. Check Request Headers in Details section & check content length
8. Check Server doesn't receive image correctly

**Comment by jarrodek** [comment]
Hi,

This is related to #945 and it's confirmed Chrome bug. I am working on the workaround. 
I'm closing this as a duplicate so please, subscribe to referenced issue for updates.
