### ISSUE TITLE
Design bug/shifted bottom bar

### ISSUE THREAD

**Issue by alekseyrozh** [jarrodek/ChromeRestClient#991]
Minor design bug
![2](https://cloud.githubusercontent.com/assets/10654710/24733965/97870258-1a83-11e7-810f-c32391e1808c.png)

## Actual outcome
shifted bottom bar

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (10)

## Steps to reproduce
 a lot of maximizing/minimizing + resizing

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report. 
I am aware of it. I never had time to fix it. 
I will try to fixed with next release.

**Comment by jarrodek** [comment]
This is fixed now.
