### ISSUE TITLE
Uses old URL after port removed

### ISSUE THREAD

**Issue by IverBand** [jarrodek/ChromeRestClient#992]
In testing out a cloud app vendor's API, I executed the following URL in a POST request:

https://app.ebenefitsyncdemo.com:8005/api/data/v1.0/token

Then the vendor changed their configuration to use the standard HTTPS port

So I tried

https://app.ebenefitsyncdemo.com/api/data/v1.0/token

without success.  Network monitoring software indicated that ARC was still using port 8005.  

I tried clearing my advancedrestclient cookie, but that had no effect.

**Comment by jarrodek** [comment]
Is this behavior still happening? I can't reproduce it.

**Comment by IverBand** [comment]
I don't know.  I switched to using another tool for service testing soon after this happened, so I haven't used this tool for a while.  I will close the issue.
