### ISSUE TITLE
Typo on "Saved" screen

### ISSUE THREAD

**Issue by shanabus** [jarrodek/ChromeRestClient#996]
When you first click the "Saved" tab along the left, you see a message like this:

![arc-typo](https://cloud.githubusercontent.com/assets/2854605/25646152/8615cb52-2f83-11e7-92d4-74d444e886d6.PNG)

That should read "OPEN" instead of "OPEB FROM GOOGLE DRIVE" right?

## Expected outcome
Button should be labeled "OPEN FROM GOOGLE DRIVE"

## Actual outcome
Button was labeled "OPEB FROM GOOGLE DRIVE"

## Versions
App: 9.14.64.305-stable
Chrome: 58.0.3029.81
Platform: Windows (10)

## Steps to reproduce
1. Install ARC plugin
2. Click "Saved" tab along left
3. Observe misspelled button label

**Comment by jarrodek** [comment]
This is fixed, soon will be released.
