### ISSUE TITLE
Windows profile corrupt, new profile created but cant access my saved projects. 

### ISSUE THREAD

**Issue by netsuco** [jarrodek/ChromeRestClient#998]
Good day. 

Not sure if this was resolved before but my pc profile was corrupt and created a new one. How do I access my saved projects on the Advanced Rest Client? I don't have a google drive backup but can access contents of my old profile. 

Regards

**Comment by jarrodek** [comment]
Sorry, but I can't help you with that. Seek assistance in Chromium forums.
