### ISSUE TITLE
Cookies not being sent

### ISSUE THREAD

**Issue by f8k8** [jarrodek/ChromeRestClient#999]
When testing my API, I used to be able to do the following:
- POST to the login URL, which returned a `Set-Cookie` header.
- POST / GET from other paths at the same domain, and the authentication cookie would be correctly passed to the API.

Recently, the cookies have stopped being passed. The response from the login URL gives:
`Set-Cookie: sid=<Auth Data>; Max-Age=31536000; Expires=Sat, 12 May 2018 10:05:43 GMT; Secure; HttpOnly; SameSite=Strict; Path=/`

However, calling a different path straight after no longer seems to include the cookie.

The login path which returns the cookie is: `/api/v1/user/login`. It seems like any path directly under the `/api/v1/user/` seems to have the cookie set, but other paths dont. I.e.
- `/api/v1/user/` - Has cookie
- `/api/v1/user/foo` - Has cookie
- `/api/v1/user/foo/bar` - Doesn't have cookie
- `/api/v1/foo/` - Doesn't have cookie

I've tried clearing the cookies but it's still not working. This used to work fine until recently.

Looking at the debug console for ARC, there's a line at the start of the log:
`window.localStorage is not available in packaged apps. Use chrome.storage.local instead.`
I'm not sure if this is the issue though, as the cookie does seem to be sent for some requests as noted above.

Running on Chrome Version 57.0.2987.133 on Windows 10 Version 1703 Build 15063.296.

Edit: ARC version: App: 9.14.64.305-stable

**Comment by jarrodek** [comment]
Hi,

I can't reproduce this behavior in app v 10 anymore. Cookie support module was rewritten in this version.
If it's still an issue, please reopen.
